### ISSUE TITLE
Allow runtime adding of SSH keys to authorized_keys

### ISSUE THREAD

**Issue by rfkrocktk** [phusion/baseimage-docker#107]
As far as I understand, there's no way to currently add SSH keys to a Docker image based on baseimage at _runtime_ as opposed to _compile-time_. In order for me to get my SSH keys into my Docker machines, I need to write a custom Dockerfile based on baseimage to add them. Rinse and repeat, ad infinitum.

Instead of making it a compile-time dependency, why not add a script in `/etc/my_init.d/` that reads out all environment variables matching `SSH_KEY_\d+`, and append them to the default user's `$HOME/.ssh/authorized_keys`, and set the permissions properly? 

For example, the user would run his container like this:

```
sudo docker run -d -e SSH_KEY_0="$(cat ~/.ssh/id_rsa.pub)" phusion/baseimage
```

The script would internally do the following:

**/etc/my_init.d/01_add_ssh_keys.sh**

```
#!/bin/sh

source /etc/environment.sh

test -d $HOME/.ssh && mkdir $HOME/.ssh

: > $HOME/.ssh/authorized_keys

for var in get_the_environement_variables ; do 
    cat "$var" >> $HOME/.ssh/authorized_keys
done

chown $USER:$USER $HOME/.ssh/authorized_keys
chmod 0600 $HOME/.ssh/authorized_keys
```

Obviously, this is a contrived example, but this would enable users to add their own SSH keys to Docker images _a lot more easily_ and would solve the whole `nsenter` and `lxc-attach` problems for now, and would make it possible for the common user to get started quickly without having to write a Dockerfile.

**Comment by FooBarWidget** [comment]
In the next version of baseimage-docker, we'll support 'docker exec' by default and disable SSH by default, so I don't think this is necessary. In case you want to support environment variable-controlled keys, I believe it should be done outside of baseimage-docker.
