### ISSUE TITLE
sshd UsePrivilegeSeparation is broken

### ISSUE THREAD

**Issue by ksaio** [phusion/baseimage-docker#109]
Hi,

I was having trouble using the image on CentOS 7 host. Was not able to ssh with my own key or insecure key. 

But after some throuble shooting i found this https://github.com/dotcloud/docker/issues/6103

So I add this to my Docker file
RUN echo "UsePrivilegeSeparation no" >> /etc/ssh/sshd_config

And i'm able to ssh to the container.

**Comment by FooBarWidget** [comment]
Since this is a Docker bug, I'm closing this issue.
