### ISSUE TITLE
Can't start additional daemons

### ISSUE THREAD

**Issue by dancodes** [phusion/baseimage-docker#110]
When I try to add custom daemons to my image, I get the following error:

    runsv mysql: fatal: unable to start ./run: file does not exist
    runsv apache: fatal: unable to start ./run: file does not exist

My Dockerfile:

	RUN mkdir -p /etc/service/apache
	ADD ./bin/apache.sh /etc/service/apache/run

	RUN mkdir -p /etc/service/mysql
	ADD ./bin/mysql.sh /etc/service/mysql/run

	RUN chmod +x /etc/service/apache/run
	RUN chmod +x /etc/service/mysql/run

	RUN chown root:root /etc/service/apache/run
	RUN chown root:root /etc/service/mysql/run

/bin/mysql.sh:

	#!/bin/sh
	exec /sbin/setuser www-data /usr/bin/mysqld_safe >>/var/log/mysql_exec.log 2>&1

Any ideas?

**Comment by FooBarWidget** [comment]
So can I consider this issue to be solved?

**Comment by msgre** [comment]
I have similar issue and problem was in one extra space character on first line. Instead of:

```
#!/bin/bash
...my script
```

I have:

```
 #!/bin/bash
^
+--- here! do you see it?
```

**Comment by ababkov** [comment]
FYI - this was coming back with "./run: file does not exist" for me for any services i attempted to add. When the script was run directly on the box, the following additional info was presented: an "Invalid interpreter /#!/bin/sh^M" (or similar).

Issue ended up being dos vs unix line endings. Running the init files through from dos2unix / http://www.virtualhelp.me/linux/164-dos2unix-missing-ubuntu-1004 resolved the issue for me after 4 hours of head banging...

**Comment by inversion** [comment]
As @FooBarWidget alluded to you should check that your daemon scripts are executable, this solved the issue for me.
