### ISSUE TITLE
Document selection of syslog-ng over rsyslog

### ISSUE THREAD

**Issue by jfkw** [phusion/baseimage-docker#114]
The table of included components lists syslog-ng as the syslog daemon. It would be helpful  if details were provided there as to why syslog-ng was selected over rsyslog, ubuntu's default syslog daemon.

Such information is provided for the choice of runit over upstart. This helps the prospective user evaluate her own priorities (e.g. consistency with ubuntu defaults) vs. baseimage-docker defaults, which likely have good reasoning behind them vis. docker tradeoffs.

**Comment by milani** [comment]
I encounter problems with syslog-ng while using perl scripts if they use `Sys::Syslog`. But the script works fine when using rsyslog.
