### ISSUE TITLE
syslog-ng doesn't seem to work

### ISSUE THREAD

**Issue by amoghe** [phusion/baseimage-docker#118]
Seen on 0.9.9

Symptoms:
- `sv status` says `down: syslog-ng: 0s, normally up, want up`
- No /var/log/syslog file is present in container (started with `my_init -- /bin/bash -l`
- `ps ax` output has entry for `runsv syslog-ng` but not for the `syslog-ng` itself

Further investigation
- Attempting to run syslog-ng by hand (after stopping it from runit) spits out the following error:

```
root@e998...e57:/# syslog-ng -F -p /var/run/syslog-ng.pid
syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
Plugin module not found in 'module-path'; module-path='/usr/lib/syslog-ng/3.3.4', module='afsql'
Error opening file for reading; filename='/proc/kmsg', error='Operation not permitted (1)'
Error initializing source driver; source='s_src', id='s_src#1'
Error initializing message pipeline;
```

**Comment by mabushey** [comment]
FROM phusion/baseimage:0.9.22
root@77cedf6ff00c:/# ps aux | grep kmsg
root         7  0.0  0.0    200    36 ?        S    23:15   0:00 /usr/bin/runsvdir -P /etc/service log: ge pipeline;?Error opening file for reading; filename='/proc/kmsg', error='Operation not permitted (1)'?Error initializing source driver; source='s_src', id='s_src#1'?Error initializing message pipeline;?Error opening file for reading; filename='/proc/kmsg', error='Operation not permitted (1)'?Error initializing source driver; source='s_src', id='s_src#1'?Error initializing message pipeline;?

I think you have to comment out system() (line 20) from the source s_src {} block in /etc/syslog-ng/syslog-ng.conf
