### ISSUE TITLE
Substitute hosts with /usr/bin/workaround-docker-2267

### ISSUE THREAD

**Issue by rseiffert** [phusion/baseimage-docker#146]
In my Dockerfile I do
RUN /usr/bin/workaround-docker-2267
ADD hosts /etc/workaround-docker-2267/hosts
where hosts is a modified hosts file. 

BUT the original hosts-file in /etc/workaround-docker-2267/ does not get substituted. Am I doing something wrong? "cat hosts" in /etc/workaround-docker-2267 does not show my hosts-file, but the one provided by the workaround.

If I do 
bash# echo 127.0.0.1 my-test-domain.com >> /etc/workaround-docker-2267/hosts
bash# ping my-test-domain.com
afterwards it works like supossed.

**Comment by FooBarWidget** [comment]
Merged int o#155.
