### ISSUE TITLE
Can we get similar image for 14.10?

### ISSUE THREAD

**Issue by kesavkolla** [phusion/baseimage-docker#150]
I've to use ubuntu 14.10 for one of strange packaging issue with 14.04.  Is there any base image for 14.10?  If not can you please point me to direction how to build one for 14.10?

Thanks

**Comment by FooBarWidget** [comment]
We only publish images for 14.04 because we value stability. As others have mentioned, it's easy to create your own fork based on whatever Ubuntu version you want.
