### ISSUE TITLE
trying to run Firefox with `docker exec`

### ISSUE THREAD

**Issue by mascip** [phusion/baseimage-docker#163]
Hi, in an effort to try and "Dockerize all the tings", I managed to run Firefox in phusion-baseimage with `ssh`, as you can see [here](https://github.com/mascip/X11-forwarding-with-phusion-baseimage/tree/master/phusion-ssh). Now I'm trying to get it to work with `docker exec`.

I also managed to run firefox with `docker exec` in an **ubuntu:14.04** container, [here](https://github.com/mascip/X11-forwarding-with-phusion-baseimage/tree/master/ubuntu-x11-port). One thing to note, is that it works with `docker exec` but not with `nsenter` (no idea why).
Another thing to note, is that to avoid using `xhost +` (which is not safe) I **created a new user** called `developer` with the right permissions (I stole the code from [this blog post](http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/)).

For phusion-baseimage you can find my current attempt [here](https://github.com/mascip/X11-forwarding-with-phusion-baseimage/tree/master/phusion-x11-port).

I manage to run **Leafpad**, but not Firefox. For Leafpad, for some reason I need to use `setuser` to make it work:

    docker exec px11 setuser developer leafpad &

**WORKS**, while
   
     docker exec px1 leafpad &

**DOES NOT WORK**: I get the usual X error

    No protocol specified
    leafpad: Cannot open display:

I have no idea why `setuser` makes it work. It must have something to do with the fact that `root` is the default user in phusion-baseimage, and I created a new user called `developer`. But well, in the end I was happy as I got Leafpad to run.

**For Firefox**, the problem also seems related to the user and permissions. I manage to **try** to launch `firefox` by using `setuser` (without `setuser` I get the usual X error), but then Firefox gives me this error:

    Your Firefox profile cannot be loaded. It may be missing or inaccessible.

which makes me think "Damn! It launches but doesn't have the right permissions to read the `/home/developer/.mozilla/firefox` directory, where its profile is."

I have tried accessing the container with `docker exec -ti px11 /bin/bash`, and then doing

    chmod 777 -R /home/developer 
    chown developer:developer -R /home/developer
    setuser developer firefox

with the same unsuccessful result.

I see two ways out of this now:
 - giving `developer` the right "super powers" to be able to run Firefox successfully
 - forget about `developer`, and instead try to give these "super powers" to root.

I have tried this second option by replacing "developer" by "root" in the Dockerfile, and "/home/developer" by "/root", but it didn't work: I just got the usual X error. Intuition tells me it is the best paths to follow, but I have no idea how to overcome the X error in this case.

And I have no idea how to go further with the first option too.

Any help would be greatly appreciated.
 - what am I doing wrong? 
 - what could I try? 
 - what/where could I learn in order to do less groping around in the dark?

**Comment by FooBarWidget** [comment]
Both Docker and baseimage-docker are primarily meant for server use cases, not GUI use cases. There are probably all kinds of issues that need to be solved in order to make it work well (in general) with GUI apps like Firefox. It is outside the scope of the baseimage-docker project to deal with them.
