### ISSUE TITLE
more minimalistic

### ISSUE THREAD

**Issue by tcurdt** [phusion/baseimage-docker#165]
I like the idea of this image - but frankly speaking for most of my use cases I don't need syslog or cron. It would be great if the base image would be a little more minimalistic - but allows for inclusion of syslog, cron and ssh.

**Comment by FooBarWidget** [comment]
Marking it for serious considering in 0.9.16.

**Comment by endersonmaia** [comment]
@FooBarWidget I couldn't find any docs on the branching system you're using.

Should I merge it with the `next` branch ?

**Comment by FooBarWidget** [comment]
Yes. Since today, `next` is the development branch. It used to be `master`, but users read documentation on `master` so `master` should refer to the latest stable version.

**Comment by UserTaken** [comment]
I'm wondering why VIM and Nano is installed when VIM-tiny already come with Ubuntu:14.04? Removing that from utilities.sh will save 40MB. Less is also preinstalled from Ubuntu:14.04.

**Comment by wsouto** [comment]
@UserTaken has a point. 40MB is quite considerable, at least for people where the Internet is not so good to say the least... And, afterwhile, it is quite easy to install any of them if the user want or need to.

**Comment by FooBarWidget** [comment]
In 0.9.17, I have removed nano. Nano was there because it's my personal preference, but I think not many people share this preference with me. I have also replaced vim with vim-tiny -- I didn't know about it!

Virtual image size dropped from 280.2 MB to 237.7 MB.
