### ISSUE TITLE
policy-rc.d denied execution of reload

### ISSUE THREAD

**Issue by skyflyer** [phusion/baseimage-docker#167]
There is a cron.daily job to rotate logs inside container and the syslog-ng log rotation tries to reload syslog-ng. When doing to, the reload is denied, though I don't know exactly why. I'm getting cron.daily reports that:

    /etc/cron.daily/logrotate:
    invoke-rc.d: policy-rc.d denied execution of reload.

syslog-ng seems to be running and logging OK though. Is this related to runit running the syslog deamon and logrorate script should be modified? Should the postrotate be changed from

    invoke-rc.d syslog-ng reload > /dev/null

to

    sv reload syslog-ng

?

**Comment by FooBarWidget** [comment]
This issue has been fixed. Thanks for reporting it and sorry for the delay.
