### ISSUE TITLE
Reference `docker exec` in "Running a command in an existing container" section

### ISSUE THREAD

**Issue by shideon** [phusion/baseimage-docker#168]
I'm new to docker so I could definitely be missing something but couldn't the [Running a command in an existing container](https://github.com/phusion/baseimage-docker#running-a-command-in-an-existing-running-container) section reference the [`docker exec`](http://docs.docker.com/reference/commandline/cli/#exec) command?

**Comment by FooBarWidget** [comment]
Sorry responding so late, we're at small team at Phusion and it's been way too busy the past few months. I've finally come around to investigating docker exec.

I've found that docker exec is just a thin wrapper around nsenter, though with a few changes. Most of the usual cons of nsenter still applies. Therefore, I think it's not a good idea to remove SSH entirely in favor of docker exec. What we can do is replacing nsenter with docker exec, and disabling SSH by default. I've begun work on this.
