### ISSUE TITLE
baseimage-docker-nsenter: failed to parse pid:

### ISSUE THREAD

**Issue by abrongersma** [phusion/baseimage-docker#170]
Docker-bash errors when a container has a high valued PID.

```
root@docker-host:~# docker-bash 3e77224d4fc4
baseimage-docker-nsenter: failed to parse pid: '1.488899e+06'
```
I took a look at how docker-bash pulls the PID and ran that manually.
```
root@docker-host:~# docker inspect -f "{{ .State.Pid }}" 3e77224d4fc4
1.488899e+06
```
The following code takes the PID and converts it to decimal notation and rounds it to the nearest integer. 
```
root@docker-host:~# docker inspect -f "{{ .State.Pid }}" 3e77224d4fc4 | awk '{ print sprintf("%.f", $1); }'
1488899
```

**Comment by FooBarWidget** [comment]
Since we're going to remove nsenter in favor of docker exec, this issue should now be considered outdated.
