### ISSUE TITLE
shutdown and reboot don't work as expected

### ISSUE THREAD

**Issue by smfreegard** [phusion/baseimage-docker#172]
If you SSH to a phusion-baseimage based container and issue shutdown or a reboot command - then nothing happens, my_init seems to ignore them.

I realise that you'd typically do this from externally from the docker host, but it would be 'nice' if this worked as expected for the times that you might not have access to the external host but actually wanted to stop the container over SSH or restart everything via reboot.

**Comment by FooBarWidget** [comment]
Shutdown and reboot are not supposed to work. They do a lot of close-to-the-hardware things like synching disks, unmounting filesystems, etc. If you want this to work, then the proper place to implement this is in Docker. It doesn't appear that Docker provides any mechanism for doing this though.
