### ISSUE TITLE
chpasswd not working

### ISSUE THREAD

**Issue by mzedeler** [phusion/baseimage-docker#181]
I was using the latest phusion image and couldn't get chpasswd to work.

It turns out that this is a known issue with Ubuntu, fixed here:

https://github.com/sequenceiq/docker-pam/blob/master/ubuntu-14.04/Dockerfile

I've verified that adding a custom build of PAM solves this issue. Just add the following four lines to the Dockerfile (as provided in the link above):

    # Setup build environment for libpam
    RUN apt-get update && apt-get -y build-dep pam
    # Rebuild and istall libpam with --disable-audit option
    RUN export CONFIGURE_OPTS=--disable-audit && cd /root && apt-get -b source pam && dpkg -i libpam-doc*.deb libpam-modules*.deb libpam-runtime*.deb libpam0g*.deb

**Comment by FooBarWidget** [comment]
I'm wary about introducing this change. I see the solution, but I can't find a reference to the underlying bug. Do you have more information about the bug?

**Comment by mzedeler** [comment]
Yes. I forgot to include a link to a bug description I found. Here it is: https://github.com/docker/docker/issues/5704

**Comment by FooBarWidget** [comment]
I've run into this issue myself, and I've confirmed that the fix works well, so planning this for the next release.

**Comment by mzedeler** [comment]
:+1:

**Comment by mzedeler** [comment]
Great work, @FooBarWidget :-)
