### ISSUE TITLE
messages from syslog-ng on stdout

### ISSUE THREAD

**Issue by michaelsbradleyjr** [phusion/baseimage-docker#186]
I've been rebuilding my images against the latest version of `phusion/baseimage-docker` and noticed that just after a login, text similar to the following is logged to stdout:

`Jan 23 20:59:47 ccca01551c12 syslog-ng[17]: syslog-ng starting up; version='3.5.3'`

Then, at regular intervals, `syslog-ng` messages related to `cron` are likewise being logged to stdout.  I've found that I cannot suppress them with the `--quiet` flag to `/sbin/my_init`.

Is this behavior expected? I don't find it to be terribly problematic; but it's a tad annoying when I'm in "dev mode" working inside a container. In a production context such messages would be a non-issue for me.

**Comment by FooBarWidget** [comment]
This is the syslog-to-docker-logs forwarder. You can turn it off temporarily with:

    sv stop /etc/service/syslog-forwarder

Or permanently in your Dockerfile with:

    RUN touch /etc/service/syslog-forwarder/down
