### ISSUE TITLE
No such file or directory: '/etc/container_environment/PATH'

### ISSUE THREAD

**Issue by chris-martin** [phusion/baseimage-docker#195]
I got here from [*Docker and the PID 1 zombie reaping problem*](http://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/):

> all you have to do is to is to spend 5 minutes, either on using Baseimage-docker, or on importing [our 350 lines my_init init system](https://github.com/phusion/baseimage-docker/blob/rel-0.9.16/image/bin/my_init) into your container

I need to be using an Ubuntu base image, so I picked the latter option, and copied `my_init` into `/sbin`.

When I run it ...

    docker run image my_init -- command

I get ...

```
Traceback (most recent call last):
  File "/sbin/my_init", line 334, in <module>
    main(args)
  File "/sbin/my_init", line 253, in main
    export_envvars()
  File "/sbin/my_init", line 81, in export_envvars
    with open("/etc/container_environment/" + name, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/container_environment/PATH'
```

Are there some more instructions I'm missing? Or is my_init not actually suitable to be used by itself outside the context of baseimage-docker?

**Comment by FooBarWidget** [comment]
This is my_init's [environment variable persistence mechanism](https://github.com/phusion/baseimage-docker#environment_variables). It expects the directory /etc/container_environment to exist within the container. So you can fix this either by creating this directory, or by removing the lines in my_init that deal with this.

**Comment by FooBarWidget** [comment]
In e575443aba48e3, I made it so that `my_init` does not use /etc/container_environment if it does not exist. This way, you do not need to modify things yourself.
