### ISSUE TITLE
sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory

### ISSUE THREAD

**Issue by pcjacobse** [phusion/baseimage-docker#196]
When trying to increase the receive and send buffers (using `sysctl -w net.core.rmem_max 4194304` and `sysctl -w net.core.wmem_max=1048576`) i get the error `sysctl: cannot stat /proc/sys/net/core/rmem_max: No such file or directory` and `sysctl: cannot stat /proc/sys/net/core/wmem_max: No such file or directory`

I'm trying to setup a transmission docker, which suggest increasing the buffer size.

**Comment by FooBarWidget** [comment]
I think that's because Docker limits privileges within containers. Maybe running your container with --privileged will help, but I don't know. In any case, this is not a baseimage-docker problem.
