### ISSUE TITLE
Cron jobs does not run because of hard links to crontab files

### ISSUE THREAD

**Issue by zoltan-tornoczky** [phusion/baseimage-docker#198]
I'm using the baseimage to build a container which have cron jobs written to cron.d by the Dockerfile like:
`RUN echo "30 1    * * *   root    /root/backup-svn.sh\n" >> /etc/cron.d/backup-svn`

But the jobs won't run and there are messages in the syslog like:
`Feb 26 08:43:01 65040e4fbb39 /usr/sbin/cron[18]: (*system*) NUMBER OF HARD LINKS > 1 (/etc/crontab)
Feb 26 08:43:01 65040e4fbb39 /usr/sbin/cron[18]: (*system*backup-svn) NUMBER OF HARD LINKS > 1 (/etc/cron.d/backup-svn)`

The problem is probably caused by Docker hardlinking the unmodified files for the container. I'm not that much into Docker internals, but this is probably caused by the overlay fs driver, I found hard links for the cron files under /var/lib/docker/overlay/

I've got a workaround, a simple touch on the cron files makes the file non-hardlinked ( ls -l shows link count 1), and cron seems to process the files (no errors in syslog and the job did what it had to do). I used this line in the Dockerfile to touch the files on container startup:
`RUN echo "#!/bin/bash\ntouch /etc/crontab /etc/cron.d/*" >> /etc/my_init.d/touch-crond && chmod 744 /etc/my_init.d/touch-crond`

**Comment by croemmich** [comment]
Seeing the same issue.

**Comment by abelaska** [comment]
Same here.

**Comment by rhoerbe** [comment]
Zoltan's fix did not work here, reverted to starting cron from CMD.

I wonder if Vixie cron is dockerish at all. It is writing to /var/log and there is no way to disable message via mail. RH's cronie seems to be more sensible.

**Comment by saikat** [comment]
@rhoerbe I believe your solution may not work on Overlay (at least, I've been battling with this as well).  Overlay seems to have a bug with tail -f because it does not implement inotify correctly.  See this bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/882147

**Comment by jfoy** [comment]
https://github.com/docker/docker/issues/16813

**Comment by Theaxiom** [comment]
This should be resolved by #348

**Comment by iaon** [comment]
@Theaxiom Are you sure? #348 is fix for #345  crontab Cannot make/remove an entry for the specified session. I have no clue how it could fix  "NUMBER OF HARD LINKS > 1" issue .

**Comment by BunnyHolder** [comment]
I suggest starting cronjobs at the end of main process. `crontab /some/file.cron`

**Comment by hyperknot** [comment]
Can anyone report back if this is still an issue or not? I think #348 was a totally different fix and shouldn't have closed this one.

**Comment by Theaxiom** [comment]
Let's re-open this until we can confirm.
