### ISSUE TITLE
Add information on how to start syslog-ng daemon

### ISSUE THREAD

**Issue by else** [phusion/baseimage-docker#200]
The [webpage](http://phusion.github.io/baseimage-docker/) says:
> The syslog daemon is not run automatically. You have to start it yourself.

However I could not find any information on that in the [documentation](https://github.com/phusion/baseimage-docker). Could you please add information on how to start the syslog-ng daemon?

**Comment by FooBarWidget** [comment]
Which "webpage" do you mean? Your link doesn't go anywhere.

**Comment by else** [comment]
Sorry, fixed that.

**Comment by else** [comment]
Oh, I think I got it: the quote was part of the motivation for baseimage-docker. Sorry.
