### ISSUE TITLE
running startup scripts after runit

### ISSUE THREAD

**Issue by Tim-Erwin** [phusion/baseimage-docker#202]
In one of my my_init scripts I'm logging to syslog - which fails because syslog-ng has not been startet at that time.

Is there a way to execute scripts after booting the runit daemon? I mean, I can always put stuff in the entrypoint script, but that's not really an elegant and extendable way.

**Comment by FooBarWidget** [comment]
Unfortunately not, but the solution isn't as easy as "executing after booting the runit daemon". Please see my comments in #44, which basically addresses the same issue as what you describe here.

**Comment by Tim-Erwin** [comment]
Yeah, I've seen that issue. Thanks for the comment though.

**Comment by tdemalliard** [comment]
Stupid idea : why not puting your script in a service that remove itself after the start ?
I mean , write this in /etc/service/after_syslog_ng/run
```
#!/bin/sh
echo "bla"
sv stop after_syslog_ng
rm -rf /etc/service/after_syslog_ng
```

**Comment by FooBarWidget** [comment]
@tdemalliard Because that won't work. As I explained in #44, just starting something after Runit is not enough. You also have to have code for actually waiting until the service is up, where the definition of "up" is different for every service.

**Comment by saamich** [comment]
@tdemalliard 
I do so:
If need run one command one time after first run conteiner , i create runit service 'firstboot' which perform the necessary work. if need wait start/stop other service- use this script https://gist.github.com/saamich/ab0eb33a53390892b638. If need for other service start after service 'firstboot', this service have 'down' file and in runit 'firstbot' script write like this https://gist.github.com/saamich/af989ed9c4c263bc9ba9

**Comment by Tim-Erwin** [comment]
Thanks for the ideas. For me the simplest version was to put those lines in my entrypoint.sh:

    sv check syslog-ng
    run-parts /root/startup/

Then instead of placing my scripts in */etc/my_init.d/* I put them in */root/startup/*.
