### ISSUE TITLE
Recommended syntax for single service container?

### ISSUE THREAD

**Issue by pikeas** [phusion/baseimage-docker#204]
The docs cover adding additional daemons by dropping scripts in `/etc/service`. What if I only need to run a single service, like nginx? Given the bash example, it's reasonable to assume I could have the following:

    # Dockerfile
    ...
    CMD ["/sbin/my_init", "--", "nginx"]

Is this a good idea? It's more lightweight and obvious than creating nginx.sh and copying it over. It would be great if the docs made an explicit recommendation for the (very common) single daemon use case.

**Comment by FooBarWidget** [comment]
Almost. You can also pass --skip-runit to my_init.

**Comment by FooBarWidget** [comment]
And yes, it's a good idea to have this documented.

**Comment by pikeas** [comment]
You don't necessarily want `--skip-runit`, as you probably want syslog.
