### ISSUE TITLE
Clean up cron

### ISSUE THREAD

**Issue by pikeas** [phusion/baseimage-docker#205]
There are five daily jobs in /etc/cron.daily: `apt`, `dpkg`, `logrotate`, `passwd`, and `upstart`.

`upstart` can definitely go, since this image uses runit. Sub-question: should upstart itself also be removed?

`passwd` and `dpkg` are both backing up data to /var/backups. Since this directory isn't a docker volume, these backups are basically meaningless and should be removed.

I'm not really sure what the `apt` job does, but it definitely seems related to backups, and is likely also removable.

This leaves `logrotate`, which should stay because of syslog. Unless there's a way to have syslog log directly to stdout/stderr (`/dev/lstdout`?), which also has the benefit of eliminating the syslog forwarding service.

There is also one job in /etc/cron.weekly, `fstrim`. This is a hard drive cleanup utility. I'm leaning towards removal, but an argument could be made for keeping it.

**Comment by FooBarWidget** [comment]
Yes /etc/cron.daily/upstart can be removed. But many packages depend on Upstart itself, so it can't be removed although we already disable it.

Indeed, /etc/cron.daily/{passwd,dpkg} can be removed as well.

I'm not so sure about `apt`. It seems to do useful things depending on configuration, so I think it's best to leave it.

I will remove `fstrim`. I think it is up to the host to manage hardware-related stuff like that.
