### ISSUE TITLE
Document purpose of "--"

### ISSUE THREAD

**Issue by pikeas** [phusion/baseimage-docker#206]
I can run a container with:

    docker run --rm -it phusion/baseimage /sbin/my_init bash

Or:

    docker run --rm -it phusion/baseimage /sbin/my_init -- bash

The second form is given in the docs, but there's no documentation on why the "--" is needed.

**Comment by FooBarWidget** [comment]
`--` is standard Unix syntax for saying "don't parse any more parameters after this marker, and pass them as-is to the program". Pretty much all Unix tools support this.

For example, if you want to `cat` a file with filename `--help`, you have to write this:

    cat -- --help
