### ISSUE TITLE
sshd does not initialize host dsa keys

### ISSUE THREAD

**Issue by pbecotte** [phusion/baseimage-docker#210]
Trying to ssh into a new container following the directions in the README failed because the root dsa keys were not initialized.  I had to run `ssh-keygen -P "" -t dsa -f /etc/ssh/ssh_host_dsa_key` to get it to work.  I am not sure if this is intentional or not... but I wanted to bring it up in case it was not.

**Comment by FooBarWidget** [comment]
If you follow the instructions, it should generate an *RSA* host key, not DSA. Is the RSA host key not generated either? Or is it generated, but you want to specifically use DSA instead of RSA?

**Comment by pbecotte** [comment]
I am not a pro with sshd :)  I followed the instructions and got error messages (that I should have posted but for some reason didn't) about missing root dsa keys.  I searched stackoverflow and figured out that command to get things working.  I mounted a shell script in /etc/my_init.d to run that to make the sshd server work.  To help you out, I removed that line and reran everything just now and got the same issue as before.  In the startup logs, I noticed the following lines...

Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_dsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key

SSH with the key got 

```
ssh -i ~/.ssh/insecure -p 2222 -v root@localhost
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/vagrant/.ssh/config
debug1: /home/vagrant/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to localhost [127.0.0.1] port 2222.
debug1: Connection established.
debug1: identity file /home/vagrant/.ssh/insecure type -1
debug1: identity file /home/vagrant/.ssh/insecure-cert type -1
debug1: identity file /home/vagrant/.ssh/id_rsa type -1
debug1: identity file /home/vagrant/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2 pat OpenSSH_6.6.1* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
Connection closed by 127.0.0.1
```

/var/log/auth.log contains

```
Jul 15 13:50:40 f78d7437ccf3 sshd[118]: error: Could not load host key: /etc/ssh/ssh_host_rsa_key
Jul 15 13:50:40 f78d7437ccf3 sshd[118]: error: Could not load host key: /etc/ssh/ssh_host_dsa_key
Jul 15 13:50:40 f78d7437ccf3 sshd[118]: error: Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Jul 15 13:50:40 f78d7437ccf3 sshd[118]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key
Jul 15 13:50:40 f78d7437ccf3 sshd[118]: fatal: No supported key exchange algorithms [preauth]
```

**Comment by pbecotte** [comment]
Oh, my init script (without that line that I removed) is
```
#!/bin/bash

rm -f /etc/service/sshd/down
```

and I run the container with `-v <FOLDER HOLDING THAT FILE>:/etc/my_init.d`

**Comment by FooBarWidget** [comment]
According to [the latest SSH instructions](https://github.com/phusion/baseimage-docker#enabling_ssh), you also need to run `/etc/my_init.d/00_regen_ssh_host_keys.sh`.

**Comment by FooBarWidget** [comment]
Actually, wait, the comments say that it will autogenerate a key if you don't run that.

Can you show me all your 'docker run' output?

**Comment by pbecotte** [comment]
I found the problem  ... which you just posted :)

I was mounting the folder instead of the file, which overwrote the 00_regen_ssh_host_keys.sh
mounting just the file and using

```
#!/bin/bash

rm -f /etc/service/sshd/down
/etc/my_init.d/00_regen_ssh_host_keys.sh
```
got it working.  Is there a way to get my init script to run first so that I don't have to call the regen script again?  Either way, thanks and sorry for the confusion!

**Comment by FooBarWidget** [comment]
Init scripts are run in alphabetical order, so just give your file a proper name.
