### ISSUE TITLE
Using baseimage with an alternate uid

### ISSUE THREAD

**Issue by frioux** [phusion/baseimage-docker#211]
I'm not sure if this is a straight up docker issue or not, though I suspect not.  Basically I am trying to simplify one of my containers by removing the `sudo` inside the container and instead running the container with `docker run ... -u 1000`.  I get this error:

      *** Killing all processes...
      Traceback (most recent call last):
        File "/sbin/my_init", line 334, in <module>
          main(args)
        File "/sbin/my_init", line 252, in main
          import_envvars(False, False)
        File "/sbin/my_init", line 61, in import_envvars
          for envfile in listdir("/etc/container_environment"):
        File "/sbin/my_init", line 49, in listdir
          return sorted(os.listdir(path))
      PermissionError: [Errno 13] Permission denied: '/etc/container_environment'

So I figured I needed to fix the perms of that directory, so I added this to the RUN statements inside the Dockerfile:

      RUN chown 1000:1000 /etc/container_environment -R

I can then do a `docker run -itu 1000 mycontainer bash` and I see this:

      user@1d0d69fe032e:/$ ls -dlh /etc/container_environment
      drwx------ 2 user user 4.0K Apr  2 23:32 /etc/container_environment
      user@1d0d69fe032e:/$ ls -lh /etc/container_environment
      ls: cannot open directory /etc/container_environment: Permission denied

I don't see why I wouldn't be able to open that directory...  Also, if I start without the `-u 1000` everything looks fine:

      root@54d1f1699037:/# ls -lh /etc/container_environment
      total 12K
      -rw-r--r-- 1 user user  2 Jan 20 10:08 INITRD
      -rw-r--r-- 1 user user 11 Jan 20 10:09 LANG
      -rw-r--r-- 1 user user 11 Jan 20 10:09 LC_CTYPE

What should I do next?

**Comment by FooBarWidget** [comment]
I get the feeling that this is a kernel bug, probably related to AUFS. Your chmod should work. I've seen a similar issue before, but I couldn't figure out what was wrong.

But there is an alternative. Instead of running the container with `-u 1000`, you could wrap the process you want to run with a `setuser user` call. For example:

    docker run -t -i mycontainer \
      /sbin/my_init -- \
      /sbin/setuser user \
      bash

**Comment by frioux** [comment]
Yeah I already have that working, I just thought it would be super nice if
all the processes in the container were the same uid.

-- 
sent from a rotary phone, pardon my brevity

**Comment by eiosis** [comment]
I did not get this to work; I no longer get a permission error on /etc/container_environment, but when I use /sbin/setuser in my docker run,  I had assumed my directories inside my container would be owned by my new user, but still they are owned by root. 

Also, I tried using https://hub.docker.com/r/wingedkiwi/ubuntu-baseimage/ but same issues.
