### ISSUE TITLE
Ubuntu 15.04

### ISSUE THREAD

**Issue by mkjois** [phusion/baseimage-docker#212]
Hi,

A base image for docker with runit as an init process is a great idea. I was wondering if there were plans to upgrade the base layer to Ubuntu 15.04. The official Ubuntu [repository](https://registry.hub.docker.com/_/ubuntu/) on Docker Hub has the pre-release available.

Thanks!

**Comment by FooBarWidget** [comment]
There are no plans to upgrade to 15.04. We favor stability, so we only base on LTS releases of Ubuntu. If you wish to use 15.04, please fork this repository.
