### ISSUE TITLE
Syslog-ng is writing to /dev/tty10

### ISSUE THREAD

**Issue by dekobon** [phusion/baseimage-docker#222]
The default syslog-ng configuration is configured to write messages to /dev/tty10. This device may not exist on all Docker hosts. Moreover, it just seems like something dirty to do in a container.

Around /etc/syslog-ng/syslog-ng.conf:148
```
log { source(s_src); filter(f_crit); destination(d_console); };
```

Around /etc/syslog-ng/syslog-ng.conf:65

```
# The root's console.
#
destination d_console { usertty("root"); };
```
Can we delete these lines from the base image's configuration?

**Comment by FooBarWidget** [comment]
Agreed. This has been done in commit a9e956d9f9.
