### ISSUE TITLE
setuser soon deprecated

### ISSUE THREAD

**Issue by bierdok** [phusion/baseimage-docker#224]
The custom tool for running a command as another user will be soon deprecated.
Indeed, this will be present in the docker binary in few months. https://github.com/docker/docker/pull/12025

**Comment by FooBarWidget** [comment]
It won't be deprecated. docker/docker#12025 is to allow a user outside the container to run a command inside the container as a specific user. Setuser's primary purpose is to allow the container itself to run an internal command as a specific user.

**Comment by FooBarWidget** [comment]
I guess a good analogy is ssh vs sudo. With ssh you can login as a specific user. With sudo you can -- given local access -- run a command on the local host as a specific user.

**Comment by bierdok** [comment]
@FooBarWidget Thanks for the feedback!
This Docker extension can interest you https://github.com/softilabs/docker-host/
