### ISSUE TITLE
Question regarding the choice of CMD vs ENTRYPOINT

### ISSUE THREAD

**Issue by jakirkham** [phusion/baseimage-docker#225]
I noticed in your `Dockerfile` that you chose to use `CMD` instead of `ENTRYPOINT`. As it seems one would always want to always run `/sbin/my_init` first (and it is trivial for an end user to override if they wish via an `--entrypoint` flag), is there a reason why you chose not use an entrypoint?

**Comment by FooBarWidget** [comment]
No reason. I prefer CMD so that I can have control over what exactly I am executing. But you can use ENTRYPOINT to ensure that everything is always run under my_init.

**Comment by jakirkham** [comment]
Thanks for clarifying.
