### ISSUE TITLE
Restarting a container makes runit freak out

### ISSUE THREAD

**Issue by kstenerud** [phusion/baseimage-docker#227]
I've made a squid Dockerfile that works well, except when it gets stopped and restarted.

Dockerfile:

	FROM phusion/baseimage:0.9.16

	RUN apt-get update && \
	    apt-get install -y squid3 && \
	    mv /etc/squid3/squid.conf /etc/squid3/squid.conf.dist && \
	    rm -rf /var/lib/apt/lists/*

	COPY squid.conf /etc/squid3/squid.conf
	COPY squid_passwd /etc/squid3/squid_passwd

	RUN /usr/sbin/squid3 -N -f /etc/squid3/squid.conf -z

	RUN mkdir /etc/service/squid
	ADD squid.sh /etc/service/squid/run

	EXPOSE 3128

My run script (squid.sh):

	#!/bin/sh
	# `/sbin/setuser memcache` runs the given command as the user `memcache`.
	# If you omit that part, the command will be run as root.
	exec /usr/sbin/squid3 -NY -d 1 -f /etc/squid3/squid.conf >>/var/log/squid.log 2>&1

When I run it the first time, everything is great. If I stop and restart it, there's a high chance it will get confused.

On the first start, the following processes are running:

    # ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
      8 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
      9 ?        Ss     0:00 runsv squid
     10 ?        Ss     0:00 runsv cron
     11 ?        Ss     0:00 runsv syslog-forwarder
     12 ?        Ss     0:00 runsv sshd
     13 ?        Ss     0:00 runsv syslog-ng
     14 ?        S      0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
     15 ?        S      0:00 /usr/sbin/cron -f
     16 ?        S      0:00 tail -f -n 0 /var/log/syslog
     17 ?        S      0:00 /usr/sbin/squid3 -NY -d 1 -f /etc/squid3/squid.conf
     22 ?        Ss     0:00 (logfile-daemon) /var/log/squid3/access.log
     23 ?        Ss     0:00 (pinger)
     24 ?        Ss     0:00 bash
     38 ?        R+     0:00 ps ax

If I stop and restart the container, it may or may not restart squid. Sometimes it works:

    # ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
      8 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
      9 ?        Ss     0:00 runsv syslog-ng
     10 ?        Ss     0:00 runsv cron
     11 ?        Ss     0:00 runsv syslog-forwarder
     12 ?        Ss     0:00 runsv sshd
     13 ?        Ss     0:00 runsv squid
     14 ?        S      0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
     16 ?        S      0:00 /usr/sbin/cron -f
     18 ?        S      0:00 tail -f -n 0 /var/log/syslog
     21 ?        S      0:00 /usr/sbin/squid3 -NY -d 1 -f /etc/squid3/squid.conf
     22 ?        Ss     0:00 (logfile-daemon) /var/log/squid3/access.log
     23 ?        Ss     0:00 (pinger)
     24 ?        Ss     0:00 bash
     38 ?        R+     0:00 ps ax

Sometimes it doesn't:

    # ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
      7 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
      8 ?        Ss     0:00 runsv syslog-ng
      9 ?        Ss     0:00 runsv cron
     10 ?        Ss     0:00 runsv syslog-forwarder
     11 ?        Ss     0:00 runsv sshd
     12 ?        Ss     0:00 runsv squid
     14 ?        S      0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
     15 ?        S      0:00 /usr/sbin/cron -f
     16 ?        S      0:00 tail -f -n 0 /var/log/syslog
     29 ?        Ss     0:00 bash
     45 ?        R+     0:00 ps ax

When this happens, you'll see the following in /var/log/squid.log (redirect from the shell script):

    2015/06/09 23:29:06| Squid is already running!  Process ID 15
    2015/06/09 23:29:07| Squid is already running!  Process ID 15
    2015/06/09 23:29:08| Squid is already running!  Process ID 15

... Which of course makes no sense since PID 15 isn't even squid3, and never was.

Killing PID 15 manually fixes the problem (temporarily):

    # kill 15
    # ps ax
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
      7 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
      8 ?        Ss     0:00 runsv syslog-ng
      9 ?        Ss     0:00 runsv cron
     10 ?        Ss     0:00 runsv syslog-forwarder
     11 ?        Ss     0:00 runsv sshd
     12 ?        Ss     0:01 runsv squid
     14 ?        S      0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
     16 ?        S      0:00 tail -f -n 0 /var/log/syslog
     29 ?        Ss     0:00 bash
    346 ?        S      0:00 /usr/sbin/cron -f
    347 ?        S      0:00 /usr/sbin/squid3 -NY -d 1 -f /etc/squid3/squid.conf
    348 ?        Ss     0:00 (logfile-daemon) /var/log/squid3/access.log
    349 ?        Ss     0:00 (pinger)
    350 ?        R+     0:00 ps ax

**Comment by FooBarWidget** [comment]
That sounds like a stale pid file problem to me. Try removing the pid file before starting squid.

**Comment by kstenerud** [comment]
Yeah, it's a stale pid file:

    root@odin:/mnt/main/docker/applications/httpproxy# docker exec -it httpproxy bash
    root@9a9314e43d29:/# ps ax
      PID TTY      STAT   TIME COMMAND
        1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
       10 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
       11 ?        Ss     0:00 runsv squid
       12 ?        Ss     0:00 runsv cron
       13 ?        Ss     0:00 runsv syslog-forwarder
       14 ?        Ss     0:00 runsv sshd
       15 ?        Ss     0:00 runsv syslog-ng
       16 ?        S      0:00 tail -f -n 0 /var/log/syslog
       17 ?        S      0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
       18 ?        S      0:00 /usr/sbin/squid3 -NY -d 1 -f /etc/squid3/squid.conf
       19 ?        S      0:00 /usr/sbin/cron -f
       24 ?        Ss     0:00 (logfile-daemon) /var/log/squid3/access.log
       25 ?        Ss     0:00 (pinger)
       26 ?        Ss     0:00 bash
       40 ?        R+     0:00 ps ax
    root@9a9314e43d29:/var# cat /var/run/squid3.pid 
    18
    root@9a9314e43d29:/var# exit
    exit
    root@odin:/mnt/main/docker/applications/httpproxy# docker stop httpproxy
    httpproxy
    root@odin:/mnt/main/docker/applications/httpproxy# docker start httpproxy
    httpproxy
    root@odin:/mnt/main/docker/applications/httpproxy# docker exec -it httpproxy bash
    root@9a9314e43d29:/# cat /var/run/squid3.pid 
    20
    root@9a9314e43d29:/# ps ax
      PID TTY      STAT   TIME COMMAND
        1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
       11 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
       12 ?        Ss     0:00 runsv syslog-ng
       13 ?        Ss     0:00 runsv syslog-forwarder
       14 ?        Ss     0:00 runsv sshd
       15 ?        Ss     0:00 runsv squid
       16 ?        Ss     0:00 runsv cron
       17 ?        S      0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
       19 ?        S      0:00 tail -f -n 0 /var/log/syslog
       20 ?        S      0:00 /usr/sbin/squid3 -NY -d 1 -f /etc/squid3/squid.conf
       22 ?        S      0:00 /usr/sbin/cron -f
       24 ?        Ss     0:00 (logfile-daemon) /var/log/squid3/access.log
       25 ?        Ss     0:00 (pinger)
       26 ?        Ss     0:00 bash
       41 ?        R+     0:00 ps ax
    root@9a9314e43d29:/# exitroot@odin:/mnt/main/docker/applications/httpproxy# docker stop httpproxy
    httpproxy
    root@odin:/mnt/main/docker/applications/httpproxy# docker start httpproxy
    httpproxy
    root@odin:/mnt/main/docker/applications/httpproxy# docker exec -it httpproxy bash
    root@9a9314e43d29:/# ps ax
      PID TTY      STAT   TIME COMMAND
        1 ?        Ss     0:00 /usr/bin/python3 -u /sbin/my_init
        9 ?        S      0:00 /usr/bin/runsvdir -P /etc/service
       10 ?        Ss     0:00 runsv syslog-ng
       11 ?        Ss     0:00 runsv syslog-forwarder
       12 ?        Ss     0:00 runsv sshd
       13 ?        Ss     0:00 runsv squid
       14 ?        Ss     0:00 runsv cron
       15 ?        S      0:00 syslog-ng -F -p /var/run/syslog-ng.pid --no-caps
       17 ?        S      0:00 /usr/sbin/cron -f
       20 ?        S      0:00 tail -f -n 0 /var/log/syslog
       24 ?        Ss     0:00 bash
       38 ?        R+     0:00 ps ax
    root@9a9314e43d29:/# cat /var/run/squid3.pid 
    20

What's the best way to deal with this? Change my runit script to always remove the pid file?

    rm -rf /var/run/squid3.pid
    exec /usr/sbin/squid3 -NY -d 1 -f /etc/squid3/squid.conf >>/var/log/squid.log 2>&1

**Comment by FooBarWidget** [comment]
Yes, that is what I would do.
