### ISSUE TITLE
container_environment.sh cannot handle certain environment variable names

### ISSUE THREAD

**Issue by cazzerson** [phusion/baseimage-docker#230]
I've run into an issue with my passenger-ruby22 based Docker container that only seems to occur after restarting it using docker-compose. If I try to source /etc/container_environment.sh, I see errors like:

```
bash: export: 
`affinity:container==b35c5f32eeace1c3ae12efb5631ce5354eb7d289e3d716d8b3af2dcbacdf6ad3': 
not a valid identifier
```

It looks like this is related to recent docker-compose support for Swarm results in colon-delimited environment identifiers. Has anyone else encountered this yet?

**Comment by FooBarWidget** [comment]
That looks like a bug in the shell value escaper. How does /etc/container_environment.sh and /etc/container_environment.json look like?

**Comment by cazzerson** [comment]
Here's an example from container_environment.sh:

```sh
export MYDB_ENV_affinity:container==42234af922200216f1449e66b7eb0de7b9aa73c4f4c9c81dd065565189cbe67c
```

and container_environment.json

```json
"MYDB_ENV_affinity:container": "=42234af922200216f1449e66b7eb0de7b9aa73c4f4c9c81dd065565189cbe67c"
```

**Comment by FooBarWidget** [comment]
Bash cannot handle environment variable names that contain ':', so I've modified `my_init` to sanitize names like that with underscores. `MYDB_ENV_affinity:container` is now transformed to `MYDB_ENV_affinity_container`.
