### ISSUE TITLE
Dockerfile incompatible with Ubuntu 12.04 i386

### ISSUE THREAD

**Issue by yukron** [phusion/baseimage-docker#232]
Unable to to build Ubuntu 12.04 32-bit using Dockerfile, got a bunch of errors. Here is a fix, I guess:

1. adding multiverse/universe to  /etc/apt/source.list failed, so runit and other packages could not be installed. There is a single line:
`deb http://archive.ubuntu.com/ubuntu precise main`

Just added the complete line:
```bash
echo 'deb http://archive.ubuntu.com/ubuntu precise main multiverse universe' > /etc/apt/sources.list
```

2. in system_services.sh `syslog-ng-core` install failed, though all workarounds are there. Had to force install to be true and moved workarounds after it:
```diff
 ## Install a syslog daemon.
-$minimal_apt_get_install syslog-ng-core
+$minimal_apt_get_install syslog-ng-core || true
+sed -i 's/^#\(SYSLOGNG_OPTS="--no-caps"\)/\1/g' /etc/default/syslog-ng
+sed -i -E 's/^(\s*)system\(\);/\1unix-stream("\/dev\/log");/' /etc/syslog-ng/syslog-ng.conf
+apt-get install -f || true
+service syslog-ng restart
 mkdir /etc/service/syslog-ng
````

**Comment by FooBarWidget** [comment]
I don't understand your issue. You mentioned Ubuntu 12.04, but baseimage-docker is based on Ubuntu 14.04. Or are you saying you are trying to build baseimage-docker *on* Ubuntu 12.04?

Can you paste the exact error message you see?
