### ISSUE TITLE
Set primary group ID for user?

### ISSUE THREAD

**Issue by nfarrar** [phusion/baseimage-docker#237]
I'm running some services in docker containers. These services write files in directories with locked down permissions. Using `setuser`, I can specify the user, but I also need written files to belong to be created belonging to a specified group (for multi-service/multi-user sharing purposes). Is there a recommended way with baseimage-docker?

**Comment by FooBarWidget** [comment]
I think you are looking for the setgid filesystem bit. If you turn that on for a directory, all files created inside it are by default owned by the directory's group. https://en.wikipedia.org/wiki/Setuid#setuid_and_setgid_on_directories
