### ISSUE TITLE
set different timezone using environment variable

### ISSUE THREAD

**Issue by thewilli** [phusion/baseimage-docker#239]
I'm using the container for various services, and it's kind of annoying that I have to set the timezone in each of the docker files by hand, so log output and cronjobs work as expected.

It would be a great improvement if we could configure the timezone using an environment variable, that could be set and updated with docker.

**Comment by mrosic** [comment]
There is no reason to implement something like that because Linux already supports several easy ways of doing that. Put this in your dockerfile:
RUN ln -sf /usr/share/zoneinfo/Europe/Vienna /etc/localtime

Or:
ENV TZ=CEST
(CEST as in Central European Summer Time)
