### ISSUE TITLE
Where does ssh log to in your setup

### ISSUE THREAD

**Issue by sean-abbott** [phusion/baseimage-docker#240]
I can't figure out where/how ssh logs.  I used your server as a base for a jenkins slave.  I created a new user (jenkins-slave), I copied public keys into the the users $HOME/.ssh/authorized_keys, but I can't ssh to the continor as that user and I can't find any logging to give me a hint of why it's not working.

**Comment by hd-deman** [comment]
Did you run this `rm -f /etc/service/sshd/down`?

**Comment by wingedkiwi** [comment]
ssh logs to /var/log/auth.log.
To show it in the console, add a runit file like the https://github.com/phusion/baseimage-docker/blob/master/image/services/syslog-ng/syslog-forwarder.runit or modify the syslog-ng.conf to log auth to syslog.

**Comment by sean-abbott** [comment]
Sadly, I'm not working on this project anymore and I don't remember the details, so apologies for the noise.  Hopefully the answer will help someone else, though!
