### ISSUE TITLE
couchbase does not launch properly with my_init

### ISSUE THREAD

**Issue by FuriousD** [phusion/baseimage-docker#243]
I am building my own version of a couchbase server with baseimage-docker as a base.  I built a similar thing with centos and supervisord which worked but I decided to switch to ubuntu/baseimage.

So when i don't have my_init start anything but rather enter the container manually using bash and I launch my startup script couchbase will start properly.  However, if I place the script in the /etc/service/couchbase/run file then it won't start properly.

It looks like my_init is starting the initial couchbase process but then that process is supposed to start many more processes.  This never seems to happen.

You can reproduce the issue by pulling my image or looking at my dockerfile(s)
docker pull furiousd/mycouchbase
https://github.com/FuriousD/mycouchbase

**Comment by FooBarWidget** [comment]
I'm not familiar with CouchBase, but I do see that you're calling 'exec' in your shell scripts. exec *replaces the current bash process* with the command that you're executing. This means that any traps you installed, or any code that comes after the exec, will never be executed. I'm guessing that's causing whatever problems you have.

**Comment by FuriousD** [comment]
I understand that the main script needs to hold the focus in order for systems like supervisord (and I'm assuming my_init) to keep track of whether or not to restart the process.  To me, the issue doesn't seem to be that it's loosing focus but that it's not allowing all of the child processes to launch, only some.

Concerning the use of exec, I'm doing it almost exactly the way that is suggested on the baseimage-docker instructions under 'adding additional daemons'

I'm saying there seems to be an issue with my_init launching a process that then goes ahead and launches sub processes where similarly supervisord was working for the same process.

**Comment by FuriousD** [comment]
I created a regular .sh script as a wrapper to my start_couchbase.sh script.  It also exhibited the same problem.  So it was a couchbase problem, not as much as my_init problem.

I added " -- -noinput" after /opt/couchbase/bin/couchbase-server to fix the issue.
