### ISSUE TITLE
0.9.17 image is private

### ISSUE THREAD

**Issue by ivant** [phusion/baseimage-docker#244]
Looks like there is some misconfiguration in the way the 0.9.17 image is published.

If I use the following `Dockerfile`:

    FROM phusion/baseimage:0.9.17
    
    EXPOSE 8888
    RUN mkdir /etc/service/test && \
        echo "#!/bin/sh\ndate | nc -l 8888" > /etc/service/test/run && \
        chmod a+x /etc/service/test/run
    
    CMD /sbin/my_init

then I get the following error after I (successfully) build an image from it:
 
    % docker push ivant/test-phusion
    The push refers to a repository [ivant/test-phusion] (len: 1)
    Sending image list
    FATA[0000] Error: Status 400 trying to push repository ivant/test-phusion: "Access denied: f21b69028ac081f5a624192ccb40bfefa60d267b2f41ec2677af6f6b93a2040c is a private image"

This hash is the hash of image 0.9.17 (or a part of it):

    % docker inspect -f '{{.Author}}' f21b69028ac081f5a624192ccb40bfefa60d267b2f41ec2677af6f6b93a2040c
    Phusion <info@phusion.nl>

If I replace the version in my `Dockerfile` to 0.9.16, the `docker push` command for my container succeeds:

    % docker push ivant/test-phusion
    The push refers to a repository [ivant/test-phusion] (len: 1)
    Sending image list
    Pushing repository ivant/test-phusion (1 tags)
    511136ea3c5a: Image already pushed, skipping 
    53f858aaaf03: Image already pushed, skipping 
    837339b91538: Image already pushed, skipping 
    615c102e2290: Image already pushed, skipping 
    b39b81afc8ca: Image already pushed, skipping 
    8254ff58b098: Image already pushed, skipping 
    ec5f59360a64: Image already pushed, skipping 
    2ce4ac388730: Image already pushed, skipping 
    2eccda511755: Image already pushed, skipping 
    5a14c1498ff4: Image already pushed, skipping 
    c946dd34c016: Image successfully pushed 
    03d453e17f53: Image successfully pushed 
    b9fb7fa3c479: Image successfully pushed 
    Pushing tag for rev [b9fb7fa3c479] on {https://cdn-registry-1.docker.io/v1/repositories/ivant/test-phusion/tags/latest}

**Comment by FooBarWidget** [comment]
I've double checked our repository account. It's marked public. I also haven't heard of anyone else with this problem. Do you have any idea why this may be happening? Could it be a temporary bug in the Docker hub?

**Comment by ivant** [comment]
I tried investigating, but failed to uncover anything more useful than what I reported above. Can you reproduce the problem (using some other account)?

**Comment by ivant** [comment]
% docker history f21b69028ac0
    IMAGE               CREATED             CREATED BY                                      SIZE
    f21b69028ac0        5 weeks ago         /bin/sh -c #(nop) MAINTAINER Phusion <info@ph   0 B
    d2a0ecffe6fa        6 weeks ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
    29460ac93442        6 weeks ago         /bin/sh -c sed -i 's/^#\s*\(deb.*universe\)$/   1.895 kB
    b670fb0c7ecd        6 weeks ago         /bin/sh -c echo '#!/bin/sh' > /usr/sbin/polic   194.5 kB
    83e4dde6b9cf        6 weeks ago         /bin/sh -c #(nop) ADD file:c8f078961a543cdefa   188.1 MB

If I'm reading this right, `d2a0ecffe6fa` must be the last image produced by the base image, which is `ubuntu:14.04`, `f21b69028ac0` is an image with 0B changes produced by setting the maintainer. Unfortunately that doesn't explain much.

**Comment by dnesteryuk** [comment]
I run into the same issue. When I use `0.9.15` everything works fine.

**Comment by brianwhigham** [comment]
heh, thanks for the 0.9.15 tip, @dnesteryuk .  I had the same problem with f21b69028ac081f5a624192ccb40bfefa60d267b2f41ec2677af6f6b93a2040c and docker 1.5.0.  I could build with docker 1.7.1.  But, using phusion 0.9.15 worked with docker 1.5.0.

Why not just use a newer docker you ask? Well, 1) I'm using what Ubuntu gives me and 2) Deis 1.10.0 apparently still can't "deis pull" images built with images built with >= docker 1.6. :-1:

**Comment by isaac** [comment]
@FooBarWidget Same error for me using Docker 1.8.3 on Mac OS X 10.10.5

**Comment by slayer** [comment]
@FooBarWidget same problem

**Comment by FooBarWidget** [comment]
I have released 0.9.18 and pushed it using Docker 1.9. Maybe that solves the problem.
