### ISSUE TITLE
Can't restart services

### ISSUE THREAD

**Issue by tapir** [phusion/baseimage-docker#246]
I have nginx and php5-fpm services running. Inside my init script I call
```
sv restart php5-fpm
sv restart nginx
```
but I get this error
```
warning: php5-fpm: unable to open supervise/ok: file does not exist
warning: nginx: unable to open supervise/ok: file does not exist
```

Here are my service files
```
#!/bin/sh
#/etc/service/nginx/run
exec /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"
```
```
#!/bin/sh
#/etc/service/php5-fpm/run
exec /usr/sbin/php5-fpm -c /etc/php5/fpm/ --nodaemonize
```

**Comment by JohnOhl** [comment]
Can you check the file permissions on each file? I had a similar problem in the past, both `/etc/service/php5-fpm/run` and `/etc/service/nginx/run` should be executable. If not, try the following and see if it helps:

```
chmod a+x /etc/service/nginx/run
chmod a+x /etc/service/php5-fpm/run
```

**Comment by FooBarWidget** [comment]
Since the original poster didn't post further feedback, I'm closing this issue for now.
