### ISSUE TITLE
grep from / crashes container and Docker service

### ISSUE THREAD

**Issue by mstormo** [phusion/baseimage-docker#247]
So, this seems to happen only for this baseimage. If I simply do
    cd / && grep -niIr "foobar" .
both the current container and the docker service as a whole crashes. In fact, it crashes on a kernel level, so I cannot reboot my machine without using the reset/power button.

When I do the same on any other image, I can simply Ctrl+C out of the command without any issue.

If I contain it to /etc for example, the crash doesn't happen.

I'm on Mint Linux 17.1.

**Comment by FooBarWidget** [comment]
That is definitely a Linux kernel bug. Please report it to the Linux kernel team.

**Comment by mstormo** [comment]
While I would agree with you that Docker (and by redirection the Linux kernel) shouldn't allow this to happen, it only happens with your baseimage. None of the other baseimages exhibits this behavior. I therefore think it would be most correct if you guys engaged in the issue, given that you guys "own" the baseimage and the Docker "recipe".

Who knows, maybe it's your baseimage's special Init causing the issue? I don't have the slightes idea, which means you're probably in a better position to raise the issue, or figure it out and work around the issue in your own image.

That's my 2c. I won't bring it further..

**Comment by FooBarWidget** [comment]
We can't reproduce the issue though, so we're not in a position to raise a bug report. Our init system doesn't do anything special from a POSIX API point of view and a kernel point of view; everything we do is very standard.

**Comment by FooBarWidget** [comment]
Furthermore, you trigger the crash through a grep. This suggests that the bug probably lies in the filesystem, which probably means AUFS.

**Comment by mstormo** [comment]
Ok, thanks for checking, might be a Mint Linux/Docker issue then.
