### ISSUE TITLE
Buffering output

### ISSUE THREAD

**Issue by moltar** [phusion/baseimage-docker#249]
It seems like the output is being buffered and never flushed until the script terminates:

How to replicate:

```
docker run --rm phusion/baseimage:latest perl -e "for (1..10) { print qq{test\n}; }; sleep 5"
```

**Comment by FooBarWidget** [comment]
This is not a baseimage-docker problem. If you run `docker run` without `-t` then Perl has no terminal. The default behavior of most applications when they don't have a terminal, is to switch stdout to byte buffered mode (NOT line buffered mode), so the fact that you don't see anything until the process exits is normal and has got nothing to do with either Docker or baseimage-docker.
