### ISSUE TITLE
E: Invalid operation –y The command '/bin/sh -c sudo apt-get –y update && sudo apt-get install –y fortunes' returned a non-zero code: 100

### ISSUE THREAD

**Issue by mmoralesmc** [phusion/baseimage-docker#251]
Hi Im María and I'm new in Docker...
I'm following the next tutorial https://docs.docker.com/mac/step_four/ but when I run: ocker build -t docker-whale . I have the next mistake:
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM docker/whalesay:latest
 ---> fb434121fc77
Step 1 : RUN sudo apt-get –y update && sudo apt-get install –y fortunes
 ---> Running in 199a5ca8dab3
E: Invalid operation –y
The command '/bin/sh -c sudo apt-get –y update && sudo apt-get install –y fortunes' returned a non-zero code: 100

My Dockerfile is:
FROM docker/whalesay:latest

RUN apt-get –y update && apt-get install –y fortunes

CMD /usr/games/fortune –a | cowsay

Can you help me, please?? I'm using Mac OS Yosemite versión 10.10.5

Thanks son much

**Comment by FooBarWidget** [comment]
The dash character in your code is incorrect. It's supposed to be `-y`, not `–y`. Notices the difference in the dashes: they look similar but are different Unicode characters.

I think you copy-pasted that command from some random blog that converts `-` to `–`.

In any case, this is not a baseimage-docker problem.

**Comment by mmoralesmc** [comment]
Hi, thanks, I written the Docfile again, but I have this mistake:

MacBook-Pro-de-Maria-2:mydockerbuild mariamoralesmunoz$ docker build -t docker-whale .
Sending build context to Docker daemon 2.048 kB
Step 0 : FROM docker/whalesay:latest
 ---> fb434121fc77
Step 1 : RUN apt-get -y update && apt-get instala -y fortunes
 ---> Running in a59d4056a625
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [64.4 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Get:3 http://archive.ubuntu.com trusty-updates/main Sources [299 kB]
Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [4513 B]
Get:5 http://archive.ubuntu.com trusty-updates/universe Sources [176 kB]
Get:6 http://archive.ubuntu.com trusty-updates/main amd64 Packages [790 kB]
Get:7 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [22.7 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [420 kB]
Hit http://archive.ubuntu.com trusty Release
Get:9 http://archive.ubuntu.com trusty-security/main Sources [122 kB]
Get:10 http://archive.ubuntu.com trusty-security/restricted Sources [3230 B]
Get:11 http://archive.ubuntu.com trusty-security/universe Sources [35.4 kB]
Get:12 http://archive.ubuntu.com trusty-security/main amd64 Packages [440 kB]
Get:13 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [19.4 kB]
Get:14 http://archive.ubuntu.com trusty-security/universe amd64 Packages [151 kB]
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Fetched 2612 kB in 14s (179 kB/s)
Reading package lists...
E: Command line option 'y' [from -y] is not known.
The command '/bin/sh -c apt-get -y update && apt-get instala -y fortunes' returned a non-zero code: 100

The similar error...

**Comment by mmoralesmc** [comment]
solved, thanks so much
