### ISSUE TITLE
upstart jobs doesn't work

### ISSUE THREAD

**Issue by agonen** [phusion/baseimage-docker#255]
Hi , I'm new to docker  but I can't make upstart jobs run .

I'm try to test elasticsearch installation . The elastic is run a deaom using upstart. on regualer ubunto it works well. But in docker it's seems that start/stop command doesn't work (alway return true)

My docker file is at http://pastebin.com/3ysJWkVW

The postinst script is at : http://pastebin.com/FZt3e5t7

any idea what I've got wrong ?

**Comment by FooBarWidget** [comment]
Upstart isn't really meant to be used inside Docker. This is why baseimage-docker introduced its own init system. We can't do anything about this, sorry, so you should find another solution that doesn't involve Upstart.
