### ISSUE TITLE
add eatmydata package

### ISSUE THREAD

**Issue by paulopastoriza** [phusion/baseimage-docker#256]
Hello, I would like the base image was added the eatmydata package to increase performance in installing packages via apt.

https://packages.debian.org/sid/eatmydata
Installed Size - 27.0 kB

http://people.skolelinux.org/pere/blog/Speeding_up_the_Debian_installer_using_eatmydata_and_dpkg_divert.html

Sample
RUN eatmydata -- apt-get install -yq software-properties-common && add-apt-repository ppa:webupd8team/java -y

**Comment by FooBarWidget** [comment]
Not needed. We already disable fsync in apt: https://github.com/phusion/baseimage-docker/blob/master/image/prepare.sh#L6-L9

**Comment by hashar** [comment]
That was done via:
```
## Temporarily disable dpkg fsync to make building faster.
if [[ ! -e /etc/dpkg/dpkg.cfg.d/docker-apt-speedup ]]; then
	echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/docker-apt-speedup
fi
```

But eventually got removed 8f2877c806186511611017395d6f87cd00392adf since "the latest Ubuntu image does that".
