### ISSUE TITLE
Could setuser tool run a service like a login user?

### ISSUE THREAD

**Issue by xfyuan** [phusion/baseimage-docker#257]
I extend the base image to build a CI machine, and use setuser tool to run CI service with a seperated user, for example 'testci'. My application is a Rails app. The CI server needs a ruby env to run each test. I have installed rvm for user 'testci',  and use these commands to check, the ruby env is OK:

(I use docker compose, docker name is 'ci')
```
docker-compose run ci bash
su - testci
ruby -v
```
output is 'ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]', ruby does works.

But the problem is when the CI run each test, it always can't found ruby. Because the rvm config is be written in .bash_profile, a logined user can read it correctly so all ok, I guess setuser tool maybe didn't read .bash_profile then ruby not works.

Did I missed or ignored something? and I want to know the setuser tool can run a service like a real logined user?

**Comment by bestes** [comment]
Why use rvm inside a docker container at all? Just pick (and install) the
version of ruby you want. If you want another version, make another
container.

**Comment by FooBarWidget** [comment]
The setuser tool isn't supposed to read .bash_profile. That is done by bash. Try running your commands through bash like this:

    setuser username bash -lc 'ruby -v'
