### ISSUE TITLE
Cannot install sqlite php driver on this image

### ISSUE THREAD

**Issue by BeOleg** [phusion/baseimage-docker#259]
Trying to install `php5-sqlite` driver on this image results in an error.
Is there anyway to solve it?

**Comment by kingdonb** [comment]
How are you trying?  What is the error?  Specific details, or not much help can be given.

**Comment by BeOleg** [comment]
Tried everything from `apt-get install php5-sqlite` to downloading the package and compiling it myself.
The error is: `Package not found`

**Comment by kingdonb** [comment]
You may have forgotten `apt-get update` -- that's what it sounds like to me.

The container is shipped with apt source data stripped, because it is bloat unless you are trying to install a package.  So, installing any package generally will show `Package not found` unless `apt-get update` first.

**Comment by BeOleg** [comment]
I was running `apt-get update` as well.
will add the full amount output.

**Comment by BeOleg** [comment]
Full `Dockerfile`


```Docker
FROM phusion/baseimage:0.9.15

RUN locale-gen en_US.UTF-8
ENV LANG       en_US.UTF-8
ENV LC_ALL     en_US.UTF-8

ENV HOME /root

RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

CMD ["/sbin/my_init"]

# installing packages
RUN add-apt-repository -y ppa:ondrej/php5 \
    && add-apt-repository -y ppa:nginx/stable \
    && add-apt-repository -y ppa:ondrej/mysql-5.6 \
    && apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y --force-yes \
        nginx \
        vim \
        curl \
        wget \
        php5-cli \
        php5-fpm \
        php5-mysql \
        php5-sqlite \
        unzip \
        php5-curl \
    && mkdir -p /tmp_download \
    && mkdir -p /data/config \
    && mkdir -p /etc/my_init.d \
    && curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "/tmp_download/awscli-bundle.zip" \
    && unzip -o -d /tmp_download/ /tmp_download/awscli-bundle.zip \
    && /tmp_download/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

```

**Comment by kingdonb** [comment]
The exact Dockerfile you pasted, works for me without error, on Docker 1.6.2 the latest version from Ubuntu Wily repository.

```
$ sudo docker build .
  ... ... ...
Successfully built fdbdd0f90bbc

$ sudo docker run -it fdbdd /bin/bash
root@7b36823d21e8:/# dpkg -l|grep php5-sqlite
ii  php5-sqlite                       5.5.30+dfsg-1+deb.sury.org~trusty+1 amd64        SQLite module for php5
```

I'm sorry I can't be more helpful?  This shouldn't have anything to do with the Docker 1.5 deprecation starting November 19, but just to be sure, you're not running docker <= 1.5 are you?

**Comment by BeOleg** [comment]
`- docker run integration/menuimporter /bin/sh -c "apt-get update && apt-get install php5-sqlite"`
in `travis.yml` and also on dev give an error:

on dev:
```
invoke-rc.d: policy-rc.d denied execution of restart.
invoke-rc.d: policy-rc.d denied execution of start.
```

On travis:
`command apt-get update && apt-get install php5-sqlite exited with status code 100`

**Comment by BeOleg** [comment]
What we are trying to do is to add this module, as part of a travis build, that used docker.

**Comment by FooBarWidget** [comment]
This isn't a Baseimage-docker problem, so I'm afraid I can't help you with this.
