### ISSUE TITLE
List of images extending baseimage-docker

### ISSUE THREAD

**Issue by Nyholm** [phusion/baseimage-docker#261]
Im new to Docker, I just found this base image which I believe is great. I don't want to reinvent the wheel and create my own php/mysql/nginx images extending this image but I have a hard time finding existing ones. Sure, you can search for [nginx on docker hub](https://hub.docker.com/search/?q=nginx&page=1&isAutomated=0&isOfficial=0&starCount=0&pullCount=0) and click through all 5500+ images. 

Suggestion: Could we include a link to common images with good maintainers in the documentation? Ie images for php, mysql, nginx, apache, redis etc etc?

**Comment by FooBarWidget** [comment]
We haven't kept track of people who use baseimage-docker, so I don't have such a list.

**Comment by cisso** [comment]
@Nyholm Not even the public docker registry keeps track of extending images. For an approximation or starting point you could use the [Github code search](https://github.com/search?l=dockerfile&q=FROM+phusion+baseimage&type=Code&utf8=%E2%9C%93).

**Comment by franz-josef-kaiser** [comment]
@cisso Much better than searching 5.5k images! ;)

> We’ve found 4,242 code results

**Comment by Theaxiom** [comment]
I have created a [page in our Wiki](https://github.com/phusion/baseimage-docker/wiki/Baseimage-Based-Projects) which is dedicated to a list of projects which extend `baseimage-docker`. You are more than welcome to submit a PR which contains your project!
