### ISSUE TITLE
Should setuser be more "forgiving"?

### ISSUE THREAD

**Issue by eiden** [phusion/baseimage-docker#266]
Ran into an issue where one script was calling `exec /sbin/setuser user otherscript.sh`. 
`otherscript.sh` also did a `exec /sbin/setuser user command` which resulted in the error `Operation not permitted`

Steps to reproduce:

```
useradd someuser
/sbin/setuser someuser /sbin/setuser someuser echo "foo"
Traceback (most recent call last):
  File "/sbin/setuser", line 17, in <module>
    os.initgroups(username, user.pw_gid)
PermissionError: [Errno 1] Operation not permitted
```

Would it be a good idea to check if the current user is the same as the first arg to `setuser` before calling `os.initgroups`?

**Comment by FooBarWidget** [comment]
Yes that seems like a good idea.

**Comment by hyperknot** [comment]
Since this is used in planned scenarios only, does it realistically happen? In 3 years this didn't happen, so I'm closing it, re-open if you deem it important.
