### ISSUE TITLE
syslog-ng memory leak

### ISSUE THREAD

**Issue by davibe** [phusion/baseimage-docker#267]
Please look at this

https://bugs.launchpad.net/ubuntu/+source/syslog-ng/+bug/1394101

This is happening to me in production. Syslog-ng 3.5.3-1 (the one base image is using) leaks memory over time.

As a temporary solution i restart it every day using a runit service like `sleep 86400; kill -9 $(cat /var/run/syslog-ng.pid)`

**Comment by FooBarWidget** [comment]
Unfortunately this is not something we can do anything about. Ubuntu hasn't updated their syslog-ng package.
