### ISSUE TITLE
Significant size increase between 0.9.17 and 0.9.18

### ISSUE THREAD

**Issue by hubertbanas** [phusion/baseimage-docker#268]
I noticed that there is a significant size increase (67.5 MB) between 0.9.17 and 0.9.18. 

```bash
phusion/baseimage   0.9.17              e9f50c1887ea        5 months ago        237.7 MB
phusion/baseimage   0.9.18              fdcdf46f55d4        8 days ago          305.2 MB
```

Was something else added to the 0.9.18 that is taking that much extra space?

**Comment by FooBarWidget** [comment]
Nothing was added. The only thing I did was installing the latest Ubuntu updates.

**Comment by hubertbanas** [comment]
That is fair. I just wasn't sure where is this 28% increase coming from.

**Comment by davidkarlsen** [comment]
Checkout https://labs.ctl.io/imagelayers-io-docker-visualization-and-badges/ and https://imagelayers.io/?images=phusion%2Fbaseimage:latest to browse the layers, associated command and size.
