### ISSUE TITLE
Use `ARG` for optional services during `docker build`

### ISSUE THREAD

**Issue by endersonmaia** [phusion/baseimage-docker#269]
Since docker 1.9, it's possible to use ARG Dockerfile instrunction to define build time variables.

This could be used as the solution implemented in PR-#182 

I can work on a PR it's the maintainer interest.

**Comment by FooBarWidget** [comment]
Sorry for the late response, I haven't had time until now to look after Baseimage-docker. Yes your proposed change would be welcome.

**Comment by hyperknot** [comment]
The PR has been merged years ago.

BTW, we should go back to simply using 0 and 1 as it doesn't actually work.
