### ISSUE TITLE
Nginx fails to log to syslog

### ISSUE THREAD

**Issue by kop** [phusion/baseimage-docker#277]
I'm trying to configure Nginx 1.8.0 logging like this:

```
access_log syslog:server=unix:/dev/log;
error_log syslog:server=unix:/dev/log;
```

But logging fails with the following error:

```
2016/01/12 20:19:59 [alert] 36#0: connect() failed (91: Protocol wrong type for socket)
```

Any ideas what is wrong? Thank you.

**Comment by guedressel** [comment]
I remember that syslog support is part of the commercial subscription of ngnix. But [documentation](http://nginx.org/en/docs/syslog.html) says - if I read it right - that it is also part of the open source variant since version 1.7.1.
@kop, did you ever made it log to syslog without docker and base-image?

**Comment by kop** [comment]
@guedressel,

I never used syslog output on Nginx before, but according to docs, it should work. Plus Nginx error log says it tries to connect to the socket. I just thought that its a small chance that its Nginx issue.

However now I see that some other services I'm running are working just fine with syslog, so I guess it's Nginx issue. I will close this issue and will address it to Nginx devs. Thank you.

**Comment by theypsilon** [comment]
@kop I still have the same problem, did you find any solution?

**Comment by kop** [comment]
@theypsilon, No, I've just configured it this way:

```
access_log /dev/stdout;
error_log /dev/stderr;
```

And it works. And Docker logs can be passed to the syslog with no problems.

**Comment by jonathanpmartins** [comment]
same problem here! :(

**Comment by lucafavatella** [comment]
Reason is https://github.com/phusion/baseimage-docker/blob/rel-0.9.19/image/services/syslog-ng/syslog-ng.conf#L21
Compare with https://www.balabit.com/documents/syslog-ng-ose-3.9-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#configuring-source-system

**Comment by lucafavatella** [comment]
It appears affecting tag 0.9.20 too https://github.com/phusion/baseimage-docker/commit/b56693beb345781092f294c209cba49ace355dd7

**Comment by lucafavatella** [comment]
It is weird finding it here too https://github.com/dockerbase/syslog-ng/blob/98a447ba98ad56dd4cf08701c3cf778ec31935ca/Dockerfile#L16

**Comment by lucafavatella** [comment]
syslog-ng appears avoiding the problem using only network https://github.com/balabit/syslog-ng-docker/blob/6a440e3f84d17126de52a88b16cf4da55c458344/syslog-ng/syslog-ng.conf#L3-L13 - I guess it is because their image is supposed to be used on network alone.
