### ISSUE TITLE
Add Changelog with GitHub Releases

### ISSUE THREAD

**Issue by franz-josef-kaiser** [phusion/baseimage-docker#279]
Currently the [`Changelog.md`](https://github.com/phusion/baseimage-docker/blob/8ec76f25caf42738170d03f6a7a9feaa708c6527/Changelog.md) file hosts what is basically a list of releases. GitHub already [has this feature built in](https://github.com/phusion/baseimage-docker/releases). Please be so kind and follow other organisations repos and GitHub standards and add some releases there as well. From experience: It's very fast and easy, even with a huge number of releases. It also provides a default route that people can go without searching through all provided files in this repository. Thanks in advance!

**Bonus:** It looks quite professional :)

_(Question: Why the `rel-` prefix for version numbers? The rest looks like if it is according to the semver specs, but the prefix is strange.)_

**Comment by Theaxiom** [comment]
@franz-josef-kaiser Would you mind submitting a PR with your requested changes and we will get them implemented? Thanks!

**Comment by franz-josef-kaiser** [comment]
@Theaxiom I can not add releases for you, unless I am the owner or some contributor of the repo. This is not possible via a PR. Please, read the above again. Thanks.

**Comment by Theaxiom** [comment]
@franz-josef-kaiser I apologize, I thought you were talking about the Changelog.md content. Could you please link to an example of what you are explaining? Thanks!

**Comment by franz-josef-kaiser** [comment]
@Theaxiom sure. A nice, basic example of _releases_ can be seen in the [WPStarter](https://github.com/wecodemore/wpstarter/releases) repo.

**Comment by Theaxiom** [comment]
Thank you @franz-josef-kaiser -- I see what you are saying now and I agree. I will work to ensure that moving forward we will use that method for release notes. Thanks!
