### ISSUE TITLE
@reboot cron jobs not being run

### ISSUE THREAD

**Issue by teu** [phusion/baseimage-docker#280]
Hi,

great work on baseimage first of all.

Small issue - the cron jobs with "@reboot" in front aren't being run after the container restarts (so technically on reboot).

**Comment by skyscooby** [comment]
Docker containers are non-persistent by design, they are not virtual machines and have no ACPI subsystem to handle a traditional reboot. They are always 'first booting' so to speak so just through whatever you want run on boot somewhere in your startup sequence.. no need for cron.

**Comment by koh-osug** [comment]
Where is this mentioned start up sequence? I also have a script which should be just executed right after the start of the container to prepare some settings for the running service inside docker. This script __must__ be inside the container. I have no influence on the start up from the host.

**Comment by koh-osug** [comment]
OK, found it:

> The baseimage-docker init system, /sbin/my_init, runs the following scripts during startup, in the following order:
>All executable scripts in /etc/my_init.d, if this directory exists. The scripts are run in lexicographic order.
The script /etc/rc.local, if this file exists.
