### ISSUE TITLE
any way to run a post my_init script?

### ISSUE THREAD

**Issue by steveinatorx** [phusion/baseimage-docker#281]
Need to run an ant build after my tomcat instance spins up via my_init - my idea was to add the ant build as an exec to the regular /services/foo/run script as bash scripts run commands sequentially. Any cleaner way i could do that via existing baseimage functionality?

**Comment by chrisliu529** [comment]
I believe a simple shell script checking your tomcat status then invoking ant tool can do the trick.
Add the line below in your dockerfile:
`ADD build.sh /etc/my_init.d/build.sh`

In build.sh:
```
while true; do
  if ps aux | grep <tomcat pattern>; then
    cd <code_path> && ant && exit
  fi
  sleep 3
done
```
