### ISSUE TITLE
why vagrant? could we use docker itself instead of vagrant?

### ISSUE THREAD

**Issue by cypa** [phusion/baseimage-docker#290]
I'm not vagrant user and I need apply these cool features to existing docker-image without Dockerfile available.

**Comment by jjborie** [comment]
Hi @cypa ,

Create a docker image from this one on docker hub:
https://github.com/phusion/baseimage-docker/tree/master/image

I have created a public repo here with the last version:
https://hub.docker.com/r/jjborie/baseimage-docker/

Then just reference it on your dockerfile:
FROM jjborie/baseimage-docker

I don't understand why they didn't make it available directly on docker hub as a public repo...
Until then I suggest you to create an account on docker hub and create your own repo.

**Comment by akleiber** [comment]
Why not use this one https://hub.docker.com/r/phusion/baseimage/ mentioned here https://github.com/phusion/baseimage-docker#getting-started ?

**Comment by jjborie** [comment]
Ok my bad... thanks @akleiber

**Comment by cypa** [comment]
@akleiber, I have no Dockerfile source, but only docker-image 
this one https://hub.docker.com/r/onlyoffice4enterprise/communityserver-ee/
I need to apply baseimage tricks to this image
@jjborie, thanks, I'll try this

**Comment by jjborie** [comment]
Just add the instructions found here:
http://helpcenter.onlyoffice.com/fr/server/linux/document/linux-installation-enterprise.aspx

In the section ...put your own build instructions here..., using RUN command.
```

FROM phusion/baseimage:<VERSION>

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# ...put your own build instructions here...

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

```

Incomplete example will be:
```
FROM phusion/baseimage

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# Using http://helpcenter.onlyoffice.com/fr/server/linux/document/linux-installation-enterprise.aspx
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe multiverse" | sudo tee -a /etc/apt/sources.list
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-key adv --keyserver keys.gnupg.net --recv-keys 5072E1F5

# Install nodejs and some component needed for front
RUN curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes nodejs

RUN wget http://download.onlyoffice.com/repo/onlyoffice.key
RUN apt-key add onlyoffice.key

# etc ...

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

```

After don't forget to add all services. Example for nginx, it will be:
```
# Service that need to be runned and monitored
RUN mkdir /etc/service/nginx
ADD ./service/nginx.sh /etc/service/nginx/run
RUN chmod +x /etc/service/nginx/run

```

Use the official image instead of mine.
./service/nginx.sh
``` 
#!/bin/sh
/usr/sbin/nginx

```

**Comment by cypa** [comment]
@jjborie OK, shall try this
thanks again
