### ISSUE TITLE
phusion/baseimage size inconsistencies?

### ISSUE THREAD

**Issue by traviswdev** [phusion/baseimage-docker#293]
If I clone this repository and build the docker image from the source then `docker images` will return the image having a size of 244mb. 

If instead I do `docker pull phusion/baseimage:0.9.18`, `docker images` tells me that the size of the image is 305.1mb. 

Why?

Exact steps to replicate this below. I excluded the docker build lines but can include them on request. 
**`$ docker images`**
`REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE`

**`$ docker ps -a`**
`CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES`

**`$ git clone https://github.com/phusion/baseimage-docker.git && cd baseimage-docker && sudo make build NAME=travis/baseimage`**
`Cloning into 'baseimage-docker'...`
...
...
...
`Successfully built 8f63262225f7`

**`$ docker pull phusion/baseimage:0.9.18`**
`0.9.18: Pulling from phusion/baseimage`
`6ffe5d2d6a97: Pull complete`
`f4e00f994fd4: Pull complete`
`e99f3d1fc87b: Pull complete`
`a3ed95caeb02: Pull complete`
`ededd75b6753: Pull complete`
`1ddde157dd31: Pull complete`
`Digest: sha256:9e9b3519ecba8acbe7d5218ff53b618dd7308ef6473dd2c2b4bbbb478e2e1825`
`Status: Downloaded newer image for phusion/baseimage:0.9.18`

**`$ docker images`**
`REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE`
`travis/baseimage      0.9.18              8f63262225f7        About a minute ago   244 MB`
`ubuntu                      14.04               97434d46f197        2 weeks ago          187.9 MB`
`phusion/baseimage  0.9.18              772dd063a060        3 months ago         305.1 MB`

**Comment by traviswdev** [comment]
Do you need any other information from me?

**Comment by FooBarWidget** [comment]
The size difference is probably because the Ubuntu packages have changed since the time we originally built 0.9.18. Maybe newer packages are smaller, for whatever reason. There's nothing we can do about this though.
