### ISSUE TITLE
Is docker-ssh tool secure for production ?

### ISSUE THREAD

**Issue by maxivak** [phusion/baseimage-docker#295]
The documentation for the docker-ssh tool says:

> Looking up the IP of a container and running an SSH command quickly becomes tedious. Luckily, we provide the docker-ssh tool which automates this process. This tool is to be run on the Docker host, not inside a Docker container.

It says as it helps automate work for using my own key.
But docker-ssh  uses  the insecure key.
When trying "docker-ssh <my-container-name>" it shows error:

>  You did not enable the the insecure key inside the container. 

Can I use docker-ssh in production in secure way ?

**Comment by FooBarWidget** [comment]
docker-ssh is not insecure by itself, but it does assume that the container is using the insecure key. docker-ssh currently provides no way for you to specify your own key. So as docker-ssh is right now, it's mostly useful for development and testing environments, not production.
