### ISSUE TITLE
Provide possibility to override default SIGTERM handler

### ISSUE THREAD

**Issue by chrisliu529** [phusion/baseimage-docker#297]
In production cloud computing environment, it often requires a graceful upgrade/downgrade mechanism which means the end users will never experience any downtime (not a single second) during your system deployment.
A practical method is using baseimage with a docker scheduler such as mesos. We can specify --docker_stop_timeout=60 in docker configuration to ask mesos send SIGTERM before SIGKILL in 60 seconds. Then we override the SIGTERM handler to ask LB not to route any traffic to the container to be killed while the remained live traffic data can still be processed during the 60 seconds.
However, the current implementation doesn't allow customisation for SIGTERM handler. If agreed, I will provide a PR for this possibility.

**Comment by FooBarWidget** [comment]
I don't think you need any changes in Baseimage-docker. When my_init receives a SIGTERM, it will initiate the shutdown procedure by terminating Runit services and the main command. Runit services are terminated with `sv down`, which in turn sends SIGTERM. The main command is terminated with SIGTERM. So all you need to do is to ensure that either your services, or your main command, does what you want upon receiving SIGTERM. No need to change my_init itself.
