### ISSUE TITLE
Proposal for the README

### ISSUE THREAD

**Issue by pascalandy** [phusion/baseimage-docker#298]
I would start the README.md with this:

> Baseimage-docker consumes 6 MB and is much powerful than Busybox or Alpine. See why below.

My 5 cents :)

**Comment by FooBarWidget** [comment]
Do you mean that people have the feeling that baseimage-docker uses a lot of resources? And that people don't know the difference between Busybox/Alpine and Ubuntu?

**Comment by pascalandy** [comment]
Exactly! I read this project for 3+ hours and I never saw "Baseimage-docker consumes 6 MB " prior that. I was wondering for a while a thrusted that you guys did a great job at it. 

Think **marketing** wise here. This fact is a big selling point + all the best practices you guys put in place.

Of course my 5 cents only :)

Cheers!
Pascal

**Comment by natostanco** [comment]
You can't compare it to alp/bb, the correct phrasing would be "baseimage docker consumes only 6mb _on top_ of ubuntu" but docker slim appears to be working fine with baseimage, just make sure to run it as sudo/root to copy the `env` files

**Comment by FooBarWidget** [comment]
All right, the blurb has been added. Thanks for the suggestion. :)
