### ISSUE TITLE
Run script AFTER daemons start

### ISSUE THREAD

**Issue by michaeljs1990** [phusion/baseimage-docker#301]
I have a situation in which I want to mount an nfs drive however this means that I have to hack the my_init script so that it will allow for loading after the daemons are started. Does anyone have a way that does not involve modifying my_init. If this is something others would find useful i'll push it back upstream.

**Comment by FooBarWidget** [comment]
The [main command](https://github.com/phusion/baseimage-docker#oneshot) is run after daemons are started.
