### ISSUE TITLE
How can I upgrade Ubuntu to 16.04?

### ISSUE THREAD

**Issue by xlight** [phusion/baseimage-docker#305]
as the title

**Comment by gglachant** [comment]
Try [this](https://github.com/phusion/baseimage-docker/pull/302/commits/e436d1c4af16a5e9590ae4e48e5105f1db787e7f). From my preliminary testing, it works fine.

**Comment by foxycode** [comment]
@xlight Or you can use https://hub.docker.com/r/sunfoxcz/baseimage/ in meantime, it is fork of phusion/baseimage-docker with upgraded ubuntu and few patches from unmerged pull requests.

**Comment by richardriman** [comment]
Hi guys, is there a similar project based on Debian 8?

**Comment by mbookman** [comment]
The image from @foxycode seems to work fine, but I'm wondering if there is an Ubuntu 16 plan for phusion.

**Comment by FooBarWidget** [comment]
Ubuntu 16.04 support has been merged (see pull request #302). Sorry for the delay! Things have been very busy so I've only recently had time to process this.
