### ISSUE TITLE
How to run systemd in docker container with no root user?

### ISSUE THREAD

**Issue by me115** [phusion/baseimage-docker#306]
hello,
I like baseimage-docker, but I need run systemd in docker container. So I tried use systemd to 	
substitute runit，but not successed; Then I tried this one:
https://github.com/dramaturg/docker-debian-systemd

I build a docker image with systemd to run in it;
when I start docker container from root user, systemd works well,
as you see , the following process starts:

>UID         PID   PPID  C STIME TTY          TIME CMD
root          1      0  0 May06 ?        00:00:00 /lib/systemd/systemd
daemon       18      1  0 May06 ?        00:00:00 /usr/sbin/atd -f
root         20      1  0 May06 ?        00:00:04 /usr/sbin/rsyslogd -n
message+     23      1  0 May06 ?        00:00:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-acti
root         29      1  0 May06 ?        00:00:00 /usr/sbin/cron -f
root         31      1  0 May06 ?        00:00:00 /lib/systemd/systemd-logind
root         33      1  0 May06 ?        00:00:15 /lib/systemd/systemd-journald

I can use systemctl to start/stop service ;
But ,when I use other user(not root,eg:tiger),I cann't use systemctl or systemctl --user
in the no root environment;
>tiger@ddb392be5603:/$ systemctl --user status
Failed to connect to bus: No such file or directory

I think if I want user systemctl --user command,I need start the systemd --user process manually,but also cann't start at tiger user environment:
error is:
>tiger@ddb392be5603:/$ /lib/systemd/systemd --user
Failed to create /system.slice/docker.service/init.scope control group: Permission denied
Failed to allocate manager object: Permission denied

please help me ,thanks a lots;

--------------------
PS:
my dockerfile like this:
...
VOLUME [ "/sys/fs/cgroup", "/run", "/run/lock", "/tmp" ]
CMD ["/lib/systemd/systemd"]

run docker command:
docker run -d -t -i -v /sys/fs/cgroup:/sys/fs/cgroup:ro bashimage_debian_use_systemd:v1.0

OS version:
tiger@ddb392be5603:/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.4 (jessie)
Release:	8.4
Codename:	jessie

my doceker version:
># docker --version
Docker version 1.7.0, build 0baf609

Host systemd version:
># systemd --version
systemd 215
+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR

docker container systemd version:
root@ddb392be5603:/# systemd --version
systemd 228
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

**Comment by rfkrocktk** [comment]
You can't run SystemD inside of Docker for a number of reasons unrelated to this project.
