### ISSUE TITLE
Provide a CentOS based baseimage

### ISSUE THREAD

**Issue by naftulikay** [phusion/baseimage-docker#308]
I've been a user of baseimage for quite some time, but I'd really like to see a CentOS fork. For a number of reasons, I've stopped using Ubuntu based images.

**Comment by FooBarWidget** [comment]
Anyone is free to fork this repository and create a CentOS variant, but we won't be doing this because we don't use CentOS containers.

**Comment by jwilson8767** [comment]
I'm working on a Centos port [over here](https://github.com/waystone-systems/baseimage-docker-centos)

**Comment by Theaxiom** [comment]
@jwilson8767 If you don't mind, it would be great to bring your work over to a branch in this repo when the work is completed. I have re-opened this issue to track. Please reference this issue when ready for us to pull over, thanks!

**Comment by jwilson8767** [comment]
@Theaxiom Right now all the docs are Ubuntu focused, do you have any plans to generalize them for other ports?

**Comment by hyperknot** [comment]
I'd personally vote for a separate repo like baseimage-centos or similar. Mixing issues, maintaining one OS's particularities etc. definitely needs full attention and "full-time" contributors maintaining those very specific issues.

**Comment by Theaxiom** [comment]
You have a point, thanks. I suppose you are correct. Maybe we should add the other repo links to the readme instead.

**Comment by hyperknot** [comment]
Yes, links to related projects is a good idea in the README.

**Comment by jwilson8767** [comment]
Links to forks/ports sounds like a start. The next big thing as far as I'm concerned would be to have one the maintainers of phusion/baseimage-docker join me on this Centos fork. Mostly to reduce divergence, but also to ensure that my efforts here don't go to waste as I shift focus to other projects.

**Comment by hyperknot** [comment]
@jwilson8767 if you start a fork, it's only up to you how much maintenance it receives and how long do you keep it updated. As you can see even with a handful of maintainers on a very stable repo sometimes it takes time to keep this repo up-to-date.

**Comment by jwilson8767** [comment]
I agree completely. My plan is to get this Centos fork stable/production ready, and then to attempt to keep in sync with upstream changes. I just know the amount of time I can put into OSS waxes and wanes as I have paying projects.

**Comment by Theaxiom** [comment]
If other people are using it and interested in contributing, they will. :)

**Comment by naftulikay** [comment]
FYI I have at least started work on a CentOS 7 base image: https://github.com/naftulikay/docker-baseimage

**Comment by rajivr** [comment]
@hyperknot FYI we a maintaining a fork for Amazon Linux and Fedora here - https://github.com/lambda-linux/baseimage-amzn and https://github.com/lambda-linux-fedora/baseimage-fedora

**Comment by hyperknot** [comment]
OK, I think it might be a good idea to keep a table of forks in the main readme.

**Comment by Theaxiom** [comment]
agreed @hyperknot

**Comment by Theaxiom** [comment]
I created a wiki page here: https://github.com/phusion/baseimage-docker/wiki/Baseimage-Inspired-Projects
