### ISSUE TITLE
Dockerize, or waiting for external service, in Phusion BaseImage

### ISSUE THREAD

**Issue by jquacinella** [phusion/baseimage-docker#311]
I found this nifty little utility called dockerize (https://github.com/jwilder/dockerize) that will make the docker container wait for an external service to be made available. For instance, I use it while using docker-compose to make some containers wait until a DB is up and running before starting a backend app.

The downside is that using it as the CMD of the container (ie. dockerize -wait tcp://mysqldb-container:3306 -timeout 60s /sbin/my_init), then my_init no longer reaps zombie processes. Is there any way to get the best of both worlds: using my_init for proper process mgmt but also make the container wait for an external service?

Thanks!

**Comment by FooBarWidget** [comment]
You should run my_init first, and then let my_init run dockerize.
