### ISSUE TITLE
Packer, ansible, ssh

### ISSUE THREAD

**Issue by chrisRidgers** [phusion/baseimage-docker#313]
A couple of months ago I attempted to use this base image as a starting point for playing around with Packer and provisioning custom images for docker.

I wanted to use Ansible to provision the image over SSH as part of the packer process.  Unfortunately, I was unable to get very far; ran into a multitude of issues regarding ssh keys/ authentication.

I'm looking to try again though, does anyone have any experience using this image in this way?

**Comment by FooBarWidget** [comment]
Unfortunately I cannot help you, I have no experience with Ansible. And it seems nobody else who has looked in this issue knows it either. But I have the feeling that this is more of an Ansible issue than a Docker issue, so maybe you would have more luck on an Ansible support forum.
