### ISSUE TITLE
Error to build after your last release in 'add-apt-repository'

### ISSUE THREAD

**Issue by jlruizmlg** [phusion/baseimage-docker#317]
Hello, 
After your last release i had an error adding repositories

```
Build failed: The command '/bin/sh -c add-apt-repository -y ppa:webupd8team/java && apt-get update && echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections && apt-get -yf install oracle-java8-installer' returned a non-zero code: 127
```

In ubuntu 14.04 works nice.

**Comment by jlruizmlg** [comment]
sorry i have the saem error under 14.04 my mistake

**Comment by arg20** [comment]
I have the same error now, I use this for CI and all my builds are failing.

**Comment by arg20** [comment]
`/bin/sh: 1: sudo: not found`

`The command '/bin/sh -c sudo apt-get -y install software-properties-common && sudo add-apt-repository ppa:chris-lea/node.js && sudo apt-get update' returned a non-zero code: 127`

**Comment by jlruizmlg** [comment]
A hot fix lock the version to the last tag and works as usual

**Comment by FooBarWidget** [comment]
This is not a problem in baseimage-docker. Things are supposed to be slightly different between distribution versions. Some things which were installed by default may no longer be installed by default, and vice versa. You are responsible for updating your build scripts according.

For example in @arg20's case, the error message clearly shows that 'sudo' is not found, so you need to install that yourself.
