### ISSUE TITLE
[16.04] debconf: delaying package configuration, since apt-utils is not installed

### ISSUE THREAD

**Issue by hyperknot** [phusion/baseimage-docker#319]
On newest image 0.9.19, if I run any apt-get command, I received the following red warning line:
`debconf: delaying package configuration, since apt-utils is not installed`

Minimal example:

```
FROM phusion/baseimage:0.9.19

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# ...put your own build instructions here...
RUN apt-get update && apt-get upgrade -y -o Dpkg::Options::="--force-confold"

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

This is only happening in 0.9.19 / Ubuntu 16.04.

**Comment by franklinyu** [comment]
Upstream problem; I can confirm this with image `ubuntu:16.04`.

**Comment by aa21** [comment]
Did you find any solutions for this? @hyperknot @franklinyu

**Comment by hyperknot** [comment]
yes, I'm installing it myself

**Comment by franklinyu** [comment]
@aa21 I did not. The Debian-Docker guys thought this is an issue of APT incorrectly requiring the (unnecessary) package, and refused to fix it, since this is just a warning not able to stop you from anything. I guess they are too busy for it.

Good to hear that @hyperknot is trying to fix it. I am looking forward to his solution/workaround.

**Comment by hyperknot** [comment]
My solution is just to put a 

    RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

line in the docker file and it fixes the problem.

**Comment by aa21** [comment]
Thanks @hyperknot and @franklinyu.

**Comment by WesleyBatista** [comment]
It did not worked for me =/

```
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 1b35b989ce4d
 ---> 78f654f9ea69
Removing intermediate container 1b35b989ce4d
Step 3 : RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
 ---> Running in 29d7eb2e1bb5
Get:1 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial/main Sources [1103 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/restricted Sources [5179 B]
Get:6 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main Sources [250 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [129 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [522 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [432 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-security/main Sources [52.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-security/universe Sources [13.4 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-security/main amd64 Packages [196 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [62.2 kB]
Fetched 18.4 MB in 4min 14s (72.2 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapt-inst2.0
The following NEW packages will be installed:
  apt-utils libapt-inst2.0
0 upgraded, 2 newly installed, 0 to remove and 5 not upgraded.
Need to get 251 kB of archives.
After this operation, 1203 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapt-inst2.0 amd64 1.2.12~ubuntu16.04.1 [55.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 apt-utils amd64 1.2.12~ubuntu16.04.1 [196 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 251 kB in 1s (176 kB/s)
Selecting previously unselected package libapt-inst2.0:amd64.
(Reading database ... 7256 files and directories currently installed.)
Preparing to unpack .../libapt-inst2.0_1.2.12~ubuntu16.04.1_amd64.deb ...
Unpacking libapt-inst2.0:amd64 (1.2.12~ubuntu16.04.1) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../apt-utils_1.2.12~ubuntu16.04.1_amd64.deb ...
Unpacking apt-utils (1.2.12~ubuntu16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Setting up libapt-inst2.0:amd64 (1.2.12~ubuntu16.04.1) ...
Setting up apt-utils (1.2.12~ubuntu16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
```

**Comment by Lewiscowles1986** [comment]
it's the only red command I now get when setting up my jekyll x86 base image...

**Comment by yosualb** [comment]
```
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils
```

didn't work for me too.

**Comment by hyperknot** [comment]
It is a harmless error message. The command does get installed, and any following apt-get command does not provide any error message. Don't worry about that one red line.

**Comment by hyperknot** [comment]
I started making an updated fork of this project, containing Ubuntu 16.04 fixes, including this one. Have a look here:
https://github.com/hyperknot/baseimage16

**Comment by vlymar** [comment]
> The command does get installed, and following apt-get commands do not show any error / warning messages.

When I install apt-utils before the rest of apt packages, I only get `delaying package configuration` for the installation of the apt-utils package, which makes sense. However, I get the following warnings for the other packages:

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
```

Apparently this is also a harmless warning that can be avoided by setting `DEBIAN_FRONTEND=noninteractive` as some others have in this thread.

If anyone is wondering what the best-practice way to set this variable is, this is the best info I could find https://github.com/docker/docker/issues/4032#issuecomment-192327844 .

The key takeaway there is make sure you don't use `ENV` to set this because it will persist in the image, but you only want that value set during the docker build stage.

I wonder though, what if you're installing a package that does depend on interactive configuration? Does apt-get just fail, or will it just silently leave the package unconfigured?

**Comment by hyperknot** [comment]
I don't think apt-get allows packages which only work in interactive mode. So all packages must work in noninteractive mode.

What I do is I set 

```
ENV DEBIAN_FRONTEND noninteractive
```

in the beginning of the Docker file 
and I set 

```
ENV DEBIAN_FRONTEND teletype
```
At the very end. This way both interactive and non-interactive modes get set.

**Comment by franklinyu** [comment]
@hyperknot Why two `ENV` instead of a single (and more future-proof) `ARG`?

**Comment by hyperknot** [comment]
They are totally different. ENV is persistent in the image. It'd still need two cases here.

**Comment by franklinyu** [comment]
But why do you need to persist it (which overrides the default)? The default frontend works for me.

**Comment by hyperknot** [comment]
The default gives a warning about falling back to teletype. So setting it
to teletype fixes that.

**Comment by franklinyu** [comment]
Yes, I just confirmed that. I thought the default only gives warning when installing packages in Dockerfile. I missed that because the warning was not highlighted as red (of course), and that doesn't happen on normal Ubuntu. However, `teletype` is not a known value for `DEBIAN_FRONTEND` according to [documentation online](https://www.debian.org/releases/jessie/amd64/ch05s03.html.en#installer-args) (??), while the `newt` mentioned as default in documentation still produces the warning for me (???).

**Comment by hyperknot** [comment]
I noticed that as well. But Teletype is the one it is falling back
automatically also "Falling back to Teletype", so I believe it's a
reasonable choice.

**Comment by Theaxiom** [comment]
Being that this is an upstream issue, I am closing this issue. It looks like there is a viable workaround and this issue will remain for posterity.

**Comment by aairey** [comment]
FWIW
It is better to use `ARG` on newer docker installations, as this only sets the `ENV` during build time (See https://github.com/moby/moby/issues/4032).

```
ARG DEBIAN_FRONTEND=noninteractive
```
But I am still getting the warnings about apt-utils.

**Comment by Theaxiom** [comment]
@aairey Did you try adding this to your Dockerfile?

`RUN apt-get update && apt-get install -y --no-install-recommends apt-utils`

**Comment by franklinyu** [comment]
@aairey We discussed about why we need `ENV` instead of `ARG` above.

**Comment by aairey** [comment]
@Theaxiom this just installs `apt-utils`?
I thought there was a way to just make the warning go away without installing apt-utils.
When apt-utils is installed, the build is way slower, and since it is not the default I prefer not to install it.
But seems there is no way to get rid of the warning without installing `apt-utils`?

@franklinyu it works for me just using `ARG`.
The `apt-utils` warning and reason for using `noninteractive` is unrelated. (unless I am missing something?).
The `noninteractive` setting just makes sure no dialogs are opened and that `dpkg-reconfigure` dus not prompt you for input.
At least that is my understanding after fiddling around with it yesterday.

**Comment by Theaxiom** [comment]
@aairey Unfortunately, I think that is indeed the only way to make the error message go away. From what I understand it is a no-op.

**Comment by hyperknot** [comment]
You need both apt-utils and noninteractive. Installing apt-utils is really not making any difference in build speed, it's a tiny util which should actually be part of official image.

**Comment by Theaxiom** [comment]
@hyperknot Are you proposing this be added to baseimage-docker?

**Comment by hyperknot** [comment]
@Theaxiom I'd definitely add apt-utils here:
https://github.com/hyperknot/baseimage16/blob/master/image/prepare.sh#L34
and
teletype at the end:
https://github.com/hyperknot/baseimage16/blob/master/image/Dockerfile#L19

**Comment by Theaxiom** [comment]
Sounds like a plan, thanks @hyperknot 👍

**Comment by EduardoBorsa** [comment]
Anyone was able to solve this?
None of the previous solutions solved for me.
Still receiving the "returned a non-zero code: 100"

**Comment by viniarck** [comment]
@EduardoBorsa, if you're running Kernel 4.19 check this out:

https://gist.github.com/Francesco149/ce376cd83d42774ed39d34816b9e21db

**Comment by punitvara** [comment]
sudo aptitude install apt-utils

**Comment by kaioramos** [comment]
> @Theaxiom I'd definitely add apt-utils here:
> https://github.com/hyperknot/baseimage16/blob/master/image/prepare.sh#L34
> and teletype at the end:
> https://github.com/hyperknot/baseimage16/blob/master/image/Dockerfile#L19
> 
> noninteractive is already part of buildconfig

Add the ENV DEBIAN_FRONTEND teletype works for me. Thanks

**Comment by Lucas-Malor** [comment]
`teletype` does not work for me. This is my `Dockerfile`:

```
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=teletype

RUN apt-get update
RUN apt-get install -y evince

CMD ["evince"]
```

**Comment by spartacutz** [comment]
I found this solution that works for me from: https://stackoverflow.com/questions/51023312/docker-having-issues-installing-apt-utils

it consists of following the commands apt-get install on the same line as ENV DEBIAN_FRONTEND noninteractive:

DEBIAN_FRONTEND=noninteractive apt-get install -y <pkgs>

**Comment by zendriani3006** [comment]
my solution

apt-get update && apt-get install -y --no-install-recommends apt-utils

**Comment by Marco-Sulla** [comment]
> `teletype` does not work for me. Neither installing `apt-utils` This is my `Dockerfile`:
> 
> ```
> FROM ubuntu:18.04
> ENV DEBIAN_FRONTEND=teletype
> 
> RUN apt-get update
> RUN apt-get install -y --no-install-recommends apt-utils
> RUN apt-get install -y evince
> 
> CMD ["evince"]
> ```

I already tried your suggestion and they does not work for me. Furthermore they are already suggested in this issue.

**Comment by kingdonb** [comment]
There should be no difference between runtime environments in a container on one host to another, I don't know why something would work for one person but not others unless there was drift over time.  Please provide us with some error output, if you think something is wrong.

**Comment by chetabahana** [comment]
While the issue has been closed but still unclear solution on this case that already runs for years .

Currently the highest votes goes to:
```
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils
```

but it still gives the warning
```
debconf: delaying package configuration, since apt-utils is not installed
```

**Comment by kingdonb** [comment]
I am assuming you get this message while installing apt-utils, indicating that apt-utils hasn't finished installing yet, but that subsequent apt-get install invocations no longer print the warning.  Is that not the case?

**Comment by ssbarnea** [comment]
I am quite curious if someone manages to result the apt-utils issue without triggering any warnings. Ignoring warnings in builds is very bad practice, once you let them in, they will grow exponentially and everyone will ignore them.

**Comment by bjornoj** [comment]
I don't get why this issue is closed, it is still an issue. This is my Dockerfile:
```
FROM postgres:latest

ENV TZ=UTC
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y postgresql-contrib
COPY sql/* /docker-entrypoint-initdb.d/
```

And these are my logs, from running `docker-compose build`
```
Step 5/8 : RUN apt-get update
 ---> Running in 142bd8adbec2
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [161 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7,908 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [5,792 B]
Get:7 http://apt.postgresql.org/pub/repos/apt buster-pgdg InRelease [46.2 kB]
Get:8 http://apt.postgresql.org/pub/repos/apt buster-pgdg/main amd64 Packages [151 kB]
Get:9 http://apt.postgresql.org/pub/repos/apt buster-pgdg/12 amd64 Packages [861 B]
Fetched 8,510 kB in 6s (1,437 kB/s)
Reading package lists...
Removing intermediate container 142bd8adbec2
 ---> 7024764329ca
Step 6/8 : RUN apt-get install -y --no-install-recommends apt-utils
 ---> Running in f9258fb99c3f
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapt-inst2.0
The following NEW packages will be installed:
  apt-utils libapt-inst2.0
0 upgraded, 2 newly installed, 0 to remove and 5 not upgraded.
Need to get 625 kB of archives.
After this operation, 1,655 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libapt-inst2.0 amd64 1.8.2 [204 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 apt-utils amd64 1.8.2 [421 kB]


debconf: delaying package configuration, since apt-utils is not installed


Fetched 625 kB in 0s (4,284 kB/s)
Selecting previously unselected package libapt-inst2.0:amd64.
(Reading database ... 13981 files and directories currently installed.)
Preparing to unpack .../libapt-inst2.0_1.8.2_amd64.deb ...
Unpacking libapt-inst2.0:amd64 (1.8.2) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../apt-utils_1.8.2_amd64.deb ...
Unpacking apt-utils (1.8.2) ...
Setting up libapt-inst2.0:amd64 (1.8.2) ...
Setting up apt-utils (1.8.2) ...
Processing triggers for libc-bin (2.28-10) ...
Removing intermediate container f9258fb99c3f
 ---> 1fa9de755ff2
```

**Comment by danielxfr** [comment]
I keep having the same issue. Nothing said above solved my problem. Where we are going?

My Dockerfile:
```shell
FROM php:7.2-apache

ARG TERM=xterm
ARG LC_ALL=C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install --yes --no-install-recommends apt-utils 
RUN apt-get install --yes --no-install-recommends apt-transport-https
```

My output:
```shell
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM php:7.2-apache
 ---> d0e98d20a124
Step 2/7 : ARG TERM=xterm
 ---> Running in e2c44669cea7
Removing intermediate container e2c44669cea7
 ---> 2f2ace91ade4
Step 3/7 : ARG LC_ALL=C.UTF-8
 ---> Running in 2f63d8e4765f
Removing intermediate container 2f63d8e4765f
 ---> cbbdc3930308
Step 4/7 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Running in 7a9d5fd0474c
Removing intermediate container 7a9d5fd0474c
 ---> 9b41b58bd730
Step 5/7 : RUN apt-get update
 ---> Running in 40244a45a5fb
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security-cdn.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7908 kB]
Get:5 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [167 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]
Fetched 8317 kB in 9s (897 kB/s)
Reading package lists...
Removing intermediate container 40244a45a5fb
 ---> 1ac1a52a0771
Step 6/7 : RUN apt-get install --yes --no-install-recommends apt-utils
 ---> Running in 843eb4e89040
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  sensible-utils
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  libapt-inst2.0
The following NEW packages will be installed:
  apt-utils libapt-inst2.0
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 625 kB of archives.
After this operation, 1655 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libapt-inst2.0 amd64 1.8.2 [204 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 apt-utils amd64 1.8.2 [421 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 625 kB in 1s (692 kB/s)
Selecting previously unselected package libapt-inst2.0:amd64.
(Reading database ... 13530 files and directories currently installed.)
Preparing to unpack .../libapt-inst2.0_1.8.2_amd64.deb ...
Unpacking libapt-inst2.0:amd64 (1.8.2) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../apt-utils_1.8.2_amd64.deb ...
Unpacking apt-utils (1.8.2) ...
Setting up libapt-inst2.0:amd64 (1.8.2) ...
Setting up apt-utils (1.8.2) ...
Processing triggers for libc-bin (2.28-10) ...
Removing intermediate container 843eb4e89040
 ---> cacb6cd31c49
Step 7/7 : RUN apt-get install --yes --no-install-recommends apt-transport-https
 ---> Running in 46e69d0a1858
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  sensible-utils
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 149 kB of archives.
After this operation, 156 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 apt-transport-https all 1.8.2 [149 kB]
Fetched 149 kB in 0s (377 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 13660 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2_all.deb ...
Unpacking apt-transport-https (1.8.2) ...
Setting up apt-transport-https (1.8.2) ...
Removing intermediate container 46e69d0a1858
 ---> 0d811308b11d
Successfully built 0d811308b11d
```

**Comment by Marco-Sulla** [comment]
@danielxfr It's seems to me correct. The message comes out when you are installing `apt-utils` itself. Of course `debconf` does not find `apt-utils` and gives you the warning.

But when you install `apt-transport-https`, no warning is displayed.

PS: I continue to receive notification from this bug even if I unsubscribed... now I subscribe and re-unsubscribe, but if the problem persist, where can I signal it?

**Comment by FranklinYu** [comment]
@Marco-Sulla I think it’s https://support.github.com/contact

**Comment by sebthom** [comment]
@danielxfr how about:
```Dockerfile
FROM ...

ARG DEBIAN_FRONTEND=noninteractive

RUN \
  apt-get update -y && \
  apt-get install -y apt-utils 2>&1 | grep -v "since apt-utils is not installed" && \
  apt-get install -y --no-install-recommends package1,package2,...
```

**Comment by Theaxiom** [comment]
I will reopen this issue until we come to a conclusion.

**Comment by alanivey** [comment]
Building off of https://github.com/phusion/baseimage-docker/issues/319#issuecomment-573368959 from @sebthom; if you use bash, you can keep STDERR text separate from STDOUT and apply the grep pattern only in the STDERR text:
```
FROM ...

ARG DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN \
  apt-get update -y && \
  apt-get install -y apt-utils 2> >( grep -v 'debconf: delaying package configuration, since apt-utils is not installed' >&2 ) && \
  apt-get install -y --no-install-recommends package1,package2,...
```

**Comment by marcusjwhelan** [comment]
This is also an issue exists on Ubuntu's 18.04 image

**Comment by nysta1** [comment]
I too have this apt-utils problem and it's really bringing the grade of development down, it says unable to.further configure after this.

**Comment by rufreakde** [comment]
Having also the apt-utils issue and when I want to install gcc of a specific version it also does not export it in the PATH correctly... after adding the install line of apt-utils it at least added the gcc files into the bin directory.


```bash
RUN                                                                                                                     \
    set     -eux                                                                                                        \ 
    && apt-get -y update                                                                                                \
    && apt-get install -y apt-utils                                                                                     \
	&& apt-get -y install --no-install-recommends --no-install-suggests --fix-missing bash-static                       \
    && apt-get -y install gcc-4.8                                                                                       \
    && apt-get -y install make                                                                                          \
    && cp /bin/bash-static /sh
```

then I get the following errors on make gcc and so on:

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 21.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
```

After some googling I found this here
https://github.com/moby/moby/issues/27988

added the dialog apt-utils line but the error still persists not sure if both problems are related. Anyone else having the same behaviour on ubuntu:18.04 image?
```bash
RUN                                                                                                                     \
    set     -eux                                                                                                        \ 
    && apt-get -y update                                                                                                \
    && apt-get install -y dialog apt-utils                                                                              \
    && apt-get -y install --no-install-recommends --no-install-suggests --fix-missing bash-static                       \
    && apt-get -y install gcc-4.8                                                                                       \
    && apt-get -y install make                                                                                          \
    && cp /bin/bash-static /sh            
```

**Comment by rufreakde** [comment]
Update: just adding seems to do the trick for the ubuntu image. gcc is still not found in the path but that I can fix by hand I think.
```
ENV DEBIAN_FRONTEND="noninteractive"
```

**Comment by stephanwehr** [comment]
The behavior is controlled by the configuration setting:
`DPkg::Pre-Install-Pkgs`

The default setting is configured via "/etc/apt/apt.conf.d/70debconf":
```
// Pre-configure all packages with debconf before they are installed.
// If you don't like it, comment it out.
DPkg::Pre-Install-Pkgs {"/usr/sbin/dpkg-preconfigure --apt || true";};
```

To disable the setting permanently:
```dockerfile
RUN set -x \
&& sed -Ei 's|^(DPkg::Pre-Install-Pkgs .*)|#\1|g' /etc/apt/apt.conf.d/70debconf \
&& apt-get update \
&& apt-get upgrade -y
```

To disable the setting temporarily:
```dockerfile
RUN set -x \
&& mv /etc/apt/apt.conf.d/70debconf . \
&& apt-get update \
&& apt-get install -y apt-utils \
&& mv 70debconf /etc/apt/apt.conf.d \
&& apt-get upgrade -y
```

Show less debconf warnings:
`ARG DEBCONF_NOWARNINGS="yes"`

Here is an example Docker file including all methods mentioned above, pick the one that fits your use case.
_To get the full "apt-get" output, remove "-qq" and ">/dev/null"._
```dockerfile
ARG IMAGE="ubuntu:16.04"
FROM ${IMAGE}

ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBCONF_NOWARNINGS="yes"
ARG DEBCONF_TERSE="yes"
ARG APT="apt-get -qq -y"
ARG LANG="C.UTF-8"

# Configure APT
RUN set -x \
&& echo "debconf debconf/frontend select ${DEBIAN_FRONTEND}" | debconf-set-selections \
&& echo 'APT::Install-Recommends "false";' | tee /etc/apt/apt.conf.d/99install-recommends \
&& echo 'APT::Get::Assume-Yes "true";' | tee /etc/apt/apt.conf.d/99assume-yes \
&& sed -Ei 's|^(DPkg::Pre-Install-Pkgs .*)|#\1|g' /etc/apt/apt.conf.d/70debconf \
&& debconf-show debconf

# Install Packages
RUN set -x \
&& mv /etc/apt/apt.conf.d/70debconf . \
&& ${APT} update \
&& ${APT} install apt-utils >/dev/null \
&& mv 70debconf /etc/apt/apt.conf.d \
&& ${APT} upgrade >/dev/null \
&& ${APT} install curl >/dev/null
```

References:
[debconf - Preconfiguring packages](https://manpages.ubuntu.com/manpages/focal/en/man7/debconf.7.html#preconfiguring%20packages)
[apt.conf - SYNTAX](https://manpages.ubuntu.com/manpages/focal/en/man5/apt.conf.5.html#syntax)

**Comment by Theaxiom** [comment]
Thank you @stephanwehr for your insight! :)

**Comment by boussou** [comment]
in the end the reco from @stephanwehr is enough:
just add this at the beginning of your dockerfile

    ENV DEBIAN_FRONTEND noninteractive
    ENV DEBCONF_NOWARNINGS="yes"

**Comment by rolandhemmer** [comment]
> in the end the reco from @stephanwehr is enough: just add this at the beginning of your dockerfile
> 
> ```
> ENV DEBIAN_FRONTEND=noninteractive
> ENV DEBCONF_NOWARNINGS="yes"
> ```

This. This is exactly what I was looking for.  
These two lines (and these two only) work exactly as intended. Didn't have to do anything else, no more warnings, life goes on, my wife didn't leave me, my dog is happy, I can finally rest.
Many thanks!

**Comment by Mugane** [comment]
> My solution is just to put a
> 
> ```
> RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
> ```
> 
> line in the docker file and it fixes the problem.

Now I get 
```
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/pe rl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 6.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```

**Comment by Mugane** [comment]
Even after adding 
```
ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update && echo "\n\nInstalling apt-utils:\n\n" && apt-get install -y --no-install-recommends apt-utils
```
I still get this for the install of apt-utils:
```
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapt-inst2.0
The following NEW packages will be installed:
  apt-utils libapt-inst2.0
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 625 kB of archives.
After this operation, 1650 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 libapt-inst2.0 amd64 1.8.2.3 [204 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 apt-utils amd64 1.8.2.3 [421 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 625 kB in 0s (49.9 MB/s)
Selecting previously unselected package libapt-inst2.0:amd64.
(Reading database ... 29516 files and directories currently installed.)
Preparing to unpack .../libapt-inst2.0_1.8.2.3_amd64.deb ...
Unpacking libapt-inst2.0:amd64 (1.8.2.3) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../apt-utils_1.8.2.3_amd64.deb ...
Unpacking apt-utils (1.8.2.3) ...
Setting up libapt-inst2.0:amd64 (1.8.2.3) ...
Setting up apt-utils (1.8.2.3) ...
Processing triggers for libc-bin (2.28-10+deb10u1) ...
Removing intermediate container 90a8af7fd7b2
 ```

**Comment by qindongliang** [comment]
> in the end the reco from @stephanwehr is enough: just add this at the beginning of your dockerfile
> 
> ```
> ENV DEBIAN_FRONTEND noninteractive
> ENV DEBCONF_NOWARNINGS="yes"
> ```

Simplest answer, the nasty warning is finally gone
