### ISSUE TITLE
move to 16.04 not trivial for PHP users

### ISSUE THREAD

**Issue by jazzmind** [phusion/baseimage-docker#320]
Hi guys - the choice to "upgrade" to 16.04 comes with a steep consequence - any PHP users who depend on php5 and aren't ready to move to PHP7 are out of luck.

From a "semantic-like" versioning perspective, this was not a patch upgrade... this is a breaking upgrade and should have been 0.10.1 vs 0.9.19, or some other way of telegraphing to users who are pulling baseimage:latest

The problem is you've also combined patches which don't involve the Ubuntu release with the upgrade, which means we either have to fork and maintain our own version of baseimage-docker or stay on 0.9.18 until we migrate to php7.

May I suggest giving us the choice of 14.04 or 16.04, but everything else equal? This would make transitioning helpful.

**Comment by FooBarWidget** [comment]
I'm afraid that would make maintenance too hard for us. I think the best solution is for you to maintain your own fork based on 14.04.

**Comment by acejam** [comment]
@jazzmind Just install PHP via a PPA and you're all set.

```
RUN add-apt-repository -y ppa:ondrej/php && \
    apt-get update && \
    apt-get install -y php5.6-fpm php5.6-mysql && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

I have PHP-FPM 5.6 with nginx working just fine on baseimage 0.9.19 (16.04)
