### ISSUE TITLE
my_init has zombie child process [0.9.18]

### ISSUE THREAD

**Issue by danbeaulieu** [phusion/baseimage-docker#322]
```
root     127378  0.0  0.0 202296  4024 ?        Sl   08:35   0:00  |   \_ docker-containerd-shim d751a23e8a30645db7d7d85aca07002b5ae90fa3e77ce9026785ca2dc0a15b16 /var/run/docker/libcontainerd/d751a23e8a30645db7d7d85aca07002b5ae90fa3e77ce9026785ca2dc0a15b16 docker-runc
root     127397  0.0  0.0      0     0 ?        Ss   08:35   0:00  |   |   \_ [my_init]
10002    130354  0.0  0.0      0     0 ?        Zl   08:35   0:03  |   |       \_ [java] <defunct>
```

I see this in docker logs:

```
*** Shutting down runit daemon (PID 1607)...
*** Killing all processes...

Session terminated, terminating shell...XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":1"
      after 20532 requests (20532 known processed) with 0 events remaining.
 ...terminated.
*** Not all processes have exited in time. Forcing them to exit.
```

This results in docker stop and docker kill hanging indefinitely. It is sporadic, and may be related to #315 but these containers are running for a long time before it is stopped and that issue seems to indicate a timing issue during initial container creation.

I also see a similar user report: https://groups.google.com/forum/#!topic/passenger-docker/qpqXqZePP3k

**Comment by FooBarWidget** [comment]
Is my_init running as PID 1 inside the container? Otherwise it won't work.

**Comment by danbeaulieu** [comment]
I *think* I see the issue, not sure how to reproduce. 

At https://github.com/phusion/baseimage-docker/blob/master/image/bin/my_init#L214 it will kill all processes it can but if the process is a zombie process it won't respond which will block that call indefinitely. It seems like this can happen if during kill_all_processes the alarm signal is sent which drops us in to the except code path before we can waitpid to clean up the zombie. 

I'm not sure what the solution is or how to reproduce (possibly set the alarm timeout to a very small value?)

One solution may be to identify zombie processes and waitpid them so that they are removed before doing the os.kill?

**Comment by sra** [comment]
This happens to me as well (also with a java process). Things work well for a time and then suddenly all container restarts will produce hung containers with the defunct java processes. The containers are hung, resistant to stop/start/remove.
