### ISSUE TITLE
Cannot upload files larger than a few kb with SFTP

### ISSUE THREAD

**Issue by mayerwin** [phusion/baseimage-docker#325]
I am trying to use baseimage-docker to set up a remote python interpreter with PyCharm. A few helper files need to be uploaded to the container through SFTP, however it is impossible to upload files larger than a few kB. Bitvise reports the following error:

> 01:43:24.759 Authentication completed.
> 01:43:24.791 SFTP channel opened.
> 01:43:24.846 The SSH2 session has terminated with error. Reason: Error class: LocalSshDisconn, code: ConnectionLost, message: FlowSshTransport: received EOF.

No SFTP client will work, and downloads work fine (even for large file size).
Here is a Dockerfile that can be used to replicate the issue:

```
FROM phusion/baseimage:latest

RUN rm -f /etc/service/sshd/down
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh
RUN /usr/sbin/enable_insecure_key



EXPOSE 22
CMD ["/sbin/my_init"]

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

And the docker run command:
`docker run -d -p 2222:22 test_baseimage
`

For reference, I encounter the same issue with the following alternate Dockerfile:

```
FROM continuumio/anaconda3:4.1.1

# Install OpenSSH
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
```

Do you have an idea what can be causing such an issue? Is it a bug in baseimage, a bad configuration of sshd, or a bug in docker networking?

**Comment by mayerwin** [comment]
For reference, I encounter the same issue with the following alternate Dockerfile:

```
FROM continuumio/anaconda3:4.1.1

# Install OpenSSH
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

```

**Comment by Theaxiom** [comment]
@mayerwin I am not quite sure, I will have to investigate this and get back to you. Have you found a solution in the meantime?

**Comment by mayerwin** [comment]
No, I haven't.

**Comment by Theaxiom** [comment]
Thanks @mayerwin I will let you know what I find. Thanks for bringing this to our attention!

**Comment by uptimestar** [comment]
Any updates? I'd like sftp.

**Comment by hyperknot** [comment]
I'm not using SSH/SFTP nor do I believe they actually belong in a Docker container, so I cannot help with this, maybe others can chime in.

Actually, @uptimestar what's wrong with using `docker cp`?
