### ISSUE TITLE
service/run_script con't correct run by my_init

### ISSUE THREAD

**Issue by 1071496910** [phusion/baseimage-docker#326]
service/run_script con't correct run by my_init .
but when I run exec -it bash to container ,then run /etc/service/service_name/run it is ok . Is it a bug?

service_name/run 
# !/bin/sh

/codis/codis-start create_group

service_name/finish
# !/bin/sh

echo "create_group,run rc=$1"
if [ 0 -eq $1 ]; then
   sv down create-group
fi
exit 0

**Comment by Theaxiom** [comment]
@1071496910 I am not quite understanding the question, what exactly are the steps to reproduce this issue?

**Comment by Theaxiom** [comment]
Since we haven't heard back from you I am going to close this issue, if the issue persists please let us know. Thanks!
