### ISSUE TITLE
is it possible to run shell script on docker stop?

### ISSUE THREAD

**Issue by sandrodz** [phusion/baseimage-docker#328]
lets say I want to do database backup when disposing of the container, is it possible to run shell script on docker stop or docker-compose down ?

**Comment by hyperknot** [comment]
I've run into the same problem and have just submitted a PR for it:
https://github.com/phusion/baseimage-docker/pull/329

**Comment by sandrodz** [comment]
fantastic, thanks!

**Comment by hyperknot** [comment]
I started making an updated fork of this project, containing my fix for this. 
Have a look here:
https://github.com/hyperknot/baseimage16

**Comment by Theaxiom** [comment]
@hyperknot Would you mind kindly submitting a PR for your changes? I see you had one previously. Thank you!

**Comment by hyperknot** [comment]
I'll be merging this one in after #400.

**Comment by hyperknot** [comment]
This has actually been fixed in 0.9.22 via #402.
