### ISSUE TITLE
0.9.18 : rc.local script called before services

### ISSUE THREAD

**Issue by ffrouin** [phusion/baseimage-docker#331]
Hello,

From my own tests with 0.9.18 it looks like the rc.local script is called before /etc/services/<service>/run scripts. Could you confirm this ?

Then, I thought /etc/rc.local script may be called after system services are running... What is your position on that subject ?

Thanks,
Best Regards,                Freddy.

**Comment by FooBarWidget** [comment]
/etc/rc.local is indeed called after /etc/services/*/run. But calling /etc/services/*/run merely *starts* services. This step does not wait until the services are actually up and running. So it may well be that, by the time /etc/rc.local is called, the services are still in the state of starting up.

You should put some waiting code in your own script to wait until necessary services are actually started. There is not a standard way to do this; it depends on the specific service.
