### ISSUE TITLE
Ability to pass a SIGTERM/SIGINT translate flag into my_init

### ISSUE THREAD

**Issue by schuylr** [phusion/baseimage-docker#335]
I'd like it to be possible to pass an extra flag that makes it possible to translate Docker's `SIGTERM` signal from `docker stop` into a more nginx-friendly `SIGQUIT`. More info about Docker signals can be [found here](https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/).

I could see it being possible to accept something like this in the `my_init` script (forgive me as my Python is rusty):

```
parser.add_argument('--translate-sigterm', dest = 'translate_sigterm',
  action = 'store_const', default = 'SIGTERM',
  help = 'Send a different signal instead of SIGTERM for graceful shutdowns (default: SIGTERM)')
```

And then handling all `SIGTERM` signals as that argument's value. Usage would be something like `my_init --translate-sigterm=SIGQUIT`

I'm aware I could pass `docker kill ----signal=SIGQUIT` but I'm using an orchestration platform that doesn't let me specify how it stops Docker containers.

**Comment by tinco** [comment]
Thanks for opening this issue, it does seem like an important feature but it's very specific to nginx. I feel like it would be better to implement this as a wrapper script around the nginx daemon. It's interesting to see even the official docker nginx image does not deal with this.

I think this issue would fit better on the passenger-docker project, since it runs an nginx server per default.

**Comment by schuylr** [comment]
@tinco Thanks for the suggestion. It definitely isn't just nginx-specific, as Apache also uses the `SIGWINCH` signal, noted in the same article I referenced. Maybe that helps my case. On the inverse side you're probably right, not all of the other runit services that a Docker developer might implement would probably respond to this specific signal.

Do you have any extra tips on how the wrapper script would look? Would I just make a new bash script that invoked `nginx` in the foreground and pointed the runit script to that wrapper? This might look good for posterity. I'll close this issue and re-open in passenger-docker as well so this can be referenced.
