### ISSUE TITLE
Passing environment vars to Cron

### ISSUE THREAD

**Issue by AleksMeshkov** [phusion/baseimage-docker#340]
I have a nodeJS app that is run by cron.
What I've figured out is that cron starts nodeJs script without passive env vars. See [this article](https://ypereirareis.github.io/blog/2016/02/29/docker-crontab-environment-variables/)

So is there any way to make cron work as expected without workarounds?

**Comment by hyperknot** [comment]
Baseimage has an amazing functionality especially for this, it creates a
special folder with env vars.

Look here:
https://github.com/phusion/baseimage-docker#environment-variable-dumps

**Comment by AleksMeshkov** [comment]
@hyperknot thank you very much!
