### ISSUE TITLE
Keyboard configuration

### ISSUE THREAD

**Issue by drgnkpr** [phusion/baseimage-docker#342]
Hi,

I'm trying to use kvm in a docker container. In the Dockerfile, I have:

```
FROM phusion/baseimage:0.9.19

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Install packages
RUN apt-get update -q && apt-get install -q -y qemu-kvm libvirt-bin python-libvirt libvirt-dev
```

However, during the installation, when setting up keyboard-configuration, it asks me to choose a country:

```
Setting up keyboard-configuration (1.108ubuntu15.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring keyboard-configuration
----------------------------------

The layout of keyboards varies per country, with some countries having multiple
common layouts. Please select the country of origin for the keyboard of this
computer.

Country of origin for the keyboard: 
```

It hangs after I input a number (29 for English (US)). This doesn't happen if I use ubuntu xenial image directly.

**Comment by grzpab** [comment]
@drgnkpr I hope you have found a solution on your own so far, however, for the future reference, if you want to skip the setup of the `keyboard-configuration` package, you can run:
```ENV DEBIAN_FRONTEND noninteractive```
This will skip the configuration part (which is not exactly what you might want to end up with).

Also, if you want to setup the keyboard, you can prepare you configuration file and move it to container like this (execute before the installation):
```COPY ./keyboard /etc/default/keyboard```

I hope it helps :)

**Comment by Theaxiom** [comment]
Thank you @grzpab for the workaround!

**Comment by johnyserpa** [comment]
Thanks!

I used this keyboard file and worked.

    # KEYBOARD CONFIGURATION FILE

    # Consult the keyboard(5) manual page.

    XKBMODEL="pc105"
    XKBLAYOUT="us"
    XKBVARIANT=""
    XKBOPTIONS=""

    BACKSPACE="guess"
