### ISSUE TITLE
CRON[246]: Cannot make/remove an entry for the specified session

### ISSUE THREAD

**Issue by AleksMeshkov** [phusion/baseimage-docker#345]
Hello! Have anyone faced this error?

```
root@014193c600e8:~/app# tail -f /var/log/cron.log
Oct 18 10:05:54 014193c600e8 crontab[171]: (root) LIST (root)
Oct 18 10:06:04 014193c600e8 crontab[191]: (root) BEGIN EDIT (root)
Oct 18 10:06:19 014193c600e8 crontab[191]: (root) REPLACE (root)
Oct 18 10:06:19 014193c600e8 crontab[191]: (root) END EDIT (root)
Oct 18 10:07:01 014193c600e8 CRON[246]: Cannot make/remove an entry for the specified session
```

my crontab consists of one line:

```*/1 * * * * . /etc/container_environment.sh;  node /root/app/dist/server/parser.js```

Docker command is: ```"/sbin/my_init","--","pm2","start","-x","/root/app/dist/server/app.js","--no-daemon"```

**Comment by AleksMeshkov** [comment]
Seems I got it working by including the following command in ```/etc/my_inid.d/setup_cron.sh```

```bash
#!/bin/bash
sed -i '/session    required     pam_loginuid.so/c\#session    required   pam_loginuid.so' /etc/pam.d/cron
#echo new cron into cron file
echo "*/1 * * * * . /etc/container_environment.sh;  node /root/app/dist/server/parser.js" >> mycron
#install new cron file
crontab mycron
rm mycron
```

**Comment by hyperknot** [comment]
I'm using 0.9.19 but this is not a problem. Are you using SSH? If PAM is the issue here, maybe it's related to SSH?

**Comment by AleksMeshkov** [comment]
Hey, @hyperknot. No, I don't use SSH over docker container. Just as always ```docker exec -ti ... ```

Is SSH is run by default there?

**Comment by hyperknot** [comment]
No, unless you enable it specially. So I'm surprised I didn't run into the same cron bug. 

I'm using /etc/crontab, not one of the user's crontab mechanisms.

Like:
```
echo '10 * * * * root /root/backup_rsync/backup.sh > /dev/null 2>&1' >> /etc/crontab
```

(take not of the root there, that's the difference between user's crontabs).

**Comment by AleksMeshkov** [comment]
Thank's for the tip man! I'll try your approach some day and write back to you.
