### ISSUE TITLE
my_init: port to C

### ISSUE THREAD

**Issue by mappu** [phusion/baseimage-docker#346]
Hi,

The `my_init` is a good solution. But, python is a large dependency that isn't necessary for all users of this container. I think it could reduce image size and memory usage if `my_init` was ported to C.

Thanks

**Comment by tinco** [comment]
You can find a `my_init` like project here: [dumb-init](https://github.com/Yelp/dumb-init). Since this image is expected to have Python and image size will not be significantly reduced by removing it, it is not likely Python will be dropped.

**Comment by FooBarWidget** [comment]
I welcome an effort to port it to C, but since I don't need it myself I won't be the one to do it.
