### ISSUE TITLE
Memory usage is 9.4 MO (not 6MO)

### ISSUE THREAD

**Issue by pascalandy** [phusion/baseimage-docker#355]
Hi I was curious to double check how much memory this container is using:

```
docker run -dit \
--name phusion \
phusion/baseimage:0.9.19

docker stats phusion

CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O             PIDS
phusion             0.01%               9.387 MiB / 1.954 GiB   0.47%               648 B / 648 B       782.3 kB / 73.73 kB   9
```

This is not aligned with:

> Baseimage-docker only consumes 6 MB RAM and is much powerful than Busybox or Alpine. 

Curious if you guys are seeing the same thing as I do.

**Comment by Theaxiom** [comment]
I'll have to look into this and get back to you, thanks!

**Comment by hyperknot** [comment]
With 0.10.0 it's actually 8.3 MB.

**Comment by Theaxiom** [comment]
@hyperknot We should probably update the README to reflect that.

**Comment by Theaxiom** [comment]
@hyperknot I see that you updated the README in PR #466 thanks!

**Comment by SwagDevOps** [comment]
RAM consumption depends IMHO of the RAM installed on the host itlself; as a result, it can not be an "universal truth".

**Comment by pascalandy** [comment]
I wasn't aware of this. How does it look on your system?

**Comment by SwagDevOps** [comment]
11MB with the following configuration: [2024881](https://www.linuxcounter.net/machine/2024881)
