### ISSUE TITLE
Seems network is broken on phusion/baseimage-docker

### ISSUE THREAD

**Issue by hesco** [phusion/baseimage-docker#357]
@FooBarWidget -- Thanks for the quick response.  Yes, I was coming to the same conclusion myself; and investigating that leaves me believing that the network itself seems broken.  

```
root@974b35d6effc:/# ip
bash: ip: command not found

root@974b35d6effc:/# ifconfig 
bash: ifconfig: command not found

root@974b35d6effc:/# less /etc/network/interfaces                                                                                                                        
/etc/network/interfaces: No such file or directory
```

**Comment by hyperknot** [comment]
Network is not broken, this is how Docker works. You can install the tools via apt-get if needed, but your main problem is with your host system.

**Comment by hesco** [comment]
Thank you, can you say more please about what about the host system needs to be fixed so that I have networking function on this container?

**Comment by hyperknot** [comment]
Probably not something you can fix, but a temporary problem with your
provider.

Write them a support ticket.

**Comment by hesco** [comment]
I am my provider.  I own the bare metal and rent rack space in a shared data center.  If this is to be resolved, it is left to me.

**Comment by hyperknot** [comment]
Try diagnosing your network with mtr, fping, use Google's DNS: 8.8.8.8 / 8.8.4.4. This is out of the scope of this issue, I also recommend asking for help on lowendtalk.com and https://www.reddit.com/r/sysadmin/.

**Comment by hesco** [comment]
thanks for the leads.  Fair enough, am closing this issue.

**Comment by hesco** [comment]
@hyperknot : thanks for the leads.  I used your advice to check out both mtr and fping.  Very nice.  Have added each of them to my network utilities manifest.  

I had been using `dns_args=$(weave dns-args)`to generate the `docker run` arguments used to configure the dns for the container.  I next experimented with adding `dns_additional_nameservers_open='--dns=8.8.8.8 --dns=8.8.4.4'` and settled on:  `dns_additional_nameservers='--dns=ns1.myprovider.com --dns=ns2.myprovider.com '`.  Either of those last two options worked to provide name resolution off the container.  

Appreciate the second set of eyes there.

**Comment by hyperknot** [comment]
Thanks, glad that it helped!
