### ISSUE TITLE
my_init exits with 0 on SIGINT after runit is started

### ISSUE THREAD

**Issue by jraby** [phusion/baseimage-docker#358]
Is it done on purpose that `my_init` calls `exit(2)` if it is interrupted before `runit`is started, but that it exits with 0 if it receives a `SIGINT` while waiting for `runit` to exit in `wait_for_runit_or_interrupt`

I've been trying to find a way to abort a container from inside, so that a container launched to run a batch job can exit with a non-zero exit code in case of job failure.

So far, the only way I've found to do it requires sending a SIGHUP to `runsvdir` from the finish script of a service and walking around a race conditions between `runsvdir` and the service's `runsv`.

A much simpler way would be to let `my_init` abort whenever it receives a SIGINT:

```
--- a/image/bin/my_init
+++ b/image/bin/my_init
@@ -238,11 +238,8 @@ def start_runit():
        return pid

 def wait_for_runit_or_interrupt(pid):
-       try:
-               status = waitpid_reap_other_children(pid)
-               return (True, status)
-       except KeyboardInterrupt:
-               return (False, None)
+       status = waitpid_reap_other_children(pid)
+       return (True, status)

 def shutdown_runit_services():
        debug("Begin shutting down runit services...")
```

This would let the `KeyboardInterrupt` bubble up to the exception handler around `main()`, all process get killed with a SIGTERM (with a timeout) and my_init exits with 2.

A service's finish script could simply call `os.kill(1, signal.SIGINT)` and be done with it if it needs to abort the container.

**Comment by Theaxiom** [comment]
Would you mind putting this in a PR and I will merge it in? Thanks!

**Comment by Theaxiom** [comment]
I have put this into a PR for review by the other team members. Thanks @jraby !
