### ISSUE TITLE
LANG is not set for RUN command in inherited container

### ISSUE THREAD

**Issue by wyzewyz** [phusion/baseimage-docker#359]
Here is a minimal reproduction of the problem:

```
$ cat Dockerfile
from phusion/baseimage:0.9.19

RUN echo my language is currently $LANG
$ docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM phusion/baseimage:0.9.19
 ---> c39664f3d4e5
Step 2 : RUN echo my language is currently $LANG
 ---> Running in d81e02ae0896
my language is currently
 ---> 21ed94395e2c
Removing intermediate container d81e02ae0896
Successfully built 21ed94395e2c
```

I *expect* the `LANG` variable to be some reasonable default value.  In fact [this code](https://github.com/phusion/baseimage-docker/blob/24b8bcebc85884ab3651a122f15c502a7066736c/image/prepare.sh#L39-L44) looks like it attempts to set the language to `en_US.UTF-8`, but it obviously doesn't actually set it in this case.  I'm thinking this is a problem with the image, but just in case, my host is:

```
$ docker --version
Docker version 1.12.6, build 78d1802
$ cat /etc/issue
Debian GNU/Linux 8 \n \l
```

Empty `LANG` causes subtle breakages like [this one](https://github.com/jamespacileo/django-pure-pagination/issues/40) (TLDR:  Some random Python package's `setup.py` uses `readme.read()` without setting an encoding to set its long description for package management purposes, which works 99% of the time, but when the stars align so that `README.md` has non-ASCII UTF-8 and `LANG` is empty, you will not go to space today.)

**Comment by hyperknot** [comment]
During build you only have access to the variables which were defined in the Docker file.
During run you actually have access to the ones set by the shell / login mechanism.

Just try `RUN env` or running `env` via docker run / exec.

**Comment by Theaxiom** [comment]
I believe encoding fixed by a recent pull request, we will be tagging a new release in the days to come. Thank you!
