### ISSUE TITLE
Are this boxes available to use with Vagrant?

### ISSUE THREAD

**Issue by vonpupp** [phusion/baseimage-docker#360]
Hello,

I would like to be able to run ubuntu 16.04 within a container with systemd using Vagrant. There are a couple of boxes published on Atlas but they have problem with systemd + docker.

I wonder if your box is also available on Atlas, and if not, would it play nicely with systemd + docker?

Thank you.

**Comment by Theaxiom** [comment]
@vonpupp I do not have any experience with the Docker Vagrant provider, if you do get this working in Vagrant, please let us know, submit your PR and we will get it up onto Atlas! Thank you!
