### ISSUE TITLE
Windows build fail when adding files into /etc/my_init.d/

### ISSUE THREAD

**Issue by lnyousif** [phusion/baseimage-docker#364]
I encountered a docker build error when I was working on my Windows 10 docker instance after I added this to the webapp DockerFile

```
ADD post-run-web.sh /etc/my_init.d/99_post-run-web.sh
RUN chmod +x /etc/my_init.d/99_post-run-web.sh
RUN chown root:root /etc/my_init.d/99_post-run-web.sh
```

The shell script was failing no matter what I put there, even if it was a just echo command. 

docker build failed with this message

`/etc/my_init.d/99_post-run-web.sh failed with status 127`

After researching and researching I was not able to find any solution that fixed the issue for me, most of the similar issues were appearing on OS other than Windows .

So I pulled the code from my Windows machine and ran the build from a Mac, the build worked fine with no issue and the application .

My problem is already solved but I wanted the team to be aware.

Mac Docker info
```
Version 1.13.1 (15353)
Channel: Stable
94675c5a76
```

Windows Docker Info
```
Version 1.13.1 (10072)
Channel: Stable
94675c5
```

**Comment by lnyousif** [comment]
@FooBarWidget I noticed that you are active on the issue board and wanted you to be aware of this.  so wanted your feedback, this could be a docker issue but it appeared on the image I am using  `FROM phusion/passenger-ruby23`

**Comment by hyperknot** [comment]
I guess it's very likely to be something with Docker for Windows. The Mac
client is extremely buggy, and I have to use the old 1.12.6 version for
example. Try downgrading your client to 1.12.6.

**Comment by lnyousif** [comment]
OK I will post this in Docker issues too. Thanks @hyperknot , will keep this updated

**Comment by Theaxiom** [comment]
@lnyousif Did you find a workaround, or is this issue still persisting?

**Comment by lnyousif** [comment]
@Theaxiom still happening and no answer from docker team, I just build the image on a Mac and deploy it.

**Comment by Theaxiom** [comment]
Thank you @lnyousif for the feedback, I will close this for now. If you do happen to find the solution, please come back and post your results. Thank you!
