### ISSUE TITLE
Update passenger-nodejs image to new repo and node 7.7.x

### ISSUE THREAD

**Issue by hamid-elaosta** [phusion/baseimage-docker#365]
The node image says it uses the Chris Lea PPA (https://launchpad.net/~chris-lea/+archive/ubuntu/node.js/) which doesn't appear to be true, as I can apt upgrade it to 4.x, however, it should move to the current repo (See: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

**Comment by Theaxiom** [comment]
Is this related to baseimage-docker or to the phusion-passenger image?

**Comment by hamid-elaosta** [comment]
The latter, apologies if seems I've raised if against the wrong repository.

**Comment by Theaxiom** [comment]
No problem. :)
