### ISSUE TITLE
`armhf` support.

### ISSUE THREAD

**Issue by esmail** [phusion/baseimage-docker#366]
Just wanted to let you know I was able to get this working on `armhf` devices with [very little modification](https://github.com/phusion/baseimage-docker/compare/master...kobotoolbox:armhf). I can PR it in if you want to make e.g. an `armhf` branch.

For context, this was to get our `baseimage-docker`-based [`kobo-docker`](https://github.com/kobotoolbox/kobo-docker) project running on Rasberry Pis.

**Comment by Theaxiom** [comment]
I'm glad to hear that baseimage-docker is being used on Raspberry Pi! As far as actively maintaining an `armhf` branch, if that is something you would like to contribute to, you are more than welcome to submit your new branch! Thank you!

**Comment by esmail** [comment]
@Theaxiom, I don't have permissions to create a new branch on your repo. Regarding maintaining the branch, I've been thinking of setting up Jenkins on a Pi to automate image rebuilding and updating my branch, but there are no immediate plans for this.

**Comment by Theaxiom** [comment]
@esmail You can submit your branch via a PR. When you get the CI setup for that branch, definitely let us know.

**Comment by esmail** [comment]
A PR into what branch, `master`?

![screenshot from 2017-03-20 15-01-28](https://cloud.githubusercontent.com/assets/2295939/24116760/2c50eb32-0d7e-11e7-8bc9-8d20f5fc3bfe.png)

**Comment by Theaxiom** [comment]
I can change the banch after you submit your PR.

**Comment by esmail** [comment]
Interesting. I wasn't aware of that.

**Comment by esmail** [comment]
Initial PR #368 submitted for other `armhf` users with the caveat that I have no immediate plans to actively maintain it.

**Comment by Theaxiom** [comment]
Thank you!
