### ISSUE TITLE
Push `master` to Docker Hub for bleeding edge

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#386]
Some people want the updates ASAP.

**Comment by Theaxiom** [comment]
Abandoning `next` branch, but will push `master` to DockerHub for bleeding edge.

**Comment by Theaxiom** [comment]
Just an update, I will be setting this up this week. I haven't forgot. :)

**Comment by hyperknot** [comment]
We came up with the following upon a discussion:

1. Each release will be automatically published based on a Git tag.
2. The latest release version will be published as `stable` as well.
3. The latest master version will be published as `master`.

**Comment by Theaxiom** [comment]
Correction regarding the comment above:

3. The latest master version will be published as `latest`

**Comment by hyperknot** [comment]
Sure, of course.

**Comment by hyperknot** [comment]
@Theaxiom any updates on this?

The most important thing I'd like to say is that `latest` should be used for the lastest stable version. There are thousands of Github starts in total for projects which depend on `baseimage:latest`, one example I've just run into the other day was ELK docker:
https://github.com/spujadas/elk-docker/blob/master/Dockerfile

So I strongly believe that both `phusion/baseimage` and `phusion/baseimage:latest` should always point to the latest stable version, that's how the baseimage ecosystem is working.

Master should be pushed to `next`, I think.

**Comment by Theaxiom** [comment]
@hyperknot If you want to setup the CI to push the image up automatically, etc -- feel free to do so. I haven't had much time to work with it recently, you should have access to Travis-CI and if not, let me know.

**Comment by hyperknot** [comment]
@Theaxiom I'll go on chat to discuss it. I personally have experience with CircleCI, but here we are using your personal Travis instances, aren't we?

**Comment by Theaxiom** [comment]
Travis-CI is not mine, it is a public product like Circle-CI. Phusion already had Travis-CI setup previously. You should be able to access the Travis-CI settings on the website since you are an admin on the repo.

**Comment by Theaxiom** [comment]
What do you see when you login to https://travis-ci.org/ <https://travis-ci.org/> ?
