### ISSUE TITLE
Bug in my_init.shutdown_runit_services

### ISSUE THREAD

**Issue by tgranqvist** [phusion/baseimage-docker#391]
Is there a bug in my_init.shutdown_runit_services, row 250?

When running this: `docker run --rm -t -i phusion/baseimage:<VERSION> /sbin/my_init -- bash -l` as per you documentation, and exiting the shell (with `exit`), I get the following error message:

![bild](https://cloud.githubusercontent.com/assets/24589919/24995236/cc8d02e6-2036-11e7-8fee-7ed995d4cb1d.png)

It complains about row 250, which is `os.system("/usr/bin/sv -w %d down /etc/service/*", KILL_PROCESS_TIMEOUT)`. As the error message says, the os.system call takes only one parameter and here it's given two. I guess it's a mistake with string formatting, because if I correct the line to be `os.system("/usr/bin/sv -w %d down /etc/service/*" %KILL_PROCESS_TIMEOUT)` then it works.

**Comment by Theaxiom** [comment]
That was just touched a few days ago: https://github.com/phusion/baseimage-docker/pull/388

**Comment by Theaxiom** [comment]
Would you mind submitting a PR with your update? Please and thank you! 👍

**Comment by Theaxiom** [comment]
I appreciate you fixing this in #392

I will get a new release out here in then next day.

**Comment by Theaxiom** [comment]
Looks like a package got deprecated, https://travis-ci.org/phusion/baseimage-docker/builds/221641732#L1102

Issue #394 is related

**Comment by Theaxiom** [comment]
Thanks for your contribution. 👍
