### ISSUE TITLE
curl inside  phusion/baseimage:latest

### ISSUE THREAD

**Issue by jimisan** [phusion/baseimage-docker#397]
curl https://google.com --verbose
* Rebuilt URL to: https://google.com/
*   Trying 209.85.233.100...
* Connected to google.com (209.85.233.100) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: Error in the pull function.
* Closing connection 0
curl: (35) gnutls_handshake() failed: Error in the pull function.

**Comment by hyperknot** [comment]
Cannot reproduce:

```
docker run --rm -it phusion/baseimage:latest bash -l
root@95e654fffd06:/# curl https://google.com --verbose
* Rebuilt URL to: https://google.com/
*   Trying 216.58.209.206...
* Connected to google.com (216.58.209.206) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.google.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=Mountain View,O=Google Inc,CN=*.google.com
* 	 start date: Fri, 21 Apr 2017 08:25:00 GMT
* 	 expire date: Fri, 14 Jul 2017 08:25:00 GMT
* 	 issuer: C=US,O=Google Inc,CN=Google Internet Authority G2
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
```

**Comment by jimisan** [comment]
It was not image issue, sorry. It' caused mtu difference between host and docker networks. Some cloud providers use vxlan over vpn, that shrinks mtu size on vm's host

solution, anyway: https://github.com/moby/moby/issues/22297#issuecomment-242934050
