### ISSUE TITLE
TypeError when stopping/exiting container [0.9.21]

### ISSUE THREAD

**Issue by csdev** [phusion/baseimage-docker#398]
Run any one-off command inside the container that exits successfully, for example:
```
docker run phusion/baseimage:0.9.21 /sbin/my_init -- echo "Hello world!"
```

The container exits with status 1 and an error traceback:
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
*** Running echo Hello world!...
Hello world!
*** echo exited with status 0.
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 314, in main
    sys.exit(exit_status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/my_init", line 353, in <module>
    main(args)
  File "/sbin/my_init", line 317, in main
    shutdown_runit_services()
  File "/sbin/my_init", line 250, in shutdown_runit_services
    os.system("/usr/bin/sv -w %d down /etc/service/*", KILL_PROCESS_TIMEOUT)
TypeError: system() takes at most 1 argument (2 given)
```

**Comment by lucacri** [comment]
Same here

**Comment by Theaxiom** [comment]
That command should be the following:
`os.system("/usr/bin/sv -w %d down /etc/service/*" % KILL_PROCESS_TIMEOUT)`

It was fixed already with this PR: https://github.com/phusion/baseimage-docker/pull/392

Please try using a build from master branch, I will work today to get `master` branch building a `latest` image on Docker hub; also I will work to get a release out which includes this fix.

**Comment by Theaxiom** [comment]
This is a duplicate of #391

**Comment by lfittl** [comment]
@Theaxiom Ping re: a new release, I just ran into this as well.

**Comment by Theaxiom** [comment]
Thanks for the reminder, I will get it out within the next few hours. :)

**Comment by Theaxiom** [comment]
Release 0.9.22 released: https://github.com/phusion/baseimage-docker/releases/tag/0.9.22

**Comment by nberrios** [comment]
@Theaxiom Verified that the new release solves the problem. Maybe we can update latest tag while we are at it? :)

**Comment by Theaxiom** [comment]
@nberrios latest should already be updated with latest version
