### ISSUE TITLE
Remove bd_build

### ISSUE THREAD

**Issue by hyperknot** [phusion/baseimage-docker#405]
Is there any reason why we are preserving the bd_build folder or bits from that folder here?

https://github.com/phusion/baseimage-docker/blob/7f77348a6b244bfaef3c4304c92d8f0905d7137b/image/cleanup.sh

I'd just recommend `rm -rf /bd_build` in cleanup.

**Comment by Theaxiom** [comment]
Yes, I will have to check the history but it was recommended. I will link the related issue when I find it.

**Comment by hyperknot** [comment]
I'm running with `rm -rf /bd_build` for 2 years now and no issues so far.

**Comment by Theaxiom** [comment]
Great, would you mind submitting a PR @hyperknot ?

**Comment by hyperknot** [comment]
Sure, I'll do.
