### ISSUE TITLE
shutdown_runit_services error on exiting interactive container

### ISSUE THREAD

**Issue by multidis** [phusion/baseimage-docker#408]
Dockerfile:

    FROM phusion/baseimage:0.9.21
    CMD ["/sbin/my_init"]
    EXPOSE 8080

Build and run interactively:

    docker build -t baseimg:latest --rm .
    docker run --rm -t -i baseimg:latest /sbin/my_init -- bash -l

On `exit`, the following exception trace is returned:

> logout
*** bash exited with status 0.
*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 314, in main
    sys.exit(exit_status)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/my_init", line 353, in <module>
    main(args)
  File "/sbin/my_init", line 317, in main
    shutdown_runit_services()
  File "/sbin/my_init", line 250, in shutdown_runit_services
    os.system("/usr/bin/sv -w %d down /etc/service/*", KILL_PROCESS_TIMEOUT)
TypeError: system() takes at most 1 argument (2 given)

**Comment by Theaxiom** [comment]
This is a duplicate which will be fixed in the next release. I will work on getting a new release out this week.
