### ISSUE TITLE
Modifying /etc/service/syslog-ng/run

### ISSUE THREAD

**Issue by yangmillstheory** [phusion/baseimage-docker#413]
Hi,

We recently moved from running a single container (service) per EC2 host, from running multiple containers on a single host. These services log to the same file (in the container, it's in `/var/www/my-service/service.log`). This presents collision issues when mounting the file back onto the host.

For a solution, I was thinking of namespacing the log file with the contents of `/etc/hostname`. To do this, I think I'd have to do a runtime substitution in `/etc/service/syslog-ng/run`. Is there a better way of doing this than manually overriding `/etc/service/syslog-ng/run` at runtime?

**Comment by yangmillstheory** [comment]
Found a solution. Going to use `${HOST}` in `file` directives in syslog config files.

**Comment by Theaxiom** [comment]
Thanks @yangmillstheory for updating this issue with a workaround. 👍
