### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by lazercorn** [phusion/baseimage-docker#414]
I'm seeing quite a lot of Issues (19 at the time of this post) so logically the question to ask is, is this production ready?

**Comment by Theaxiom** [comment]
Most of the open issues are low hanging fruit. baseimage has been around for several years and is quite stable, it is being used by thousands of users currently, it is also one of the most widely used Docker images in existence.

**Comment by Theaxiom** [comment]
Is there a particular issue that is open which concerns you? As can you see, there are 235 closed issues.

**Comment by lazercorn** [comment]
@Theaxiom Nothing in particular. Was just wondering.

Just another question out of curiosity, if all the problems that baseimage-docker solves are so important, then is there any reason why Docker hasn't included it in their scratch image yet?

**Comment by Theaxiom** [comment]
Joseph,

That is an excellent question. Baseimage is an abstract layer above scratch
that sets a baseline for you to build upon. It is definitely not a one size
fits all solution, however if you have ever had to bundle complex
applications into a docker image you would understand why and how baseimage
is helpful. The key component is the ability to perform a multitude of
tasks upon container startup, as well as perform maintenance while the
container is running. Not to mention the fact that baseimage enables you to
run multiple processes and services simultaneously in the same container,
which aids in creating truly self contained applications.

I hope that answers your question, please let me know if you have anymore.
😀

**Comment by FooBarWidget** [comment]
Solomon Shykes, founder of Docker Inc, acknowledged the PID 1 zombie reaping problem in a Hacker News comment 2 years ago. I didn't notice any progress towards a solution inside Docker... [until today](https://news.ycombinator.com/item?id=14525872).

Apparently Docker added the `--init` flag to `docker run` some time ago.

**Comment by hyperknot** [comment]
Now we only need to wait about 6 months till the current version can be
considered kind of stable.

**Comment by hyperknot** [comment]
OK, they just included tini init since Docker 1.13:
https://github.com/krallin/tini/issues/81

I don't think it affects us, but it can help users run single-service containers without including an init system in the image. Just run docker run --init redis, etc. and then tini takes care of single-service PID 1 problems.

**Comment by jhabdas** [comment]
@lazercorn 19 issues is pretty low given the number of stargazers. I used this image for over a year along with passenger serve a Jekyll site and never once had an issue. Of course my use case was rather simple. Your idea of production ready might be different than the others.

**Comment by kamermans** [comment]
I know this thread is already closed, but I would also give `phusion/baseimage` a vote of confidence - I have been running hundreds of containers with terabytes of RAM based on this image in production for two years now, serving hundreds of billions of requests, and no issues have yet surfaced that pointed at a problem in the `baseimage`.

We have added a number of new features to our base image, like `/etc/my_cron.d`, a configurable startup delay, inclusion of the `runit` binaries `svwaitup` and `svwaitdown` and other features that we find useful.  @hyperknot (or whoever the maintainer is) - I'm happy to submit PRs of you are interested.

**Comment by hyperknot** [comment]
@kamermans thanks for the great feedback! 
If you are thinking about turning any of your changes into PRs, please go ahead, I cannot promise they'll all be merged, but even as an open PR they'd provide great value to everyone who can find them here.

**Comment by Theaxiom** [comment]
@kamerans the praise is very much appreciated!

I agree with @hyperknot -- any PR's would be greatly appreciated!

Thanks again!

**Comment by BunnyHolder** [comment]
Because of this image, we could migrate from One Monolith for all Clients to Monolith per Client. So now we can deploy on-site. And we have made some cool applications for that.
