### ISSUE TITLE
please consider keep all files in /usr/share/zoneinfo 

### ISSUE THREAD

**Issue by cooka** [phusion/baseimage-docker#415]
I tried to change the default timezone to CST, but  either `modify /etc/timezone ` or  `set TZ env` failed.
finally, mount and override  /etc/localtime file (default to be Etc/UTC) works.

but there is only  one "Etc/UTC" file  under  /usr/share/zoneinfo, maybe this folder to be kept as is? 
/usr/share/zoneinfo  is 3.5M in total, and 1.5M zipped. 

or, is there a more gentle way to set different timezone?

**Comment by hyperknot** [comment]
Generally it's considered a bad practice to use anything else on server
other than UTC. The reason is that daylight changes can trigger double cron
jobs or skip one, or possibly cause other bugs.

In Ubuntu 16.04 you should be using these commands to set the timezone:

apt-get install dbus

timedatectl set-local-rtc 0
timedatectl set-ntp 1
timedatectl set-timezone UTC

I'm not sure about setting timezones in containers, I never touch time in
docker.

**Comment by kingdonb** [comment]
You can set time zones in containers, but that's about all you can do...

https://blog.jessfraz.com/post/two-objects-not-namespaced-linux-kernel/

Time is one of the (at least?) two things that are still currently not namespaced by the Linux Kernel.  So, if you want your container to have a particular time zone, you can either set it at runtime without any privileges by using the "TZ" environment variable, the most gentle way that can work at runtime or anytime on a per-process basis...

Or you can set it system-wide which it looks like you were trying to do (inside of the container) by setting up /etc/localtime with a copy or a link to your correct time-zone from /usr/share/zoneinfo/ -- this is the preferred way to make this change permanent on a system, although it can still be overriden by the TZ variable.

If /usr/share/zoneinfo is empty in the baseimage, it might be a problem!  If you're building something from baseimage for yourself and you know what timezone you want it to be in, you can just copy the correct zoneinfo from your host system and make sure it gets included in the container in your Dockerfile during your (downstream) docker build.

@hyperknot is correct about the things that can go wrong when you set a global timezone, you might not care about this at all, I personally prefer to set the time zone on my servers and I don't care if a job gets skipped or repeating -- they are all running several times per day anyway.

You do not need to change the hardware clock or use timedatectl.  I do not know what will happen if you do inside of a container, but the article I linked suggests at least that if it does work, it will also affect the host system, and that's bad.

**Comment by kingdonb** [comment]
@cooka I didn't read carefully, it looks like you said you did try setting the TZ environment variable but it failed.  Is that right?

In my containers I am doing:

```
RUN  cp /usr/share/zoneinfo/America/New_York /etc/localtime \
    && echo "America/New_York" > /etc/timezone
```

and that works for me, but they are not Baseimage, this is actually a Jenkins server built `FROM jenkins:2.46.2`

**Comment by kingdonb** [comment]
@cooka You might just need to `apt-get install tzdata` -- I was searching for where zoneinfo is supposed to come from, and I found reports that it was not installed by default anymore in Ubuntu 16.04.  I don't see that it's a part of baseimage at all, so it's probably missing from your container.

**Comment by cooka** [comment]
@hyperknot without tzdata installed or related files presented in `/usr/share/zoneinfo` , `timedatectl ` would not work.

@kingdonb set `TZ` environment doesn't always work, in container. 
and without `tzdata` installed(in baseimage), we can't `cp` or `ln -s` other timezone file to `/etc/localtime` (like in jenkins image) . 

so, add `tzdata` package or add  `/usr/share/zoneinfo` files would be an easier way to set different timezone.

**Comment by hyperknot** [comment]
So feel free to add them in your own child image.

**Comment by hyperknot** [comment]
Thank you for your research about timezone. Since what you are saying is a simple solution, and highly specific to your environment, I recommend you to simple implement it in a child image.

**Comment by kingdonb** [comment]
@cooka - This dockerfile worked great for me

`Dockerfile`
```
FROM phusion/baseimage

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN apt update && apt install -y tzdata && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV TZ America/New_York
```

**Comment by kingdonb** [comment]
For posterity, this Dockerfile, copying /usr/share/zoneinfo by hand out of a MacOS (or probably also Ubuntu) build host, into the working directory as shown below, also works.  You do not need to install tzdata or set environment variables to get consistent local time.

```Dockerfile
FROM phusion/baseimage

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# cp /usr/share/zoneinfo/America/New_York ./New_York
COPY New_York /etc/localtime
RUN echo "America/New_York" > /etc/timezone
```
