### ISSUE TITLE
Move to systemd for service managment

### ISSUE THREAD

**Issue by BunnyHolder** [phusion/baseimage-docker#416]
All new packages support systemd service managment.

**Comment by kingdonb** [comment]
@BunnyHolder Did you change your mind?

The docs make the case that Runit is a better init for containers than upstart, but I don't know about systemd.  I think I have heard that systemd can be used inside of a container.  I don't know the trade-offs of that, but it's definitely a boon that every package in 16.04+ will already come with systemd init configuration out of the box.

Then again, if there's a complex dependency ordering maybe those services shouldn't be running inside of a single container, and your service orchestration can happen somewhere else (like depending on K8S health and readiness checks.)

**Comment by BunnyHolder** [comment]
@kingdonb Mostly no. Systemd is a go.

But I saw how this container works and actually I liked it.
