### ISSUE TITLE
my_init not exit just like waiting something

### ISSUE THREAD

**Issue by jacknlliu** [phusion/baseimage-docker#422]
I use entry 
```
ENTRYPOINT ["/sbin/my_init", "--", "setuser", "localuser", "entrypoint.sh"]
CMD ["bash"]
```
but the container can not exit just wait something like the following picture,
![screenshot from 2017-06-20 11-14-38](https://user-images.githubusercontent.com/6220143/27315119-509aed52-55aa-11e7-96c7-7dac613cf15f.png)

**Comment by jacknlliu** [comment]
In addition,  `docker stop <container_id>` and `docker kill <container_id>` also can not exit the container.

**Comment by hyperknot** [comment]
i guess you have some custom service stuck or not reacting to signals.

**Comment by jacknlliu** [comment]
@hyperknot  but if I did not use `my_init`, everything worked well. And only ssh service in this image. Can I use `my_init`  find what makes that?

**Comment by hyperknot** [comment]
of course, without my_init there are no runit services running.

with my_init try to stop your runit services one by one. start with ssh

**Comment by jacknlliu** [comment]
@hyperknot but it seems that  `my_init`  did not stop it. Will `my_init` keep waiting? If this is true, how we stop my container with `my_init`?

**Comment by jacknlliu** [comment]
A issue caused by docker storage.
