### ISSUE TITLE
Service start in runit or my_init?

### ISSUE THREAD

**Issue by vishal24tuniki** [phusion/baseimage-docker#426]
Hi,

I'm trying to use phusion/baseimage-docker but i have few questions that need to be clarified.

Let's say my service is `python /opt/app.py`
Do i start my service by adding it in `/etc/service/myapp/run` or `/etc/my_init.d/myapp.sh`. Though i feel the documentation suggests the former, it isn't pretty clear to me what is the use of my_init if the services are to be run using runit. Is `/etc/my_init.d` only to run some basic scripts and not processes/ services?

1) On the assumption that if my services are run via runit, do they start at boot time? And also i want to configure [monit](https://mmonit.com/monit/) for monitoring my applications (restart on crash, mail configurations when load avg > 1 etc). Will it conflict with the functionality of runit as both are trying to do the same thing (restarting apps on crash) ? And final question does runit use systemd?

2) On the assumption that runit is optional and all my services can be started via my_init, i guess using monit would work absolutely fine. Please confirm

**Comment by hyperknot** [comment]
Use runit to run services / apps. My init uses runit to run them. Let runit
manage restarts.

I'm not using monit but I'm sure you can put it in a monitor only mode
where it doesn't manage restarts, just monitors.

**Comment by vishal24tuniki** [comment]
@hyperknot, Just correct me that these are the possible ways i can configure my container

1) Place my service in `/etc/service/myapp/run` and use monit to monitor without monit's restart functionalities and do **NOT** configure anything in `/etc/my_init.d`
- Doing this would run my services at container bootup ?

2) Place my service in `/etc/my_init.d/myapp.sh` and do **NOT** create anything like `/etc/service/myapp/run`.
- According to what you said my_init uses runit to run them. Does this mean, the service restarts on crashes it also managed (what runit offers) ? In case the restarts is not managed, i can use monit to do the same here

I don't think there exists a case where you put same script in both `/etc/service` and `/etc/my_init.d`. If not why do we have 2 ways. How are they different in terms of result

**Comment by hyperknot** [comment]
1. Is the right way
2. I believe should only be used for short configuration steps, not long
running services. Thus mkdir -p /data or something should go in init.d but
not a long process.
