### ISSUE TITLE
Javascript Date gives wrong Timezone in Karma test

### ISSUE THREAD

**Issue by andyfoundi** [phusion/baseimage-docker#428]
I have encounter the following problem after updating 0.9.19 to the latest. However, when I roll back to 0.9.21, the problem goes away. In other words, the problem seem to happen between 0.9.21 and 0.9.22.

See: [Javascript Date gives wrong Timezone in Karma test](https://stackoverflow.com/questions/45169838/javascript-date-gives-wrong-timezone-in-karma-test)

-------

Somehow after a Docker image rebuild, I started having problems with javascript timezone problem. It used to work, but after a Docker image update, somehow the resulting Date object does not obey the TZ setting anymore. As the result, our timezone depending Date string formatting tests are failing.

# in the tests
```
console.log(new Date("2016-04-01T00:00:00.000000+00:00"));
// It is very strange it says (Asia) at the end.
// In fact, it will say whatever I put in TZ
Fri Apr 01 2016 00:00:00 GMT+0000 (Asia)

# in Chrome developer tool
console.log(new Date());
Fri Apr 01 2016 08:00:00 GMT+0800 (CST)
```
# gulpfile.js

```
gulp.task('test', ['_set_tpe_timezone'], runKarmaWebpackTests);
gulp.task('_set_tpe_timezone', function() {
  gutil.log('Setting timezone TZ = Asia/Taipei');
  process.env.TZ = 'Asia/Taipei';
  return;
});
```
I am using the following setup to run javascript tests:

- Gulp + Karma
- inside a Docker container
- In gulpfile, execute the following setting before each test process.env.TZ = 'Asia/Taipei';
- using headless Chrome 59
- cat /etc/timezone = Etc/UTC

**Comment by hyperknot** [comment]
Can you give minimal instructions about how to replicate the issue. Exactly what kind of commands do you run to have this appear? 

Do I understand it right that it wasn't present on 0.9.21 but it is present on 0.9.22?

**Comment by andyfoundi** [comment]
I could reproduce the bug with the following setup with version 0.9.22 but not 0.9.21.
Note the output date string is incorrect in the `test.spec.js`

# Dockerfile
```
FROM phusion/baseimage:0.9.22

RUN curl -s https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install --no-install-recommends -y google-chrome-stable
RUN apt-get install -y npm nodejs-legacy
RUN npm install karma jasmine karma-jasmine  karma-chrome-launcher gulp
COPY karma.conf.js /
COPY test.spec.js /
COPY gulpfile.js /
CMD ./node_modules/gulp/bin/gulp.js
```

# gulpfile.js
```
var gulp = require('gulp');
var KarmaServer = require('karma').Server;

gulp.task('default', ['set_timezone'], runTest);
gulp.task('set_timezone', function() {
  process.env.TZ = 'Asia/Taipei';
});
function runTest() {
  new KarmaServer({
    configFile: '/karma.conf.js',
    singleRun: true
  }).start();
}
```

# karma.conf.js
```
module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: [
      'test.spec.js'
    ],

    browsers: ['ChromeHeadless'],
    customLaunchers: {
      ChromeHeadless: {
        base: 'Chrome',
        flags: [
          '--no-sandbox',
          '--headless',
          '--disable-gpu',
          ' --remote-debugging-port=9222',
        ]
      }
    }
  });
};
```

# test.spec.js
```
describe('Date', function() {
  it('sets dates in wrong timezone', function() {
    var date = new Date('2016-04-01T00:00:00.000000+00:00');
    var dateString = '' + date;

    // dateString = 'Fri Apr 01 2016 00:00:00 GMT+0000 (Asia)' in 0.9.22, which is wrong
    expect(dateString).toEqual('Fri Apr 01 2016 08:00:00 GMT+0800 (CST)');
  });
});
```

**Comment by hyperknot** [comment]
I'll have a look if it's baseimage related or just some package got updated
in Ubuntu.

**Comment by richard-scott** [comment]
With phusion/baseimage:0.10.0 I've had to add tzdata to get the /usr/share/zoneinfo folders.

**Comment by richard-scott** [comment]
I never looked on previous versions tho ;-)

**Comment by hyperknot** [comment]
@andyfoundi I could reproduce your issue, but it is not Baseimage related, at least it's behaving the same in 0.9.22 and 0.9.21. My best guess is that something changed a newer version of Chrome or one of the packages you are installing.

If you do figure out what caused this, please report back.

**Comment by hyperknot** [comment]
@richard-scott it hasn't been installed in 0.9.22 either. Is it needed for some purpose?
I know it's only 166 kB, so we should probably add it without thinking too hard about it, but just out of interest, what is it needed for?

**Comment by andyfoundi** [comment]
@hyperknot I spent hours but only could only identify the problem from the base image version. The packages installed should be the same as shown in the Dockerfile. I am now fixing the version at 0.9.21, and I will report the cause if I find out why. I will be interested in trying the solution from @richard-scott and upgrade the version.

Thanks

**Comment by hyperknot** [comment]
@andyfoundi, even in 0.9.21 the issue is present. You just had some older packages which are gone by now I believe.
