### ISSUE TITLE
How based on this images, to build a minimum java running images

### ISSUE THREAD

**Issue by penhauer-xiao** [phusion/baseimage-docker#430]
How based on this images, to build a minimum java running images; simple to build out the images is too large, java8 greater than 600M based on this images

**Comment by kingdonb** [comment]
Did you try flattening the image?

jdk8 on openjdk repo is 295M, baseimage is 225M, you should be able to put them together in less than 600M.

Post your Dockerfile here please and I will give you some suggestions about what you can trim to make it smaller!

**Comment by kingdonb** [comment]
@penhauer-xiao please post more information, so we can help with your issue.

**Comment by penhauer-xiao** [comment]
@kingdonb  Very thank you very much, the problem is solved. Java virtual machine compressed to about 400M.   Perhaps consider Alpine Linux

**Comment by kingdonb** [comment]
We've had others suggesting that we should support Alpine Linux.  I'll make a note.

The next release should be a bit smaller, as we've stopped building the PAM packages.  I'm not sure how much that adds to the release bundle size, but it's probably non-trivial amount.
