### ISSUE TITLE
#432 incompletely parameterized my_init.d

### ISSUE THREAD

**Issue by kingdonb** [phusion/baseimage-docker#434]
#432 - the string "my_init.d" occurs in other places than `my_init` and most notably, apparently, in the `image/services/sshd/sshd.sh` file, where users changing the value will cause SSH keys to not get regenerated.

https://unix.stackexchange.com/questions/62333/setting-a-shell-variable-in-a-null-coalescing-fashion

Looks like bash has a "null coalesce" style operator

**Comment by hyperknot** [comment]
@kingdonb I think that variable is used in _so_ many places now, that it'd be impossible to change it to anything. Now not just `sshd` but `syslog-ng` also depends on that folder.

I'm actually leaning towards reverting that patch, as it's break so many things if someone would try to use it. Are you actually using that in production?

**Comment by samip5** [comment]
Stale issue, closing.
