### ISSUE TITLE
Syslog messages are not forwarded

### ISSUE THREAD

**Issue by davidhiendl** [phusion/baseimage-docker#437]
I've experiencing a problem with several of my containers based on this image:
When my applications log to syslog their output is missing from docker logs. Upon investigation I noticed that their output makes it into `/var/log/syslog` inside the container but it is not forwarded via the syslog-forward service to docker.

This happens despite the syslog-forwarder running. Restarting this service by killing it fixes this problem temporarily.

Wouldn't it be better to eliminate the syslog tail completely by configuring syslog-ng to log to `/dev/stdout` which will then be picked up by docker? I don't see any negative effects in doing so and on the plus side it might eliminate the need for logrotate and the log messages are not written to disk inside the container anymore.

Here is the working example configuration I'm using at the moment:
```
@version: 3.5
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"

options { chain_hostnames(off); flush_lines(0); use_dns(no); use_fqdn(no);
          owner("root"); group("adm"); perm(0640); stats_freq(0);
          bad_hostname("^gconfd$");
};

source s_src {
       unix-dgram("/dev/log");
       internal();
};

destination d_stdout { pipe("/dev/stdout"); };
log { source(s_src); destination(d_stdout); };

@include "/etc/syslog-ng/conf.d/*.conf"
```

**Comment by Theaxiom** [comment]
I can't think of any negative side-effects regarding your proposed change, what about @kingdonb or @hyperknot? Any foreseen issues?

**Comment by hyperknot** [comment]
OK, this seems quite a big change, but not necessarily bad. It's almost like removing syslog-ng entirely. There wouldn't be anything logged to /var/log anymore, but everything would go to Docker log.

The biggest problem with this I believe:
- From inside the container there is no way to read the logs.
- The logs are no more separated, but mixed into one stream.

This might not be bad though, as normally in a baseimage container the only service regularly logging is cron.

So it's almost like asking if we need syslog-ng at all. Opinions?

**Comment by hyperknot** [comment]
@davidhiendl would it be possible to keep the existing logs in /var/log AND directly write to /dev/stdout? That way we can remove the forwarder service.

**Comment by davidhiendl** [comment]
@hyperknot Yes, I believe you can specify multiple outputs for syslog-ng. If you look into the current syslog-ng config at `/etc/syslog-ng/syslog-ng.conf` you will see multiple filter -> output chains. If you leave those instead of removing them and simply add the new chain I used above it should work.
I think you shouldn't remove syslog, here is why:
- Cron logs to syslog
- Many applications have syslog adapters or direct file outputs (php apps behind php-fpm for example cannot log to stdout -> docker directly, but by plugging in a syslog adapter into their logging framework the problem is solved)
- There is no downside (except a few mb in a somewhat larger image) to keeping it

**Comment by hyperknot** [comment]
I agree with keeping syslog and removing the forwarder. This PR seems to be doing exactly that as well:
https://github.com/phusion/baseimage-docker/pull/324/files

We just need to consolidate both into a clean solution.

**Comment by hyperknot** [comment]
OK, even this PR wants to do exactly that:
https://github.com/phusion/baseimage-docker/pull/287/files

I'll have a proper review on all proposed solutions and mix them.

**Comment by davidhiendl** [comment]
Do you want me to create a PR for it?
- removing forwarder
- add direct stdout
- logrotate should stay if logs are still written internally

**Comment by hyperknot** [comment]
If you can create a PR mixing your solution, #324 and #287 that'd be great!
I think logrotate wouldn't change, would it?

**Comment by davidhiendl** [comment]
There it is, logrotate needs a slight change: do not restart the tail command as it doesn't exist anymore

**Comment by hyperknot** [comment]
@davidhiendl thanks a lot for your PR, merged now!
