### ISSUE TITLE
my_init should have a mechanism to wait until all Runit services are started

### ISSUE THREAD

**Issue by StarvingMarvin** [phusion/baseimage-docker#44]
I'm having around 300 images based on  baseimage-docker and I'm running a script that will run a command on each of those (with `/sbin/my_init --` as an  entry point), wait for it to finish, do stuff, run next...

Several times, container hang with this message as last thing in log:

```
warning: /etc/service/cron: unable to open supervise/ok: file does not exist
```

except any of the cron / syslog / ssh could fail with this message.

I'm not having a reliable way to reproduce this.

**Comment by bukzor** [comment]
I was about to file a ticket, asking for a way to wait for runit to start its services, but found that this ticket was already created.

I think a good implementation would be to provide a wait-for-services script that blocks until this condition is met. Users can then `docker exec` it as needed, and it could be used inside my_init for the same purpose. 

If there were extension points to define further conditions to wait for (mysql can churn for a bit before it is connectable) that would be even better, but not essential.

**Comment by bukzor** [comment]
Actually, such a system seems to already exists in runit, in the `sv check` command and the `check` callback. A `wait-for-services` just needs to `set -e` and run sv check against each service.

**Comment by robinbb** [comment]
I have the same issue as @joewoodhouse.

**Comment by chadian** [comment]
This isn't really a fix, but a general strategy. Some services will have be able to launch and execute files where you can include this. In the case of mysql I was able to use a run file:
```
#!/bin/bash
mysqld --init-file=/etc/service/mysql/create-wp-db.sql
```
and then in my Dockerfile
```
ADD .docker/mysql/create-wp-db.sql /etc/service/mysql/create-wp-db.sql
```

Using mysqld with `--init-file` did the trick. Hope this helps as a temporary work around, and there might be similar strategies for other services that run into this issue.

**Comment by pnegahdar** [comment]
what is the status on this?

**Comment by FooBarWidget** [comment]
This is not implemented right now. We are currently performing a maintenance sweep and fixing important bugs. But since this is an enhancement, we don't consider it high priority.

**Comment by fedelemantuano** [comment]
I have the same issue. I'd like to submit a Apache Storm topology, after it's up. I tryed with sleep strategy in script in `/etc/my_init.d` but doesn't work.
Can you have any trick that I can use?

**Comment by hyperknot** [comment]
I believe it's impossible to implement on my_init level. The reason is simply that services do not provide a common way for showing they are UP. The best is a shell script for each specific service, which you can use.

For example, this is the one I wrote for checking if postgresql is loaded and ready.

```
until su - postgres -c '/usr/lib/postgresql/9.5/bin/pg_ctl status -D /data/pgsql/9.5' | grep 'pg_ctl: server is running '
do
    echo
    echo "....waiting for PostgreSQL to start"
    sleep 1
done
sleep 3
echo "PostgreSQL started"
```

Your custom apps can be checked by writing a custom file to `/var/run`, like:
```
until [ -f /var/run/myapp.run ]
do
    echo
    echo "....waiting for app to be ready"
    sleep 1
done
echo "app started"
```

**Comment by Theaxiom** [comment]
Right now just waiting for the merge conflicts to be resolved in #192

**Comment by thetoolman** [comment]
sv has a check command for waiting for a service to start:

http://smarden.org/runit/sv.8.html

So just add "sv check <service>" to the start of your script to ensure your service(s) are started.

**Comment by kingdonb** [comment]
That tells you the service has launched, but it doesn't tell you it is alive and ready. (Edit: I'm wrong!  `sv check` supports custom health checking behavior, you can define your own `check` script.)

Postgres for instance may take several seconds in the usual case before it is ready to answer queries, or even listening on the listening port.  I use this one (based on WUPIAO from CoreOS which stands for Wait Until Port Is Actually Open):

```
retries=10

for ((i=0; i<retries; i++)); do
    nc localhost 5432 -q 5 << EOF
EOF
    [[ $? -eq 0 ]] && break

    echo "something went wrong, let's wait 5 seconds and retry"
    sleep 5
done

[[ $retries -eq i ]] && { echo "Failed!"; exit 1; }
exit 0  # We made it!  Postgres server is listening
```

@hyperknot 's version is better I think, because it's certainly possible the port is open but PG is not ready, and pg_ctl gives a reliable answer.

But, this way does not require the caller to have root or `su` and it has worked for me...

**Comment by thetoolman** [comment]
My approach to the check script for postgres was simpler:
```bash
#!/bin/sh

##
# Runit check script for postgresql
#
pg_isready || exit 1
```

**Comment by Theaxiom** [comment]
There is a proper workaround for this issue, unfortunately there is no elegant way to implement this at the baseimage level. I am closing this issue.

If someone has a different conclusion, please post your reply here, thanks!

**Comment by yakutovicha** [comment]
Dear @phusion, I would like to re-iterate this issue one more time.

I totally agree that it is very hard to check that all services are started. But, it is very easy to make a script that waits until all scripts in the `my_init.d` folder were executed. Such a check would be of very helpful, I believe. For instance, If one wants to make sure that a service is properly started, one can add a service-specific check mechanism in the corresponding `init` scrip.

PR #192 was doing exactly that, but unfortunately, it didn't make its way through. I can volunteer to make a similar PR if such a feature is considered useful.

**Comment by Theaxiom** [comment]
@yakutovicha We are always open to accepting enhancement pull-requests. I was not around at the time that previous one didn't make it and by the time I got to it there was some bit rot.

Regarding the solution to this problem, I believe individuals are handling this on their own in different ways which are specific to the applications that are running inside the container. I don't know exactly how you could improve upon the existing process until I see it.
