### ISSUE TITLE
Version 0.10.0

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#448]
Also, please raise the minor version to 0.10.0 in the next release as this is breaking compatibility with child images. We should also document somewhere that lines like:

```
touch /etc/service/syslog-ng/down
rm -rf /etc/service/syslog-ng
```

Will have no effect, and need to be changed. 

Also 
```
touch /etc/service/syslog-forwarder/down
```

Will break the build since that folder no longer exists.

**Comment by davidhiendl** [comment]
There was no tag named "latest" or "0.9.x" or "0.9".
So any child image would require a manual update which would minimize the risk of breaking automatic builds?

Perhaps the main readme should contain a section name "Upgrades"?
And a sub-section named "0.9.x to 0.10.x" specifying those issues and possible workarounds?

**Comment by Theaxiom** [comment]
That is a great suggestion @davidhiendl 

The reason I have not performed a release is for precisely that reason, I am trying to figure out the best way to handle this as there is no precedent. Your feedback is greatly appreciated.

**Comment by hyperknot** [comment]
There _is_ the tag latest, right now it's the same as 0.9.22.

Latest is used by a large number of child images, for example: https://github.com/spujadas/elk-docker/blob/master/Dockerfile

I think it shouldn't break anything as long as they are not customising forwarder and/or logger services.

**Comment by davidhiendl** [comment]
You are right, I confused that with there not being any tag like "master" that is build from the github master branch. Sorry about that.

I think that the image should have a "0.9" tag that always points to the latest "0.9.x" version (which should never introduce breaking changes) and one "0.10" that points to the latest "0.10.x". Similar to how other images use semantic versioning to avoid introducing breaking changes. Better yet adopt it completely and indicate it in on the readme?

Anyone who uses latest should expect the build to break at some point anyhow... At least I do whenever I build images that rely on other images.

**Comment by Theaxiom** [comment]
@davidhiendl as far as a `master` Docker tag, we are working on adding that and always keeping `latest` to be the last released version: https://github.com/phusion/baseimage-docker/issues/386

@davidhiendl That information is represented in the README: https://github.com/phusion/baseimage-docker/blame/master/README.md#L142

**Comment by davidhiendl** [comment]
Has there been any progress on this or is there a concrete problem hindering the progress? I've been using my own image build from `master` for quite some time now. And the last (quite old) `release` has quite a few problems including syslog-forwarding that make it sort-of unsuitable for production.

**Comment by Theaxiom** [comment]
@davidhiendl I apologize for the delay in release, my day job has been quite demanding lately and we had holiday and my first vacation in 2 years. I will be pushing out a release this week and soon automating the release process. Thank you for your patience!

**Comment by Theaxiom** [comment]
Pushing release now, 0.10.0
