### ISSUE TITLE
syslog-ng gets the kill command from the init process before the shutdown sequence

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#450]
See https://github.com/phusion/baseimage-docker/pull/447#issue-270460590 for more details regarding this issue.

**Comment by Theaxiom** [comment]
This also affects #436

**Comment by Theaxiom** [comment]
Can any of these PR's help us?

- https://github.com/phusion/baseimage-docker/pull/287/files
- https://github.com/phusion/baseimage-docker/pull/324/files

**Comment by Theaxiom** [comment]
This has also been reported in #437

**Comment by Theaxiom** [comment]
This PR is also related: #438

**Comment by Theaxiom** [comment]
The PR which introduced this is #425

**Comment by hyperknot** [comment]
I need to add debug print() lines to my_init to see exactly what functions were called in which order before and after #425.

**Comment by Theaxiom** [comment]
Thanks @hyperknot
