### ISSUE TITLE
Best way to gracefully shut down container from inside?

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#451]
What is the best way to shut down the container from the inside and get an exit code 0?

**Comment by BunnyHolder** [comment]
`kill -9 1`
And your p1 has to handle signal and return 0 and stop child proceses.

Same is done, when you run `docker stop <instnaceid>`. It sends `nice` kill

**Comment by Theaxiom** [comment]
Thanks!

**Comment by tcf909** [comment]
This doesn't seem to work for me. kill -9 1 seems to be ignored.

```
trap 'ON_ERR' err

trap 'ON_EXIT' exit

function ON_ERR(){

	local EXIT_CODE=${1:-1}

	echo "VPN FAILURE. STOPPING CONTAINER."

	printf "" > "${VPN_FILE_AUTH}"

	kill -9 1

	echo "$?"

	exit ${EXIT_CODE}
}

function ON_EXIT(){

	local EXIT_CODE=$?

	(( EXIT_CODE > 0 )) && ON_ERR ${EXIT_CODE}

	printf "" > "${VPN_FILE_AUTH}"

	exit 0
}

exit 1
```

Does not actually stop the container.

What am I missing?
