### ISSUE TITLE
`syslog-forwarder` seems to require a restart

### ISSUE THREAD

**Issue by mitchellwrosen** [phusion/baseimage-docker#452]
For some reason, I don't see any syslog output in `docker logs` unless I manually enter the container and restart the `syslog-forwarder` service.

Steps to reproduce:

1. Run a container 
```
$ docker run -d --name foo phusion/baseimage
```

2. Ensure that `syslog-forwarder` is running

```
$ docker exec foo sv status syslog-forwarder
run: syslog-forwarder: (pid 15) 6s
```

3. Manually append to `/var/log/syslog`
```
$ docker exec -it foo bash
root@5f49d6408562:/# echo bar >> /var/log/syslog
```

4. Observe that `bar` does not appear in `docker logs`
```
$ docker logs foo
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
```

5. Restart `syslog-forwarder`

```
$ docker exec foo sv restart syslog-forwarder
ok: run: syslog-forwarder: (pid 42) 1s
```

6. Again manually append to `/var/log/syslog`
```
$ docker exec -it foo bash
root@5f49d6408562:/# echo bar >> /var/log/syslog
```

7. Observe that `bar` _does_ now appear in `docker logs`
```
$ docker logs foo
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 9
bar
```

Any idea what the problem might be? Thank you so much!

**Comment by Theaxiom** [comment]
Which version of `baseimage-docker` are you using?

**Comment by mitchellwrosen** [comment]
Latest as of today.

**Comment by Theaxiom** [comment]
That would be `0.9.22` thanks!

**Comment by Theaxiom** [comment]
Could you please try building the image from `master` and see if that resolves your issue?

**Comment by mitchellwrosen** [comment]
Hmm, I just build the image with
```
vagrant up
vagrant ssh
make build
```
and the resulting image doesn't have a `syslog` service, just `cron` and `sshd`.

**Comment by mitchellwrosen** [comment]
Ah, I see, it's because of the race condition mentioned in the README. Anywho, still, writing to `/var/log/syslog` does not appear in `docker logs`.

**Comment by mitchellwrosen** [comment]
I see #438 was merged to replace the old forwarding service, but was this actually tested? @davidhiendl did you observe your change working, and if so, might I have some advice on what the problem is?

To quickly recap: I've started a container, manually `echo`'d to `/var/log/syslog`, and I don't see the output in `docker logs`.

**Comment by mitchellwrosen** [comment]
I found this in the logs:

```
Nov 11 02:17:01 c9ddcb4fb278 syslog-ng[132]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
```

**Comment by Theaxiom** [comment]
Thank you @mitchellwrosen for your testing, we will work to perform further RCA regarding your findings and post them here until we can resolve the problem. 👍

**Comment by davidhiendl** [comment]
@mitchellwrosen If you manually redirect output to `/var/log/syslog` file you are bypassing the syslog daemon. The syslog daemon not outputs to `/var/log/syslog` AND `/dev/stdout` of PID 1 (which is docker container output as seen in logs). 

I'm currently using a self-build image from the master branch of the repo and seeing all syslog output in the docker logs as expected.

If you want to manually log with syslog you should use the `logger` utility:
```bash
echo "some log message" | logger
```

**Comment by mitchellwrosen** [comment]
Ah, apologies for the misunderstanding! Thank you.

**Comment by davidhiendl** [comment]
Regarding the warning your are receiving regarding the pipe driver vs file driver:
This occurs when you run the image with the `-t` argument, from the `docker run --help`  command:
```
-t, --tty                            Allocate a pseudo-TTY
```
It does not happen when you do not pass that argument (which you normally don't for a background service). In either case I could not find any problems when originally testing the changes made in my PR.

**Comment by Theaxiom** [comment]
Thank you @davidhiendl for the clarification! I am closing this issue.

**Comment by RichardoC** [comment]
Hi there, 

Can an updated container be uploaded? I'm encountering the same issue and am unable to rebuild the container myself.

Many thanks

**Comment by mitchellwrosen** [comment]
For now, you can use https://hub.docker.com/r/sentenai/baseimage/. The tags refer to the commits here, and I believe I disabled cron and ssh but otherwise left the image untouched.

**Comment by Theaxiom** [comment]
We will be releasing a new version shortly!
