### ISSUE TITLE
Add env vars using shell script

### ISSUE THREAD

**Issue by DoraDreams** [phusion/baseimage-docker#456]
Hi, I want to add envs using shell script, but it does not work. I do not know why?

**Comment by richard-scott** [comment]
Need more info:

- When are you running the shell script?
- what is the shell script? can we see it? or at least the 1st line and the line you sent an env variable.

**Comment by DoraDreams** [comment]
Nothing. There is somewhere i mislead. Now, i have finished it via reading your python script
