### ISSUE TITLE
cannot access '/etc/rc0.d/K01hwclock.sh': No such file or directory

### ISSUE THREAD

**Issue by ymartineau** [phusion/baseimage-docker#458]
hi,

I'm trying to start a container relying on phusion/baseimage-docker, and it seems that some files are missing or have an odd status and it gives me the error message in ticket title. More details available here:

https://stackoverflow.com/questions/47921558/restcomm-phusion-baseimage-runsv-unable-to-start-run-file-does-not-exist

thank you,

yohann

**Comment by Theaxiom** [comment]
It seems you answered your own question on SO, if you continue to encounter issues please open a new one here. Thanks!

**Comment by ymartineau** [comment]
yes, sorry, I should've closed this ticket.
thank you
