### ISSUE TITLE
Typo in port info in README?

### ISSUE THREAD

**Issue by jcw** [phusion/baseimage-docker#461]
The top-level README.md says `-p 22:2222` - but I think the two fields are reversed.
Being new to Docker, it took me a while to figure out that it should be `-p 2222:22`.

**Comment by kingdonb** [comment]
Hmm, @jcw thanks for the report I will try and follow the README to see what else is confusing.

**Comment by rdxmb** [comment]
@jcw  You are right. Just created a PR for that.

**Comment by Theaxiom** [comment]
Thanks @jcw and @rdxmb
