### ISSUE TITLE
Docker tags

### ISSUE THREAD

**Issue by hyperknot** [phusion/baseimage-docker#467]
I don't quite agree with the new automated system.

1. It's creating a Docker tag for every single branch or PR which we ever create.

![phusionbaseimage - docker hub 2018-02-17 02-08-56](https://user-images.githubusercontent.com/494223/36336431-02ab3d62-1388-11e8-8bf6-1bce2f3a692c.png)

2. Also we are using "latest" for bleeding edge releases, which will break child images. There are multiple production child images which use "baseimage:latest". For unreleased master branch, we should push to "master".

**Comment by hyperknot** [comment]
@Theaxiom

**Comment by Theaxiom** [comment]
@hyperknot I had planned to setup automation to clean-up old images, I just hadn't got around to it yet. Pushing an image for every branch is perfectly okay, I am doing that to make it easier to test changes.

There are no storage limits on Docker Hub. If you would like to develop the cron to clean-up old images, go for it. :) I was going to make it clean-up all non-tagged images which are older than 30 days.

**Comment by JPLachance** [comment]
Hello!

From Docker Hub tags, the `latest` image is more than a year old (January 26, 2018) and the `master` image is the one with all the latest commits. The last official release is `0.11“, which was a long time ago.

If I want to use this base image today, which tag should I use? Normally, I would use `latest`, but I really want Ubuntu 18.04 😄 

Thanks in advance for your advice!

**Comment by kingdonb** [comment]
I would recommend either rebuilding v0.11 from the tagged commit yourself, or if you prefer to live dangerously go ahead and use master.

I think we're pretty careful (read: slow) to merge stuff into master, so it should be perfectly safe to use the image tagged "master", and if you notice something wrong, welcome to report it.  But in general I don't believe we're updating the image regularly unless changes are merged which would cause that to happen.  So you will have some outdated packages, unless you build for yourself.

In general it's always a good idea to build images for yourself to ensure freshness, especially when they pull in dependencies from upstreams like this one does.  On the other hand we should be able to provide fresh images, or at the very least the outdated "latest" tag should go.

**Comment by Theaxiom** [comment]
We actually do not recommend using `latest` and that is why we do not build a `latest` image. In-fact, latest should be removed from Docker hub. We recommend pinning a specific version of baseimage in your Dockerfile to help ensure reproducibility.
