### ISSUE TITLE
syslog-ng WARNING with --tty

### ISSUE THREAD

**Issue by hyperknot** [phusion/baseimage-docker#468]
After the new syslog-forwarder-less commits, starting the container with `--tty` now results in regular WARNING messages, as well as at startup.

```
syslog-ng[21]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
```

Is there anything we can do with this? Seems to be a bit of a backwards step that our users cannot use the `--tty` switch without some bad looking messages appearing regularly.
@Theaxiom @davidhiendl

**Comment by hyperknot** [comment]
It's the same: `-t, --tty` (actually I'm using `-it`).

A possible solution would be to check the type in a bash script and sed the config file on each startup, I have no other idea about how to solve it. Other than a few warning lines it seems quite harmless, but definitely not a nice experience for users trying out Baseimage.

**Comment by davidhiendl** [comment]
The warning with "-t" or "--tty" stems from the fact that there is a difference between attaching a tty and logging to file (pipe driver vs file driver). It might be possible to solve this but since you should only see this warning during development and not when running containers in a production environment I'm not sure if it is a good idea.

In order to solve this you would have to detect the current attachment mode during startup of the container and modify the syslog configuration.

**Comment by danielpclark** [comment]
This is an annoying issue for me.  `dmesg -D` does not fix this problem.

**Comment by davidhiendl** [comment]
@danielpclark feel free to test my PR if you need an immediate fix. For me this fixes the issue.

**Comment by danielpclark** [comment]
Trying now…

P.S. setting `CONSOLE_LOG_LEVEL=1` in `/etc/default/syslog-ng` doesn't seem to help either.

**Comment by danielpclark** [comment]
You fix works.  The warnings stopped appearing every hour.

**Comment by danielpclark** [comment]
Oops I spoke too soon.  I'm still seeing the warning.

**Comment by davidhiendl** [comment]
That is not a warning or an error. That is simply the log for the cron invocation.

**Comment by danielpclark** [comment]
I'm aware that it is neither a warning or an error.  But it is noise on the tty which is why this issue was raised.

**Comment by davidhiendl** [comment]
The thing is that message actually serves a purpose (in my opinion, which is notifying you that cron was executed). The point of this ticket was the warning that was introduce a while ago when syslog-ng was changed to also log to docker logs via stdout (to allow aggregating logs). It might be better to raise a separate issue to bring attention to this?

**Comment by hyperknot** [comment]
@danielpclark that's a totally different issue, and has been present for ages. Most of us actually believe it's a good thing to have feedback about cron jobs running, so it'll probably stay like this.

If you are concerned, please open a separate ticket about that line please.

**Comment by danielpclark** [comment]
I'll be content to leave it as is.  This solution wasn't what I thought you were aiming for.  My ncurses server stats display gets distorted on the hour.  But the information there is only needed initially so it's not a huge issue.

**Comment by stevenmunro** [comment]
How do I suppress this annoying message?
`CONSOLE_LOG_LEVEL=1` doesn't do it for me.

**Comment by davidhiendl** [comment]
@stevenmunro Which message are you referring to? 

If you are talking about something like this:
> Feb 22 13:17:01 507a5181d782 CRON[881]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

It's perfectly normal and a log statement emitted by cron when performing cron tasks.

**Comment by kingdonb** [comment]
At the risk of pointing out something that seems obvious (to me?), you could simply prevent cron from running altogether if you don't need that (disable the service) or run it in a different container that isn't in charge of displaying your stats curses app, if you do need that.
