### ISSUE TITLE
syslog restart not possible

### ISSUE THREAD

**Issue by hyperknot** [phusion/baseimage-docker#469]
With the recent changes of running syslog-ng outside of sv, the restart syslog-ng lines in logrotate doesn't actually do anything.

Now that's an other situation where I think abandoning sv wasn't a good idea, I think it'd a better solution to manually control the order of sv services from my_init instead.

But the most important question now:
1. Why do we need to restart syslog-ng after logrotate?
2. If we do need it, how do we achieve it now?

**Comment by Theaxiom** [comment]
1. I don't know that we do, unless there are memory/leak issues. Otherwise I say we remove the restart of syslog-ng. More research may be required.
2. Not sure off the top of my head.

**Comment by hyperknot** [comment]
Will be fixed with #478

**Comment by Theaxiom** [comment]
Merged and fixed.
