### ISSUE TITLE
Docker login fails on Travis

### ISSUE THREAD

**Issue by hyperknot** [phusion/baseimage-docker#471]
@Theaxiom the new travis config fails to log in to docker, docker login is actually waiting at a 
"Username:" prompt forever and then gets cancelled after 10 minutes.

Maybe the travis version still requries the -e email switch as well?

**Comment by Theaxiom** [comment]
The problem only occurs on branches which are in a fork. I will update the travis config soon, what is there right now was just to get automated build and push working and I hven't had the time to clean everything up yet.

**Comment by coyle** [comment]
any update on this ?

**Comment by Theaxiom** [comment]
Yeah, it is very annoying. I am going to be fixing it shortly. Thanks for your patience!

**Comment by Theaxiom** [comment]
Apologies everyone for my lack of attendance, I've been really consumed by life lately. I have upgraded @kingdonb to admin along with @hyperknot -- I appreciate both of your help in maintaining this project! Thank you! I will eventually fix the Docker stuff, unless someone gets to it first. :)
