### ISSUE TITLE
Syslog to stdout does not respect message level

### ISSUE THREAD

**Issue by davidhiendl** [phusion/baseimage-docker#472]
Currently all syslog messages filtered by `f_syslog3` are redirected to `/dev/stdout`.
It might be better to actually redirect error messages to `/dev/stderr`. Also messages sent to other levels (ex. debug) do not end up in docker logs at all.

I think it at least the error messages should go to `stderr`. Any thoughts on this? If this is acceptable I would be willing to configure syslog accordingly and create a PR.

**Comment by hyperknot** [comment]
@davidhiendl that's actually a good idea, if you'd do a PR that'd be great. Also the other levels should also go to stdout I believe. 

Can you just double check if the stderr ones also appear in Docker?

**Comment by davidhiendl** [comment]
@hyperknot currently the filter does the following:
`filter f_syslog3 { not facility(auth, authpriv, mail) and not filter(f_debug); };`
is written by the following log rule: 
`log { source(s_src); filter(f_syslog3); destination(d_syslog); destination(d_stdout); };`
which means: everything except auth, mail and debug is written to `/var/log/syslog` and `/dev/stdout`.

I think we should at least correct the following:
- Include debug in `stdout`
- Change error & critical from `stdout` to `stderr`

Let me know what you think.

**Comment by hyperknot** [comment]
OK, I've just checked on some of my production containers. None of them have anything in /var/log/debug and /var/log/error. Can anyone check if there is actually anything being logged there? If not, I think we should just leave it as is, as they are not being used.

**Comment by SimonHeimberg** [comment]
> OK, I've just checked on some of my production containers. None of them have anything in /var/log/debug and /var/log/error. Can anyone check if there is actually anything being logged there? If not, I think we should just leave it as is, as they are not being used.

According to #455 /var/log/error is used.
