### ISSUE TITLE
Update packages that are part of baseimage?

### ISSUE THREAD

**Issue by fryfrog** [phusion/baseimage-docker#473]
This is kind of a weird question, but as part of our container build we basically do `apt-get update && apt-get upgrade` and I was wondering how crazy this is? It updates a *ton* of packages. Is there any reason you don't update the packages in the baseimage?

**Comment by hyperknot** [comment]
Every time there is a new release, we always include up to date packages.
Which version are you using?

**Comment by fryfrog** [comment]
I have to admit, I'm not the best at Docker. We pull phusion/baseimage:latest in our Dockerfile, then run `apt-get update && apt-get upgrade` and it updates a ton of packages.

I *think* this is simply because baseimage pulls 16.04 and runs scripts on it, Ubuntu doesn't update the packages in their base image and it may or may not make sense for you guys to do anything like that on top of it.

Is updating the packages inside the container crazy?

**Comment by hyperknot** [comment]
1. Ubuntu updates it's base image regularly, and the packages inside it.
2. When we build baseimage we also upgrade all packages.
3. When you build you can also upgrade
4. It's not crazy.

**Comment by fryfrog** [comment]
Cool cool, thanks for the information. :)
