### ISSUE TITLE
Ubuntu 18.04?

### ISSUE THREAD

**Issue by richardpenman** [phusion/baseimage-docker#479]
Ubuntu 16.04 was released in 2016 - any plans to support the next LTS release 18.04? I needed to use some more recent library versions and ended up moving from Phusion -> Ubuntu 18.04 to get them.

**Comment by hyperknot** [comment]
I believe that we'll naturally support it, but I'd strongly recommend waiting till 18.04.1 till the first issues are ironed out. Last year it appeared 3 months after the LTS release, which I consider a good timing for all stable software releases.

**Comment by unilynx** [comment]
If anybody starts working on a phusion 18.04 branch, I'd love to help beta testing it. Looking into bringing over a fedora 26 container with a lot of dependencies on various ODBC drivers, so the sooner we start hitting the rough edges, the better

**Comment by unilynx** [comment]
Looks like all that's needed was updating syslog config and the version number - that was enough to get it through `make test` and my initial CI runs. My changes are on https://github.com/unilynx/baseimage-docker - I can make a PR if you want (or not, if you prefer to wait till 18.0.4's official release)

For my purposes, it appears to be 'good enough' already (if only MS had updated their MSSQL ODBC drivers for 18.04 already...)

**Comment by PikachuEXE** [comment]
@unilynx You can now try to play with official release of 18.04
Can we have a beta version for testing?

**Comment by unilynx** [comment]
@PikachuEXE Ubuntu is out, but the official docker images aren't there yet. https://hub.docker.com/r/library/ubuntu/tags/ shows 14 days old for 18.04, and 'latest' still refers to 16.04

I've updated my phusion image based on the 14-day old 18.04, it's now available on dockerhub as unilynx/phusion-baseimage-1804:1.0.2

**Comment by unilynx** [comment]
I've built a unilynx/phusion-baseimage-1804:1.0.3 using the final version of 1804 LTS from Docker. Passes my own tests

**Comment by twobombs** [comment]
Forked this wonderfull project late January, renamed the Dockerfile FROM: 16.04 to 18.04 and it's been working for me in Docker builds since January. For early adopters that want to have stuff running when 18.04.01 hits the road for production this is the way to do this. The road from 14.04 to 16.04 was much more of a hussle then 18.04 so far IMHO. A magnitude of issues less. Looking forward to snap patches and all that, could have some quirks there, but so far in the genaral scheme of things this one is a keeper.

**Comment by shearer12345** [comment]
bump - seems like there interest for an official phusion Ubuntu 18.04 from the community. Does Phusion want to do this?

Thanks @unilynx and @twobombs for the process for doing it ourselves

**Comment by Theaxiom** [comment]
We will work toward releasing an 18.04 image very shortly, any help from the community is welcomed and greatly appreciated. Thanks!

**Comment by PikachuEXE** [comment]
Using `18.04.1`?

**Comment by kingdonb** [comment]
It will probably be based on `docker.io/ubuntu:18.04`

https://github.com/tianon/docker-brew-ubuntu-core/tree/dist-amd64/bionic (I guess?)

I don't think they're doing semver at all, 18.04 appears to be a rolling release – there is no such 18.04.1 tag on https://hub.docker.com/r/library/ubuntu/tags/

**Comment by PikachuEXE** [comment]
@kingdonb 
See all the `bionic-*` tags
`18.04` is for latest of `18.04`

**Comment by kingdonb** [comment]
It says `.1` – is that the point release? How clever!
```
[   ] ubuntu-18.04.1-live-server-amd64.iso         2018-07-25 23:39  812M
```
was also cut yesterday, I think you're right

**Comment by Theaxiom** [comment]
I'm getting the latest `0.10` release out first and then will start on baseimage version `1.0` built on `18.04` shortly thereafter. Thank you all for your patience. We will still continue to support the `0.x` releases for a short time after until most have a chance to switch over to the new version `1.0`.
