### ISSUE TITLE
SSH default

### ISSUE THREAD

**Issue by rdxmb** [phusion/baseimage-docker#480]
In your docs you write
> Baseimage-docker disables the SSH server by default.

This is not really true. To be specific, the rsa-keys are not be created, but the ssh-daemon is running by default.

```
docker3.mbr.intern--(HOST):~# docker run -d -p 2323:22 phusion/baseimage
262538f6670f64523549c4d11c9aa4d358384dfdf1de7b5a755a0e600dbb4426
docker3.mbr.intern--(HOST):~# ssh -p 2323 127.0.0.1
ssh_exchange_identification: read: Connection reset by peer                                                         
docker3.mbr.intern--(HOST):~# docker exec -ti 262538f6670f64523549c4d11c9aa4d358384dfdf1de7b5a755a0e600dbb4426 bash 
root@262538f6670f:/# ls /etc/service/sshd/                                                                         
down       run        supervise/                                                                                    
root@262538f6670f:/# cat /etc/service/sshd/down                                                                     
root@262538f6670f:/# cat /etc/service/sshd/run 
#!/bin/sh                                                                                                           
set -e                                                                                                              
exec /usr/sbin/sshd -D                                                                                              
root@262538f6670f:/# cat /etc/my_init.d/00_regen_ssh_host_keys.sh                                                   
#!/bin/bash                                                                                                         
set -e                                                                                                              
if [[ ! -e /etc/service/sshd/down && ! -e /etc/ssh/ssh_host_rsa_key ]] || [[ "$1" == "-f" ]]; then                  
        echo "No SSH host key available. Generating one..."                                                         
        export LC_ALL=C                                                                                             
        export DEBIAN_FRONTEND=noninteractive
        dpkg-reconfigure openssh-server
fi
```

Why not removing the run-file by default?

**Comment by hyperknot** [comment]
It is not running by default. Try changing `:22` to something else like `:12345` and you'll see the same results.

What is a bit annoying though is that runsv sshd is present as a process. For this it might be better to store disabled services in something like `/etc/services.disabled/` instead of the current `down` approach.

**Comment by rdxmb** [comment]
> For this it might be better to store disabled services in something like /etc/services.disabled/ instead of the current down approach.

That could be another solution. My idea was to just remove the run-script, like you see in the PR.

**Comment by rdxmb** [comment]
> hmm. Do you really mean 'later on' == 'within a running container' ? For when you restart the container, there should be no problem with that.

**Comment by hyperknot** [comment]
If you remove a run script in baseimage-docker, then no user will ever be able to run that service.
If you remove a run script in your own Dockerfile based on baseimage docker, you only disable the service for that image.
A restart does not recreate a file missing from an image.

**Comment by rdxmb** [comment]
I think I didn't get it. I was assuming that removing a file **through in the init-process-file** would remove the file when starting a container - and **not within the build-process**? 
Isn't the problem with the travis-check, that it wants to enable ssh withing a running container with` docker exec` ?

Of course, when stopping and starting the container again, the file is still missing. But when starting a new container from the image, the file will be there.

However, if more flexibility is wanted, I would suggest to use env-vars for managing the services instead of having files like` /etc/services/sshd/down`

I just created #482 for that, so I close this one.
