### ISSUE TITLE
Could you provide supervisor  as a alternative runit ?

### ISSUE THREAD

**Issue by eromoe** [phusion/baseimage-docker#483]
Hello,

I have many projects with supervisor config. Because usually we tend to keep familiar tools,
it would be nice if baseimage-docker can let user choose supervisor or runit. 

Just a advice , thank you!

**Comment by hyperknot** [comment]
I agree that supervisor provides superior configurability, but it's written in Python and thus is using more resources (RAM mostly) compared to runit.

On the other hand, in the age of minimal 1 GB VPS machines, probably RAM doesn't matter as much as reliable operation.

**Comment by BunnyHolder** [comment]
I tried using supervisor, and runit much more durable and extremely simple to configure and run. Actually you even don't need no know anything about configuration. You only create file that works. 

We have stack of rabbitmq, mysql, redis, php-fpm, websocket-server, mysql-binarylog-listener-server(for notifications) in ONE baseimage. We install those to client servers and we never ever had problem with runit. 

In long run it has much better return value.

**Comment by hyperknot** [comment]
Yes, I agree with this. runit inside baseimage has proven very stable, and we are not planning to change it in the future.
