### ISSUE TITLE
ARM64 version available?

### ISSUE THREAD

**Issue by chrispsommers** [phusion/baseimage-docker#484]
Is there an image for ARM64?

**Comment by Theaxiom** [comment]
https://github.com/phusion/baseimage-docker/tree/armhf

**Comment by Theaxiom** [comment]
No, we do not have an image uploaded. I suppose we should get one onto Docker Hub.

**Comment by chrispsommers** [comment]
ARM64 would be nice. Thanks!

**Comment by Theaxiom** [comment]
I am having difficulty building the arm image, anyone else having any luck?

**Comment by idk-whatever** [comment]
@Theaxiom What did you try?

I just built the image from the master branch for ARMv7 by changing the parent image to `arm32v7/ubuntu:16.04`.

The current armhf branch still uses `armhf/ubuntu` as parent image which is deprecated and the last push was 1 year ago.

**Comment by chrispsommers** [comment]
Experimentally I was able to build ARM64 version on an x86 by making two small changes:
change first line to:
FROM arm64v8/ubuntu

add this line:
COPY qemu-aarch64-static /usr/bin

then follow instructions per https://github.com/multiarch/ubuntu-core to set up the host for binfmt. This was kind of piecemeal and could be turning into one-step process.

**Comment by rtgoodwin** [comment]
FWIW, I'm pretty close to this working as well. Building on a Mac for an RPi3 B (not plus), using the Vagrant setup. 

I used the `binfmt` instructions from the multiarch page, then--using `master` branch--changed the `FROM` to `FROM multiarch/ubuntu-core:armhf-xenial`. 

On `make build`, Docker kicks off, I see the packages being installed (and noted they are indeed `armhf` packages). Pretty exciting!

The problem (there's always one, right?) is that the process seems to hang after certain scripts, that don't make any sense. Like the `rm` of cron jobs/files:
```
+ rm -f /etc/cron.daily/dpkg
+ rm -f /etc/cron.daily/password
+ rm -f /etc/cron.weekly/fstrim
```
(just stops there, never proceeds).

Disable cron with the flag, and it gets to syslog, hanging on the end of its services script. Disable syslog, and then it hangs on:

```
Setting up runit (2.1.2-3ubuntu1) ...
+ '[' 1 -eq 0 ']'
+ true
+ '[' 1 -eq 0 ']'
+ true
+ '[' 1 -eq 0 ']'
+ true
```
I'm no expert (far from it), but it doesn't seem like anything "important" is happening at those stages, just shell scripts that almost certainly shouldn't hang.  I can (and have) just built it right on the Pi, but the nerd in me really wants to know the solution here. :) When I've got it sorted, I'll probably put together a README on how to do this for others that come looking for an ARM version of this and are even more newbie than me. They exist, I'm sure. ;) 

Thanks!

**Comment by rtgoodwin** [comment]
Minor update: Builds fine with `multiarch/ubuntu-core:armhf-bionic`.  ¯\_(ツ)_/¯ 

But it fails on `load` to my Pi 3 docker:
```
pi@raspberrypi:~$ docker load < rgoodwin.phusion-armf-bionic.tar
af8c46d3cfac: Loading layer   66.5MB/66.5MB
d7bd3bc7bc89: Loading layer  1.024kB/1.024kB
4f964168224a: Loading layer  3.708MB/3.708MB
cba9a994b911: Loading layer  14.85kB/14.85kB
d26bd8602f5a: Loading layer  5.632kB/5.632kB
54f77cd66652: Loading layer  1.024kB/1.024kB
d9bdd6ecaaf6: Loading layer  1.024kB/1.024kB
817199ffd351: Loading layer  65.02kB/65.02kB
dfb3b4995212: Loading layer  99.91MB/99.91MB
43fda510eb86: Loading layer  1.024kB/1.024kB
9fe02a3ce7f0: Loading layer  1.024kB/1.024kB
open /var/lib/docker/tmp/docker-import-918888120/repositories: no such file or directory
```
That said, containers build and boot from the image just fine, so I am going to assume (_ahem_) that the `missing` message is something about the qemu binaries or something, which aren't actually needed anyway on the Pi. 

Could be something to do with using multiarch and doing this all the wrong way. Maybe I should sit back and just wait for an official image. :) (But I _so_ want to know!)

Completely side note: it's been a while since I messed with Docker, and it's pretty awesome (if confusing at first) to realize when tinkering how many official and popular images are built from this baseimage. Great work and thanks all!

**Comment by abrodkin** [comment]
@Theaxiom @rtgoodwin I was able to cross-build Docker for `armhf` on my Fedora 28 machine (it's x86_64 Dell laptop).

That's the only change I made to this repo code:
```
diff --git a/image/Dockerfile b/image/Dockerfile
index da5b41d9fb98..eb3f84fad549 100644
--- a/image/Dockerfile
+++ b/image/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:18.04
+FROM multiarch/ubuntu-core:armhf-bionic
 MAINTAINER Phusion <info@phusion.nl>
 
 COPY . /bd_build
```

Then executed `make build` and got my container built.
FWIW I pushed it to DockerHub, see https://hub.docker.com/r/abrodkin/baseimage/

Now on my Raspberry Pi3 I installed latest Raspbian (it's based on Debian 9.4 as of today) and Docker CE. Then executed container this way:
```
sudo docker pull abrodkin/baseimage:0.11
$ sudo docker run --rm -t -i abrodkin/baseimage:0.11 /sbin/my_init -- bash -l
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Sep 19 13:34:53 8726d62cd70a syslog-ng[15]: syslog-ng starting up; version='3.13.2'
*** Booting runit daemon...
*** Runit started as PID 24
*** Running bash -l...
Sep 19 13:34:54 8726d62cd70a cron[28]: (CRON) INFO (pidfile fd = 3)
Sep 19 13:34:54 8726d62cd70a cron[28]: (CRON) INFO (Running @reboot jobs)

root@8726d62cd70a:/# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial		: 00000000dfbbe37d
```

So I'd say everything is in place and we're good to go with multiarch baseimage.

**Comment by kingdonb** [comment]
What distro are you using on RPI3, raspbian?  I'll test this

**Comment by abrodkin** [comment]
@kingdonb Correct I used latest Raspbian Stretch from here https://downloads.raspberrypi.org/raspbian_lite_latest
As I mentioned above it is based on Debian 9.4.

**Comment by NicksonYap** [comment]
@abrodkin I tried changing only

```
FROM ubuntu:18.04
```
to
```
FROM multiarch/ubuntu-core:armhf-bionic
```

But I got error from Docker Hub: (have not tested the build directly in RPi)

```
The command '/bin/sh -c /bd_build/prepare.sh && 	/bd_build/system_services.sh && 	/bd_build/utilities.sh && 	/bd_build/cleanup.sh' returned a non-zero code: 1
```

Here is the commit:
https://github.com/NicksonYap/phusion-baseimage-docker-armhf/commit/469b835797c0895d7f093ca92702845269787384

**Comment by abrodkin** [comment]
@NicksonYap you're missing one important thing (as described in https://hub.docker.com/r/multiarch/ubuntu-core/):
```
diff --git a/Makefile b/Makefile
index 1b00a21b78bd..eb95d384cf9c 100644
--- a/Makefile
+++ b/Makefile
@@ -6,6 +6,7 @@ VERSION = 0.11
 all: build
 
 build:
+       docker run --rm --privileged multiarch/qemu-user-static:register --reset
        docker build -t $(NAME):$(VERSION) --rm image
 
 test:
```

With that you should be able to build successfully on x86 host as usual.

**Comment by kingdonb** [comment]
We should add an arm64 target to the makefile then, so it can be easily integrated with CI

**Comment by kingdonb** [comment]
In #515 I am building armhf on darwin/amd64, according to previous commenters this works just as well on Fedora/amd64 or other platforms supported with qemu...

Build may take more than twice as long with this merged, but we will have support for twice as many architectures.  It seems to be working.

The make target build_amd64 and build_armhf are available now in case you want to only build a single arch.  I don't have strong feelings about the default make target, but I assume that CI will run "make" to build a new latest tag.

**Comment by kingdonb** [comment]
... and `make release` to push latest, but I guess finalized release tags are pushed manually and not by CI? e581cf7

Building as a test and pushing to [kingdonb/baseimage:0.11](https://hub.docker.com/r/kingdonb/baseimage/tags/) and [kingdonb/baseimage:0.11-armhf](https://hub.docker.com/r/kingdonb/baseimage/tags/) as well as `latest`(amd64) and `latest-armhf`

**Comment by kingdonb** [comment]
LGTM at bbff66a

**Comment by Theaxiom** [comment]
> We should add an arm64 target to the makefile then, so it can be easily integrated with CI

@kingdonb Could we please create an issue to reflect adding additional build targets for CI? There should be no need to change the Makefile, it can be done entirely using the travis-ci and simply having separate Dockerfile for different build targets (or something like that).

**Comment by kingdonb** [comment]
I'm not so sure, I think you need to run the armhf target on a system that is capable of running armhf binaries.

That doesn't mean you need an armhf system at TravisCI, based on the qemu register trick, but I think that requires that TravisCI lets us use privileged containers, and also that we are able to grab the same build host more than once in a session.  Both of those seem like a longshot (while I have not tried, so can't say for sure.)

I'll add the issue re:
> adding additional build targets for CI

**Comment by abrodkin** [comment]
Any updates on this one?

**Comment by Theaxiom** [comment]
We cannot maintain this image for multiple architectures because we simply do not have the resources to test them. If you require an arm image, please build and test yourself or fork the project. Once you fork it, we can add your project to this page: https://github.com/phusion/baseimage-docker/wiki/Baseimage-Based-Projects

**Comment by chrispsommers** [comment]
OK, thanks for your consideration!

**Comment by Theaxiom** [comment]
@chrispsommers I take that back, it looks like there is some work by @kingdonb that I forgot about here: https://github.com/phusion/baseimage-docker/issues/518

You may want to contribute or support that effort over in that thread, if we can make this work with multiple build targets we should be able to at least support an ARM image.

**Comment by chrispsommers** [comment]
@Theaxiom Good to see. I've moved on to other things and don't have time but it's nice that the qemu-user-static approach caught some folks' attention..
