### ISSUE TITLE
Release 0.10.1

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#485]

**Comment by Theaxiom** [comment]
Need to clean up the release process so it is as close to 100% automated as possible.

**Comment by mkiesel** [comment]
@Theaxiom :latest is still 0.10.0 - is this intentional? Probably adf8fd7 should've been reverted?

**Comment by Theaxiom** [comment]
@mkiesel You are correct, this is unintentional. I will work to correct this in https://github.com/phusion/baseimage-docker/issues/471
