### ISSUE TITLE
Runit starting order

### ISSUE THREAD

**Issue by ile** [phusion/baseimage-docker#486]
If I'm starting multiple services (redis, database, Node) in a container, I need to start them in a specific order (redis + db first, then the app).

I didn't find anything about how runit chooses the order how to start these. Is there a way to do this or did I miss something?

**Comment by hyperknot** [comment]
Right now there isn't. You have to wait for each service in their run script.

For example:

```
# waiting for app to be ready
until [ -f /var/run/app_web.run ]
do
    echo
    echo "....waiting for app to be ready"
    sleep 1
done
echo "app started"
```

**Comment by ile** [comment]
Ok, thank you. That should do, I think.

BTW, I have been using systemd which has the "dependencies" type of starting order. But, I also had a problem with it: I had syslog as a dependency, and then for some reason syslog disappeared (it seemed) and systemd killed all the apps that were running. Clearly not what you would want. So if you are ever thinking of changing to systemd, you may want to keep this in mind.

**Comment by Theaxiom** [comment]
Also remember that your included scripts are executed in lexiconical order (0-9,a-z,etc).

**Comment by ile** [comment]
In `/etc/my_init.d` yes? Yes, I noticed that, but it seemed that I should use `/etc/service/<name>/run` for the processes.

**Comment by ile** [comment]
Thanks for the baseimage btw!

**Comment by ile** [comment]
There is also this:

```
How do I make a service depend on another service
I have a service that needs another service to be available before it can start. How can I tell runit about this dependency?
Answer: Make sure in the ./run script of the dependant service that the service it depends on is available before the service daemon starts. The sv program can be used for that. E.g. the cron service wants the socklog-unix system logging service to be available before starting the cron service daemon, so no logs get lost:

 $ cat /etc/sv/cron/run
 #!/bin/sh
 sv start socklog-unix || exit 1
 exec cron -f
 $ 
```

http://smarden.org/runit/faq.html
