### ISSUE TITLE
Update Documentation with "easy-to-miss" edge cases and/or reorganize information

### ISSUE THREAD

**Issue by CWelshE** [phusion/baseimage-docker#498]
Hi!

I returned to this project after some time away, and found it frustrating that `runit` would not execute when I entered a built container built on `baseimage-docker` by executing `bash`. The whole point of my using the interactive mode was to verify the container's contents and/or behaviors were as I intended.

The obvious issue (or maybe not so obvious, as it took some time for me to realize this) is that running a command in the container necessarily takes PID 1, and `runit` won't start in that case.

There is a cursory overview of this issue in the documentation, but it's not where I expected it to be. I was paying more attention to the "Additional Daemons" section, but the relevant information exists later in the README - in the section regarding one-shot commands.

In any case, I would love to help update the README with any edge cases, and perhaps reorganize some of the content in a more relevant way. I think this is a wonderful project, and I think it deserves to receive pristine documentation. :)

I have some other suggestions - grammar modifications / removal of stale or out of date pages (CONTRIBUTING.md suggests a `next` branch that doesn't exist as of this writing, for instance) - but I'd like to hear feedback on this, too.

Thanks - I look forward to discussing this further.

**Comment by Theaxiom** [comment]
@CWelshE Thank you for your interest, any contributions are welcomed and encouraged! If you feel so inclined, make your changes/updates and submit a pull request; the PR will be reviewed by a member of the team and merged in when it is ready. :+1:

**Comment by CWelshE** [comment]
@Theaxiom Great - I'll make some changes and submit a PR when ready, and we can discuss further. :)
