### ISSUE TITLE
/etc/my_init.d/logtime.sh failed with status 127

### ISSUE THREAD

**Issue by kunthar** [phusion/baseimage-docker#50]
Your sample sh with chmod +x

```
#In logtime.sh (make sure this file is chmod +x):
#!/bin/bash
/bin/date > /tmp/boottime.txt
```

---

```
RUN mkdir -p /etc/my_init.d
ADD logtime.sh /etc/my_init.d/logtime.sh
```

---

```
docker run -i -t kunthar/middleware /sbin/my_init -- /bin/bash
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/logtime.sh...
*** /etc/my_init.d/logtime.sh failed with status 127
*** Killing all processes...
```

Whenever i comment out 

```
ADD logtime.sh /etc/my_init.d/logtime.sh
```

everything is fine. 

This is the explanation of status 127= http://is.gd/eKCtRI
I've used 

```
/bin/date > /tmp/boottime.txt
```

but no luck. 

Any comments?

**Comment by moonbingbing** [comment]
this bug still exist in version 0.9.16. what's wrong?

**Comment by OnixGH** [comment]
@moonbingbing what problem are you seeing? The image seems to work fine for me:
```
# docker run -i -t onix/test:0.9.16 /sbin/my_init -- bash
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/logtime.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 14
*** Running bash...
root@54e9871459ed:/#
```

On a sidenote, the bug from [GH-45](https://github.com/phusion/baseimage-docker/issues/45) is definitely fixed, but I'm not sure it was related because the pre-fix image also works without problems with the logtime example.

**Comment by moonbingbing** [comment]
@OnixGH  thanks for reply. 
my docker file is 
```
FROM phusion/baseimage:0.9.16

RUN mkdir -p /etc/my_init.d
ADD test.sh /etc/my_init.d/test.sh

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]
```

test.sh content is 
```
#In logtime.sh (make sure this file is chmod +x):
#!/bin/bash
/bin/date > /tmp/boottime.txt
```
the result is 
```
sudo docker run -i -t ming/test /sbin/my_init -- bash
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/test.sh...
*** /etc/my_init.d/test.sh failed with status 127

*** Killing all processes...
```

**Comment by OnixGH** [comment]
@moonbingbing try removing the first comment line of test.sh, so that it starts with `#!/bin/bash`. That works for me.

**Comment by OnixGH** [comment]
I've [updated](https://github.com/phusion/baseimage-docker/commit/d04ad4793068fb733bf4b5d285b252218c3bcb3a) the documentation to help avoid this mistake.

**Comment by kunthar** [comment]
:ok_hand: 
thx.

**Comment by Defozo** [comment]
I'm having the same problem despite having `#!/bin/bash` at the beginning of the file.

**Comment by Theaxiom** [comment]
@Defozo Could you please paste your script content into a [Gist](https://gist.github.com/) and share it here?

**Comment by Defozo** [comment]
I have no fancy code here. Just the one from the example:
Dockerfile:
```
FROM phusion/baseimage:0.9.19

RUN mkdir -p /etc/my_init.d
COPY logtime.sh /etc/my_init.d/logtime.sh
RUN chmod +x /etc/my_init.d/logtime.sh

CMD ["/sbin/my_init"]

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

logtime.sh:
```
#!/bin/sh
date > /tmp/boottime.txt
```

Console:
```
$ docker run fd7090916418
time="2017-04-09T15:44:50+02:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/logtime.sh...
*** /etc/my_init.d/logtime.sh failed with status 127

*** Killing all processes...
```

**Comment by Theaxiom** [comment]
Did you try it in Linux? It appears you are running in Windows. I would like to see if the issue persists in Linux.

Try installing Virtualbox and then Vagrant, then type the following commands inside a new, empty folder:
- vagrant init travisrowland/centos7
- vagrant up

Add your `Dockerfile` and `logtime.sh` files to that folder, then type these commands:
- vagrant ssh
- cd /vagrant
- docker build .
- docker run

Please let me know how that works out, thanks!

**Comment by Defozo** [comment]
I tried it on my Amazon Linux and It's working. Thank you very much.

**Comment by Defozo** [comment]
After a few successful tries the problem reappeared on Amazon Linux.
I tried deleting all images and rebuilding - without any success.

**Comment by Theaxiom** [comment]
Can we do a Hangouts session to try and figure out what's going on?

**Comment by Defozo** [comment]
I think the problem was due to some invisible extra characters.
I especially recommend _ababkov_'s comment [here](https://github.com/phusion/baseimage-docker/issues/110#issuecomment-91993918) for anybody googling this problem.

> FYI - this was coming back with "./run: file does not exist" for me for any services i attempted to add. When the script was run directly on the box, the following additional info was presented: "Invalid interpreter /#!/bin/sh^M" (or similar).
> 
> Issue ended up being dos vs unix line endings. Running the init files through from dos2unix / http://www.virtualhelp.me/linux/164-dos2unix-missing-ubuntu-1004 resolved the issue for me after 4 hours of head banging...

Thank you for your help! :)

**Comment by hyperknot** [comment]
I recommend you to change your git config to check out as Unix line endings
so it might save you from trouble like this in the future (if you use Git).

**Comment by Theaxiom** [comment]
Thanks for letting us know! 👍
