### ISSUE TITLE
Push 0.10.1 to https://hub.docker.com/ please

### ISSUE THREAD

**Issue by stevenmunro** [phusion/baseimage-docker#502]
In my dockerfile,

`FROM phusion/baseimage:0.10.0` works

`FROM phusion/baseimage:0.10.1` doesn't

**Comment by PikachuEXE** [comment]
https://hub.docker.com/r/phusion/baseimage/tags/
![screen shot 2018-07-23 at 4 57 18 pm](https://user-images.githubusercontent.com/1018543/43067291-855a2f48-8e99-11e8-8b02-53967c7a8eb3.png)
The tag exists, I can pull the image (I am using as parent image of several images)
Maybe provide more details on "it doesn't work"?

**Comment by stevenmunro** [comment]
My apologies. It appears to be working now.

**Comment by PikachuEXE** [comment]
Maybe close the issue if it's confirmed fixed?
