### ISSUE TITLE
Why not just docker build?

### ISSUE THREAD

**Issue by naevtamarkus** [phusion/baseimage-docker#504]
Hi,
First things first, thanks for the work you've done here! It's quite amazing.

I would like to build my own base image for my different apps, based on your baseimage. I did not like the fact that there's a binary file in the tools directory (for security, I validated your scripts by eye), so I just did a ```docker build -t my_image .``` on the image directory... and it seems to work fine. This gets rid also of the vagrant, makefiles and some other steps, so I was wondering:

Is there any reason why not doing it this way?

Bonus question: why did you not include the tzdata package? /etc/localtime links to an empty place.

Thanks!

**Comment by kingdonb** [comment]
Also /etc/localtime makes sense to be set by the end-user, when it is known (if) what timezone will be the main area serviced by this machine. No?

(Or wherever the admins live, I guess, since any application ought to ignore localtime and localize the timezone for the individual user...)

**Comment by naevtamarkus** [comment]
@kingdonb I don't think I agree... the "vanilla" /etc/localtime symlink is pointing to a file that's only populated when tzdata is installed. So, if you don't do anything, the baseimage has a broken link (please check!). I think it's okay to leave the default (UTC) and let the user change it if needed.

@Theaxiom I'm not sure I got the meaning of your message: I guess you mean "yes, you can just do docker build directly in the image directory", but I'm not sure. 

May I suggest replacing the binary /tools/baseimage-docker-nsenter by a source file that's compiled when needed? The fact that you ask people to download a binary and run it scared me quite a bit (enough to try to find a way around it, and almost enough to avoid using your code)

Thanks!

**Comment by Theaxiom** [comment]
Pablo,

Please break your requests up into separate issues as it makes it much more efficient to triage and track. Thanks!

**Comment by kingdonb** [comment]
We should not be including a broken link, but I think I'd favor including tzdata first, before I do anything to massage that broken link.

I don't think it's unreasonable to want to resolve a broken link, but I'm sure we did not put it there... it must've come in some package.

I will check, let's indeed break this up into separate issues though. Thanks for your report!

**Comment by samip5** [comment]
@kingdonb Has anything been done about this and is this valid issue still?

**Comment by kingdonb** [comment]
I think it can be closed. The resolution for now is, searches for "localtime is a broken link" related to baseimage-docker will hopefully land people here, where they will learn that if they need local time zone configuration, they should install the `tzdata` package and configure the timezone appropriately.

There should not be any time zone configuration in the upstream base image, as we will have no idea what time zone users are in. If we wanted to add time zone configuration information in the docs, I would be in favor of merging a docs addition that explained how to properly set UTC as the system time zone in localtime. At this point I'm not sure if there is anything else to do beside let the user install `tzdata`, but for those that did not need it, the savings is about 288kb.

**Comment by Theaxiom** [comment]
Thank you @kingdonb -- you are awesome and I appreciate you!
