### ISSUE TITLE
minimal ubuntu - game changer?

### ISSUE THREAD

**Issue by darrenleeweber** [phusion/baseimage-docker#508]
https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released

Does this make this project obsolete?

**Comment by kingdonb** [comment]
Definitely not.  This project has a ton of features, such as an init process, daemons, syslog and cron

http://phusion.github.io/baseimage-docker/

^ Start reading here.  If you are using baseimage-docker like a regular docker image that hosts one process, you might be missing out on a lot of niceties that make it unique.

In fact:

> Using Minimal Images from Dockerhub
> On Dockerhub, the new Ubuntu 18.04 LTS image is now the new Minimal Ubuntu 18.04 image. Launching a Docker  instance with docker run `ubuntu:18.04`  therefore launches a Docker instance with the latest Minimal Ubuntu.

https://github.com/phusion/baseimage-docker/blob/master/image/Dockerfile#L1

> `FROM ubuntu:18.04`

...the latest baseimage-docker, released 9 days ago, is already built atop this new minimal image.

**Comment by gte451f** [comment]
> ...the latest baseimage-docker, released 9 days ago, is already built atop this new minimal image.

I'm thrilled you guys put this together and naturally accrue benefits from Canonical's improvements.
