### ISSUE TITLE
Version '1:5.1.6*' for 'libreoffice' was not found

### ISSUE THREAD

**Issue by vushe** [phusion/baseimage-docker#514]
Hello All,

I'm using LibreOffice in my application and I'd like to freeze its version (`RUN apt-get install -y libreoffice=1:5.1.6*`), however it doesn't work, whereas perfectly works for Ubuntu's 16.04 image.

I'm using `phusion/baseimage 0.11`.

Message in terminal: `E: Version '1:5.1.6*' for 'libreoffice' was not found`.

Suggestions, please?

**Comment by vushe** [comment]
Ok, figured out. Version 0.10.2 must be utilize as it is based on Ubuntu 16.04

**Comment by kingdonb** [comment]
For the record, the 0.11 baseimage is based on Ubuntu 18.04 (not 16.04)

**Comment by kingdonb** [comment]
How do we update: http://phusion.github.io/baseimage-docker/

It says:
```
FROM ubuntu:16.04

RUN apt-get install all_my_dependencies
ADD my_app_files /my_app

CMD ["/my_app/start.sh"]
```

While this does not explicitly describe that baseimage is based on 16.04, it is confusing and the only version number on the page.  Hypothetical new user (who hasn't found baseimage-docker yet according to the phusion promotional site) probably should fix his or her upstreams, too.

The documentation (README.md) does reflect the correct version is 18.04 upstream.

**Comment by Theaxiom** [comment]
@kingdonb https://github.com/phusion/baseimage-docker/tree/gh-pages
