### ISSUE TITLE
adding additional build targets for CI - armhf / arm64

### ISSUE THREAD

**Issue by kingdonb** [phusion/baseimage-docker#518]
We should support as much as possible ARM targets like the Raspberry Pi.  I think we can cover all of them by just supporting `armhf` build target.  There is discussion about how to do this in #484 and initially seemed like it was really doable, but the problem is that building for different arches on TravisCI or any other docker image build hosts was going to require something extra.

In #484 we learned that you can use `multiarch/qemu-user-static:register` to build images for other architectures such as building a `armhf` or `arm64` target on a machine running Darwin + amd64 + Docker.  I did not quite understand the proper way to use the multiarch image, and we are also pretty sure this can be done without breaking the existing Makefile or diverging the multiple architectures too far at build time.

Ideally we would have a set of build slaves that cover every architecture we wanted to support, and running the build on each would trigger an appropriate image for that architecture to be pushed, all based on the multiarch image, and without necessarily requiring to add a list of supported architectures to enumerate inside of Makefile, or separate Dockerfiles.  (I might still not quite be understanding how multiarch docker base image is supposed to work.)

Maybe there is some kind of scaffolding to support this (building a project on several architectures at once) already in TravisCI.

**Comment by kingdonb** [comment]
It looks like someone has done this before (it's been possible for a long time, might be easier now)

https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

I don't think there's anything stopping you from running two consecutive Docker commands inside of a Travis CI.  From the looks of it, people have also had success building on Travis using privileged containers, so it might be quite a lot easier to get this done today than it was for tomaz to do armhf builds in 2013.

https://github.com/travis-ci/travis-ci/issues/4751#issuecomment-139069772

**Comment by jmreicha** [comment]
I'm interested in ARM support as well.  If you're not completely tied to Travis, [Shippable offers arm builds](http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/).

**Comment by Theaxiom** [comment]
Is Travis not able to perform ARM builds if we use a different configuration?

**Comment by kingdonb** [comment]
From some googlin' it appears that Travis does not natively support different architectures, but you can do it.  That link I posted last month shows how, at least one way.  It looks like a lot of overhead, compared to the `qemu-user-static:register` thing.

If you can use that trick on travis in a "prebuild" step, that might work?  I don't know if that's a thing, but it would seem there must be some way to prepare the Travis worker before you start your build.

I don't know enough about Travis, if it's possible to get a Docker socket and keep it throughout the execution of your build, it should be possible to use the qemu-user-static:register thing.  (That would be a lot less effort required than the way described by tomaz.me blogpost.)

**Comment by CodeCutterUK** [comment]
I think I have something working for ARM64v8 at least.... would that be if any interest to this group?

**Comment by Theaxiom** [comment]
@CodeCutterUK it would appear there are individuals who are looking for that, so I would definitely say so. :)

The next problem is, configuring the CI process to build and test for multiple architectures.

**Comment by CodeCutterUK** [comment]
Awesome, supporting this in the main repo and docker hub location would be much better than the other options.

Let me finish getting this working in my test repo, which is currently building ARM & ARM64v8, add X86_64, generally tidy it up and submit a PR for folk to review.

**Comment by Theaxiom** [comment]
The changes have been merged in, if anything breaks we will fix it forward. If anyone is available to help test the generated Docker images, that would be extremely helpful. Please post here your results, thanks!
