### ISSUE TITLE
Runit shuts down because of no reason

### ISSUE THREAD

**Issue by OO00O0O** [phusion/baseimage-docker#525]
I run on master(because ubuntu 18.04).
And because of no reason my all containers just exit because runit shuts down.
I don't know how to debug this.
Some peace of log:

```
Feb 12 06:42:23 d8cb674aae2e syslog-ng[69]: Configuration reload request received, reloading configuration;
Feb 12 06:42:23 d8cb674aae2e syslog-ng[69]: Configuration reload finished;

...

Feb 12 07:07:01 d8cb674aae2e CRON[4055]: (root) CMD (/usr/bin/php /var/www/bin/console root:ping &>> /var/www/var/log/cron.log)
Feb 12 07:07:01 d8cb674aae2e CRON[4056]: (root) CMD (/usr/bin/php /var/www/bin/console update:resource:bookings &>> /var/www/var/log/cron.log)
*** Shutting down runit daemon (PID 76)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Feb 12 07:07:14 d8cb674aae2e syslog-ng[69]: syslog-ng shutting down; version='3.13.2'
*** Init system aborted.
*** Killing all processes...
```

EDIT: Can I disable syslog? Or change it for simple file?

**Comment by monty124** [comment]
Hi all

I'm also seeing this behaviour now, i've built a ton of images from this base and all have been fine, of late anything i build seems to execute and immediatly shut down and nothing seems to fix it, i've got a couple that just run [CMD] /bin/bash and sit waiting for interaction externally, i cant even get these to stay up!
any ideas on what has changed? I'm going to start trying previous builds and stripping out customising in my dockerfile so i can see where things went wrong.

**Comment by Theaxiom** [comment]
Thank you folks for investigating.

**Comment by dmp1ce** [comment]
I'm not sure if this is related but I'm getting the following error on the most recent `phusion/passenger-ruby23` image. Arch Linux host. Docker version: `18.09.5-ce`.

```
passenger_1     | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
passenger_1     | *** Running /etc/my_init.d/10_syslog-ng.init...
passenger_1     | [2019-05-11T18:27:40.329161] Error opening control socket, bind() failed; socket='/var/lib/syslog-ng/syslog-ng.ctl', error='Permission denied (13)'
passenger_1     | May 11 18:27:40 a11679c47c41 syslog-ng[21]: syslog-ng starting up; version='3.13.2'
passenger_1     | *** /etc/my_init.d/10_syslog-ng.init failed with status 1
passenger_1     | *** Killing all processes...
passenger_1     | May 11 18:28:10 a11679c47c41 syslog-ng[21]: syslog-ng shutting down; version='3.13.2'
```

**Comment by Theaxiom** [comment]
@dmp1ce You will have to post your issue over on https://github.com/phusion/passenger-docker

**Comment by samip5** [comment]
Stale issue, closing.
