### ISSUE TITLE
Improve the documentation for logging

### ISSUE THREAD

**Issue by markphip** [phusion/baseimage-docker#526]
It would be helpful of the documentation included some common examples on how to leverage the logging.  For example, you are running one or more daemons that log to a file.  How best to configure syslog-ng to process these files and relay to docker via stdout.  Or maybe it is best to turn off syslog-ng and do something else?

Surely there is a best practice that could be suggested.

**Comment by markphip** [comment]
My assumption is we just have to dump a conf file in /etc/syslog-ng/conf.d but an example in the daemon section would be really helpful. Assuming of course that syslog-ng has a mechanism for doing this.  The docs for it imply it does but not sure.  Maybe something like this?

```
source s_myfile {
    file("/path/to/file.log" follow_freq(1) flags(no-parse));
};
  
log { source(s_myfile); destination(d_stdout); };

```

**Comment by markphip** [comment]
The previous example does work.  The only negative to it is if the logs are stored on persistent disk then every time the container starts the entire existing contents of the log get picked up again and sent to stdout.

**Comment by markphip** [comment]
The docs for syslog-ng say this:

> The syslog-ng application notices if a file is renamed or replaced with a new file, so it can correctly follow the file even if logrotation is used. When syslog-ng is restarted, it records the position of the last sent log message in the /opt/syslog-ng/var/syslog-ng.persist file, and continues to send messages from this position after the restart.

Assuming you did not change the location of this file, if we did something to have that file be persisted outside the container then maybe it would not relog the entire file when the container restarts?  I wonder if we could symlink this file to a file in our logs folder which we mount to a volume?

**Comment by kingdonb** [comment]
You could probably also solve that by configuring your startup sequences to trigger a log rotate before starting syslog-ng. I'm not sure if that's a reasonable basis for log rotate, but it would prevent syslog from picking it up.

**Comment by markphip** [comment]
I actually got this working well.  I overrode the /etc/default/syslog-ng.conf to add startup options so that I could add the --persist-file option and have it store the file in a path that I have mounted to persistent storage.  Works great.

**Comment by Theaxiom** [comment]
Thanks @markphip for sharing, I am sure this will come in handy for someone else as well.
