### ISSUE TITLE
Push `master` to Docker Hub

### ISSUE THREAD

**Issue by joncameron** [phusion/baseimage-docker#528]
Docker Hub's phusion/baseimage doesn't appear to be current and is still using Ubuntu 16.04 LTS. Could this be updated to the latest master in git? Thanks!

**Comment by crnm21** [comment]
@joncameron You could use the :master tag or the :0.11 tag to build baseimage from docker hub w/ ubuntu 18.04.
See https://github.com/phusion/baseimage-docker/releases/tag/0.11 and https://hub.docker.com/r/phusion/baseimage/tags

**Comment by joncameron** [comment]
Thanks! The tag method is perfect. I'll use that.

**Comment by Alives** [comment]
Why isn't that promoted to the latest tag though?
