### ISSUE TITLE
Request for publishing Power (ppc64le) image on DockerHub

### ISSUE THREAD

**Issue by seth-priya** [phusion/baseimage-docker#529]
I am working on a use case which depends on the availability of  phusion/baseimage for Power (ppc64le). The image builds successfully using the "docker build" command - no changes to the Dockerfile were required.

The following steps from the travis.yml succeed:

docker build -t ${NAME}:${VERSION} --rm image 
env NAME=${NAME} VERSION=${VERSION} ./test/runner.sh 

So, I believe, that all that will be needed from the perspective of building the image would be to enable support for Power in the travis,yml file by adding 
linux-ppc64le in the os: section

Example:
https://github.com/fluent/fluentd-docker-image/blob/master/.travis.yml#L5

Would it be possible for the Power image to be then made available on DockerHub? Looking forward to suggestions, inputs and support on this .. thank you!!

**Comment by seth-priya** [comment]
Reference link to the "Power" Travis job 
https://travis-ci.org/seth-priya/baseimage-docker/jobs/510820393

It is failing at the last step i.e. "docker login" similar to its Intel counterpart
https://travis-ci.org/seth-priya/baseimage-docker/builds/510820391

**Comment by seth-priya** [comment]
Any thoughts?

**Comment by kingdonb** [comment]
I'm not sure we want to be in the business of building images for every architecture, as that would imply we're also capable of testing them... you are welcome to fork and configure travis this way.

Sorry for the delay in reply.

**Comment by Theaxiom** [comment]
I am inclined to agree with that, the best OSS projects are forks of a core which have a specific goal in mind which deviates from the core mission of the original OSS project. (Kubuntu, MariaDB, etc)
