### ISSUE TITLE
Why so old ubuntu?

### ISSUE THREAD

**Issue by ftbarata** [phusion/baseimage-docker#531]
Why it's still using ubuntu 16.04 yet? Is there any prevision for using newer version of ubuntu?

**Comment by kingdonb** [comment]
The `:latest` tag is not updated, check `master`

**Comment by lukas9393** [comment]
Would you please explain why you're not using the 'latest' tag?

Unfortunately, I used the old tag until recently. I just didn't know it. And the Laradock developers also use the wrong tag. 
https://github.com/laradock/workspace/blob/master/Dockerfile-73

**Comment by ftbarata** [comment]
Hi @lukas9393 , I was using the baseimage from docker hub instead of github. It's outdated in there.

**Comment by lukas9393** [comment]
@ftbarata sorry my question wasn't addressed to you. But to the developers of this image. I will probably open another ticket for that.

**Comment by Theaxiom** [comment]
I've been on vacation and some self discovery as of late, I apologize for
any perceived neglect of the base image. I will be coming through soon and
performing a refresh, keep your eyes peeled! The refresh will consist of a
great many issues and feedbacks being implemented and generally tying up
loose ends.
