### ISSUE TITLE
How to know the ubuntu version?

### ISSUE THREAD

**Issue by zmlccf** [phusion/baseimage-docker#533]
The phusion/baseimage images can be pull from docker hub, but the according ubuntu version is not clear, is there any solution?

**Comment by Theaxiom** [comment]
https://www.hostingadvice.com/how-to/ubuntu-show-version/

**Comment by hayd** [comment]
That link is not helpful since lsb_release is not found/installed.

You can do `cat /etc/os-release` to see it's 18.04.1 LTS for 0.11.

It'd be great to update to the latest (18.04.2)...

**Comment by Theaxiom** [comment]
We are changing the version strategy to include Ubuntu version in baseimage version.
