### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding ModuleNotFoundError

### ISSUE THREAD

**Issue by chasel** [phusion/baseimage-docker#536]
system:centos 7
python default version
`[root@localhost ~]# python`

`Python 2.7.5 (default, Jun 20 2019, 20:27:34) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
`

When i execute 
`docker run -d -it --name phusion phusion/baseimage:0.11`

docker logs phusion display:
`Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'`

then i install python 3 and config env
`[root@localhost ~]# python`
`Python 3.6.8 (default, May  2 2019, 20:40:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
`
 but docker don't use python 3, the same error display

**Comment by kingdonb** [comment]
Are you getting a python error when you run baseimage, or when you run python through baseimage?  Please clarify, thanks and sorry for the delay in answering your report.

**Comment by chasel** [comment]
> Are you getting a python error when you run baseimage, or when you run python through baseimage? Please clarify, thanks and sorry for the delay in answering your report.

Yes

**Comment by c0derGitHub** [comment]
I got the same problem, but not the same image which is harbor prepare.I found that the container runs ok in centos 7.8 & 7.7 env, and failure in centos 7.9.😂

**Comment by samip5** [comment]
Which version of the baseimage is being used here? Has this been tested with the focal images?
