### ISSUE TITLE
python3 installed on phusion baseimage is faster than docker python:3 or python:3-slim?

### ISSUE THREAD

**Issue by jimmytuc** [phusion/baseimage-docker#537]
The only thing I know is `phusion baseimage` built on top Ubuntu and `python:3` was built on Debian family.

I noticed that the performance is very much difference between them when ran the same script for processing pandas data frame on the same size of the dataset.

Any thoughts?
Thanks

**Comment by kingdonb** [comment]
Could be related to #536? It looks like python2 and python3 are both installed, and perhaps python2 is getting used in cases where you expected it to use python3?  Reporter of #536 appears to be saying that the python binary path is not as expected.
