### ISSUE TITLE
phusion/baseimage fails to start on Arch Linux

### ISSUE THREAD

**Issue by lbssousa** [phusion/baseimage-docker#540]
## System info

* OS: **Arch Linux**
* Arch: **x86_64**
* Docker version: **19.03.2-ce, build 6a30dfca03**
* Affected `phusion/baseimage` tags: **0.10.0 and newer**

## Steps to reproduce

Try to start a `phusion/baseimage` container with the following command:
```
docker run --rm -t -i phusion/baseimage /sbin/my_init -- bash -l
```

## Actual behaviour

Here's the output:
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Error parsing source, source plugin unix-dgram not found in /etc/syslog-ng/syslog-ng.conf at line 21, column 8:

       unix-dgram("/dev/log");
       ^^^^^^^^^^

syslog-ng documentation: http://www.balabit.com/support/documentation/?product=syslog-ng
mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
*** /etc/my_init.d/10_syslog-ng.init failed with status 1

```
(... after some seconds ...)
```
*** Killing all processes...
```

## Additional info

I've managed to start a `phusion/baseimage` conteiner for tag 0.9.22. Although it starts the container, it keeps showing the error message above in a loop.

**Comment by kingdonb** [comment]
Whoops... did something change upstream in syslog-ng?

**Comment by dziurka** [comment]
I have the same problem. Unfortunately

**Comment by dziurka** [comment]
Can anything be done about it at the moment?

**Comment by kingdonb** [comment]
Can you see if it resolves the issue to install `tcp-wrappers` package?

**Comment by kingdonb** [comment]
FYI, I was not able to reproduce this issue. My host OS is MacOS and I am using Docker for Mac, community Docker Engine version 19.03.2.

Seems to work fine on 0.10.0 and 0.11 image tags

```
Digest: sha256:d72f41957bf41161c2b7ec00ed665573d17e8dfaaef55492063901a7e844532a
Status: Downloaded newer image for phusion/baseimage:0.10.0
docker.io/phusion/baseimage:0.10.0
kbarret8@kbarret8-mbp:~ (master *)$ docker run --rm -t -i phusion/baseimage:0.10.0 /sbin/my_init -- bash -l
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Sep 30 18:04:47 3158b926b09f syslog-ng[11]: syslog-ng starting up; version='3.5.6'
Sep 30 18:04:47 3158b926b09f syslog-ng[11]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
Sep 30 18:04:48 3158b926b09f syslog-ng[11]: EOF on control channel, closing connection;
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 17
*** Running bash -l...
Sep 30 18:04:48 3158b926b09f cron[21]: (CRON) INFO (pidfile fd = 3)
Sep 30 18:04:48 3158b926b09f cron[21]: (CRON) INFO (Running @reboot jobs)
root@3158b926b09f:/#
```

and

```
Digest: sha256:6ba22a31a809de669243b79f982f7b2df733ead1ec45becff401b4d5d79150bb
Status: Downloaded newer image for phusion/baseimage:0.11
docker.io/phusion/baseimage:0.11
kbarret8@kbarret8-mbp:~ (master *)$ docker run --rm -t -i phusion/baseimage:0.11 /sbin/my_init -- bash -l
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Sep 30 18:04:08 daf27acc987e syslog-ng[13]: syslog-ng starting up; version='3.13.2'
*** Booting runit daemon...
*** Runit started as PID 20
*** Running bash -l...
Sep 30 18:04:08 daf27acc987e cron[24]: (CRON) INFO (pidfile fd = 3)
Sep 30 18:04:08 daf27acc987e cron[24]: (CRON) INFO (Running @reboot jobs)
root@daf27acc987e:/# logout
*** bash exited with status 0.
*** Shutting down runit daemon (PID 20)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Sep 30 18:04:16 daf27acc987e syslog-ng[13]: syslog-ng shutting down; version='3.13.2'
*** Killing all processes...
```

I got the suggestion to try installing tcp-wrappers from a forum search, I have no reason to believe that it will work, but it was mentioned in a thread where this error popped up.

If you haven't done anything to your images and they are from the repo, then this must be a difference between our host systems.  Are you running SELinux or AppArmor, or any of those kind of frameworks which might interfere with system calls in the containers?

I'm afraid I won't be much help if I can't reproduce the issue, but hopefully some of this information is good.

**Comment by kingdonb** [comment]
It should be noted also, that:
```
docker run --rm -t -i phusion/baseimage /sbin/my_init -- bash -l
```
will use the "latest" tag, which is not maintained.

```
latest 73.67 MB
Last updated2 years ago
```

There is a `master` tag which seems to be hooked up to CI and is much fresher.  Again, I did not find the same issue could be reproduced on my machine, even using the latest tag.

**Comment by hmnd** [comment]
I am experiencing this same issue, too. I am on Solus. Anything I could provide that would be of help?

**Comment by Theaxiom** [comment]
@hmnd Just any additional information that you think may be relevant. Thanks! :)

**Comment by sshishov** [comment]
@hmnd , @dziurka , @lbssousa - guys, could you please provide the instruction how to reproduce?
How you are building, where you are building. I am also on MacOS host linux and everything builds and starts for me without issues. If it is not starting under Arch linux, then please provide the steps how to reproduce it and we will be glad to help you.

Looking forward for the cooperation.
