### ISSUE TITLE
how to set net.ipv4.tcp_congestion_control to bbr? 

### ISSUE THREAD

**Issue by DinoStray** [phusion/baseimage-docker#541]
I should do the following while I want open bbr support in ubuntu 18:

echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
sysctl -p

I do this success in host machine, but in baseimage, I got error:
sysctl net.ipv4.tcp_available_congestion_control
sysctl: cannot stat /proc/sys/net/ipv4/tcp_available_congestion_control: No such file or directory

**Comment by kingdonb** [comment]
I think you either need to use a privileged container, or you need to investigate the capabilities API of Docker
