### ISSUE TITLE
Failed to run apt upgrade when building based on latest image

### ISSUE THREAD

**Issue by MrXavierLin** [phusion/baseimage-docker#542]
The error is listed below, the problem arise since recently, before that there was no problem building images.

The step is

RUN apt upgrade -y 

`Configuration file '/etc/cron.weekly/fstrim'
 ==> Deleted (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** fstrim (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package util-linux (--configure):
 end of file on stdin at conffile prompt
Errors were encountered while processing:
 util-linux
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by jgardin** [comment]
Try 
`RUN apt-get --assume-yes --verbose-versions --allow-change-held-packages -o Dpkg::Options::="--force-confdef" upgrade`

**Comment by schuylr** [comment]
Here's the [Ubuntu issue](https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1589289) that caused this.

**Comment by MrXavierLin** [comment]
> Here's the [Ubuntu issue](https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1589289) that caused this.
> 
> Additionally the above solution by @jgardin didn't work for me, but running `echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf` before my apt and dpkg lines seems to do the trick.

Confirmed, this code really does its job

`
RUN echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf
RUN apt-get upgrade -y
`

**Comment by kingdonb** [comment]
Is there a PR or action needed based on this report? It's not clear from my reading of the report exactly how to reproduce this issue.

**Comment by svparijs** [comment]
I currently have this issue. My docker image based on baseimage is not able to build even with the above provided statements.

**Comment by svparijs** [comment]
Weird enough the docker build works in my CI environment but not locally.
