### ISSUE TITLE
Image Pull was Unsuccessful

### ISSUE THREAD

**Issue by kovkev** [phusion/baseimage-docker#545]
Hi contributors to baseimage-docker! Thanks for working on this repo!

I wanted to share with you an issue I hit tonight. I use bazel to pull images from hub.docker.com . I was looking to pull https://hub.docker.com/r/phusion/baseimage , tag 0.9.22 or tag latest. However, I was getting this issue:

```
2019/11/12 00:05:10 Image pull was unsuccessful: reading image "index.docker.io/phusion/baseimage:0.9.22": unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
```

It seems like Bazel won't support pulling schema 1 images. I don't know much about schema 1 or schema 2 version manifest images. I was wondering if baseimage-docker was considering updating to schema 2 version manifest images?

In the meantime, I'll try an alternative. Maybe I'll pull manually or I'll use another base image.

**Comment by Theaxiom** [comment]
@kovkev this is news to me, I have never heard of `Schema 1` vs `Schema 2`. I will have to look into this. As far as the latest version, it is `0.11`

**Comment by fatmcgav** [comment]
So it looks like the `schemaVersion` changed between `0.10.0` and `0.10.1`. 

```
$ docker manifest inspect phusion/baseimage:0.10.0
unsupported manifest media type and no default available: application/vnd.docker.distribution.manifest.v1+prettyjws
$ docker manifest inspect phusion/baseimage:0.10.1 |grep schemaVersion
        "schemaVersion": 2,
```

AFAIK, this isn't something that can be configured by the user, it's entirely dependant on the version of docker being used to build the image... 

This is supported by the fact that the `DockerVersion` used changed between `0.10.0` and `0.10.1`:
```
$ docker inspect phusion/baseimage:0.10.0 |egrep 'Created|DockerVersion'
        "Created": "2018-01-26T09:31:02.58538605Z",
        "DockerVersion": "1.9.1",
$ docker inspect phusion/baseimage:0.10.1 |egrep 'Created|DockerVersion'
        "Created": "2018-04-02T07:34:55.061517579Z",
        "DockerVersion": "17.09.0-ce",
```

**Comment by kingdonb** [comment]
This is something that I've seen warnings about in the docker client, not necessarily on this project though... "tell your registry admin they need to take action" LOL

https://docs.docker.com/registry/spec/deprecated-schema-v1/

You probably have seen this warning before, it looks like it's probably/definitely the same issue:

```
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the docker.io registry NOW to avoid future disruption.
```

**Comment by kingdonb** [comment]
It is suggested in the doc linked above that this can be resolved by pulling the image and pushing again.  I'm not sure what in-between version you must use in order to be new enough to use the modern schema version (and yet still old enough to tolerate the old schema version on pull...)

**Comment by Theaxiom** [comment]
I loathe Docker API's, they are not very good at developing API's. If they are changing the API, they should rev the registry to v3.
