### ISSUE TITLE
Support docker run --stop-signal option

### ISSUE THREAD

**Issue by jclaveau** [phusion/baseimage-docker#546]
I'm trying to set a timeout for a container following this hack `docker stop -t 15 $(docker run -d --stop-signal 2 --rm phusion/baseimage-docker) ` but as `docker stop` sends a `SIGTERM` first, my container is instantly stopped, as if `--stop-signal 2` wasn't considered by my_init.

So I have 2 questions:
+ Is my_init compatible with `--stop-signal` option
+ Should I use another approach like `timeout XX docker run -d --rm phusion/baseimage-docker` (I tried it with SIGKILL/SIGTERM/SIGINT without success), and can my_init handle this?

Thanks a lot for your work, it provides a really smooth path deeper into docker usage

PS: I followed this thread before thinking you could be interested by this question https://github.com/moby/moby/issues/1905 
PS2: I expected to use a timeout for this kind of usage https://github.com/phusion/baseimage-docker/#login_docker_exec.
PS3: Here is my usage of your image https://github.com/jclaveau/php-library-development-toolkit/blob/master/php#L42-L70

**Comment by kingdonb** [comment]
Today I got inspired to spend some time visiting baseimage-docker issue reports, and also came across this `@learnk8s` tweet which describes an acceptance test for appropriate behavior and graceful termination of a container upon receipt of SIGTERM.

https://twitter.com/learnk8s/status/1217676679201611778

I haven't tried this yet, but I have some experience and recall working on/reviewing some issues that updated the behavior of my_init with regard to how sigterm interception is propagated and handled.  Also, thank you for your kind words about the project!  I think for me, the purpose of making the nuts and bolts of working with containers more broadly accessible is one of the main reasons I like it too.

Are you still using baseimage-docker, and have you found any of the answers you were looking for in this report on your own already?
