### ISSUE TITLE
Is baseimage-docker unmaintained?

### ISSUE THREAD

**Issue by Fazel94** [phusion/baseimage-docker#547]
Hi, 
Activity on this project is pretty rare, the target of `baseimage-docker` really resonated with me. 

Is there a maintained alternative?

**Comment by DinoStray** [comment]
I feel sad about it

**Comment by kingdonb** [comment]
Are there issues that you would like to see more attention on?

The target of baseimage-docker is an LTS release, so major releases should only be needed about once every two years.  I see there are some unresponded issues, I will take a look this week.

I am just an occasional contributor, but I have found the maintainer(s) to be responsive.  I hear we are also accepting of volunteers!

**Comment by Theaxiom** [comment]
We have some changes in master which have not been released yet, I will create a new release soon.

**Comment by Theaxiom** [comment]
@Fazel94 What @kingdonb stated is correct, many people are using this image quite effectively. We are not really adding new features, we only address issues as they are reported for bug fixes, security and general maintenance. We are running the latest Ubuntu LTS release.
