### ISSUE TITLE
question: what is different between tini and my_init?

### ISSUE THREAD

**Issue by SimonHeimberg** [phusion/baseimage-docker#551]
For reaping processes and signal handling, there exists [tini](https://github.com/krallin/tini), which is included [in docker itself](https://docs.docker.com/engine/reference/run/#specify-an-init-process).
What is the difference to my_init of basimage-docker?

What I know:

tini | my_init
---|----
written in C | written in python
tini just starts one process (it is transparent) | my_init can run startup processes, <br/> starts runit and can start a custom command additonally to it, <br/> and it can start shutdown scripts
*reaps processes* | *reaps processes*
*handles signals* | *handles signals*

Is there anything important like functionality or reaping/signals or size or stability or ...

**Comment by Theaxiom** [comment]
Maybe something worth looking into, especially if it is C -- it should be faster than Python.
