### ISSUE TITLE
Is this project discontinued?

### ISSUE THREAD

**Issue by Fazel94** [phusion/baseimage-docker#552]
Hi, Is this project unmaintained? Because there is not much activity in it.
If so, Is there any maintained similar project around?

**Comment by Theaxiom** [comment]
@Fazel94 this project is maintained actively, it is just so rock-solid that it doesn't require much maintenance. It is tried, true and tested by millions of containers running globally! :)

**Comment by SuperSandro2000** [comment]
Let me destroy that: The Readme talks about Upstart in Ubuntu which is long replaced by Systemd.

**Comment by Theaxiom** [comment]
It is definitely being used, reliably, by countless users: https://hub.docker.com/r/phusion/baseimage

Pulls: 10M+ (and counting)

**Comment by Theaxiom** [comment]
@Fazel94 We just released a new version of baseimage.
