### ISSUE TITLE
bionic-1.0.0 released!

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#557]
CI pipeline is fixed, we have automatic builds and we will be able to release more often for minor updates. We are now working on getting baseimage up to speed with focal and that is currently merged into master. On behalf of the community, I would like to thank you all for your continued support!

**Comment by danryu** [comment]
Good job, fella!

**Comment by Theaxiom** [comment]
https://github.com/phusion/baseimage-docker/releases/tag/focal-1.0.0alpha1 is available for those who would like to test it out (pre-release).

Thanks @danryu -- this is a community effort and what an awesome community it is! <3

**Comment by walkero-gr** [comment]
@Theaxiom Tested it today on one of my projects and seems to work great. The good thing is that tested with snyk and there are 0 vulnerabilities with this image, against the previous, based on Ubuntu 18.04 where there are 136 medium and minor issues.

On the other hand the image I build based on baseimage, increased size by 60MB.

Good work guys. Looking forward to test new versions.

**Comment by Theaxiom** [comment]
@walkero-gr thanks for the feedback!
