### ISSUE TITLE
Fix arch build issues (arm, s390x)

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#558]
As reported in https://github.com/phusion/baseimage-docker/issues/554 -- there is a build issue: https://travis-ci.org/github/phusion/baseimage-docker/jobs/694582397#L1806

**Comment by samip5** [comment]
@Theaxiom What's the current status?

**Comment by Theaxiom** [comment]
@samip5 I will have to take a look, because last time I checked the builds were fine. This is relating to pull requests where their branch does not have access to the protected variables. (IIRC)

**Comment by samip5** [comment]
@Theaxiom I'm talking about focal build, which is still failing. At least ARM variant.

**Comment by Theaxiom** [comment]
@samip5 thanks for clarifying. :)

**Comment by samip5** [comment]
Please fix the build error. It's preventing CI to push the actual manifests and thus making the tags correctly for each architecture.

https://travis-ci.org/github/phusion/baseimage-docker/jobs/730061275

**Comment by Theaxiom** [comment]
Something is wrong with Travis-CI, I am having to re-configure the repository integration from scratch. I am currently working on it.

**Comment by Theaxiom** [comment]
@samip5 I have temporarily disabled the failing arch builds.

**Comment by skliarie** [comment]
Any progress on this? It blocks phusion container release for ubuntu 20.04.. More than year after it been released..

**Comment by sshishov** [comment]
Can we add more maintainers here? I guess that @Theaxiom is very busy.
I guess that some people are willing to support the project and make a change. Unfortunately, we cannot do anything with Pipeline as we do not have any permissions here.

**Comment by Theaxiom** [comment]
@sshishov I have already put out a call to action for maintainers and we have added 2 more individuals.
