### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by greenlogles** [phusion/baseimage-docker#562]
Hello

Starting from today I'm facing issue with pulling latest docker image:
``` 
docker pull phusion/baseimage
Using default tag: latest
Error response from daemon: manifest for phusion/baseimage:latest not found: manifest unknown: manifest unknown
```
I've seen that docker hub has updated tag names like 'master-amd'. Would it be at all possible to use 'latest' tag for newly pushed images ?

Thank you

**Comment by p0wermilker** [comment]
I have the same problem, yesterday it worked normally but right now i can't pull the image, some solution?

**Comment by Theaxiom** [comment]
When using baseimage-docker you have to specify a version, this is to protect you from issues down the road (predictability and traceability). If you insist on using unstable versions you can simply use `master-<arch>` for your tag. Replace `<arch` with the architecture you want.

The `latest` images was over 1 year old and people were still using it, without even knowing what it represents. This is why it was removed. You should not blindly use `latest` and assume what it represents, this goes for any image on Docker Hub. There is no traceability to know which branch it was built from and you have to take the project's word for it.

You can trace our images through the pipeline and see the Travis-CI build and ensure that the images which represent the branch are exactly the same.

Here is an excellent blog post on the point: https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

There are many other resources across the internet which detail why not to use `latest` tag for Docker. If you really want to change my mind, please read the blog post and with that in mind, do research on the internet and propose a solid solution and case as to why `latest` tag should exist, as opposed to having tags which actually represent what is being built. I will definitely consider any new information, especially if it comes with a strong case.

-- Travis

**Comment by p0wermilker** [comment]
I understand why i is not recomendable use the latest tag but in the phusion when i enter to docker hub i don't more tags, for that reason i always used the latest, Where is the reference to the tags of this image?

**Comment by Theaxiom** [comment]
@p0wermilker https://hub.docker.com/r/phusion/baseimage/tags

**Comment by jjborie** [comment]
Hi,

Can you tell us what is the equivalent of the latest default latest?

Thanks

**Comment by greenlogles** [comment]
Thanks @Theaxiom for detailed explanation.
It's known that `latest` tag is not guarantee any compatibility with previous versions (the same like git master branch)

**Comment by SuperSandro2000** [comment]
@jjborie 
> When using baseimage-docker you have to specify a version, this is to protect you from issues down the road (predictability and traceability). If you insist on using unstable versions you can simply use master-<arch> for your tag. Replace <arch> with the architecture you want.

**Comment by Theaxiom** [comment]
@jjborie you can get latest release tags here: https://github.com/phusion/baseimage-docker/releases

**Comment by Theaxiom** [comment]
@jjborie you can also find (all) the different arch tags here: https://hub.docker.com/r/phusion/baseimage/tags

**Comment by samip5** [comment]
This issue has been stale for more than a year, I'm going to close this.
