### ISSUE TITLE
`/etc/container_environment/PATH` ignored

### ISSUE THREAD

**Issue by bovender** [phusion/baseimage-docker#565]
I'm trying to set the `PATH` variable for my container, but it is not being picked up:

```
root@b83a0bcb0ea5:~# cat /etc/container_environment/PATH
/home/app/rails/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@b83a0bcb0ea5:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Am I missing something, or is this a bug?

I saw the merged PR #86, but it does not concern `PATH`?

**Comment by Theaxiom** [comment]
I do not currently have the time to investigate this, perhaps @kingdonb or @hyperknot ?
