### ISSUE TITLE
[Q] one-off command still starts init, README suggests it shouldn't

### ISSUE THREAD

**Issue by laur89** [phusion/baseimage-docker#566]
[Readme](https://github.com/phusion/baseimage-docker#running-a-one-shot-command-in-a-new-container) states:

>However the downside of this approach is that the init system is not started. That is, while invoking COMMAND, important daemons such as cron and syslog are not running.

From this I gather following example should _not_ start cron, nor execute scripts in `/etc/my_init.d/`:

    docker run -it --rm -e SOME_ENV_VAR=testvalue layr/borg-mysql-backup:0.0.5 -- cat /env_vars.sh

Yet `/env_vars.sh` is created by [setup.sh](https://github.com/laur89/docker-borg-mysql-backup/blob/0.0.5/setup.sh#L46), which is executed by [init](https://github.com/laur89/docker-borg-mysql-backup/blob/0.0.5/Dockerfile#L20)
(Yes, I do know we're supposed to source /etc/container_environment.sh instead of collecting env vars the way it's done here).

So what's going on? How come I don't need to invoke `cat` via /sbin/my_init as described in readme?

**Comment by laur89** [comment]
It's because my image sets `/sbin/my_init` as ENTRYPOINT, not CMD, so everything gets executed via it anyway.

**Comment by Theaxiom** [comment]
@laur89 you can override the entrypoint on startup.

**Comment by laur89** [comment]
Nah it's the proper way to start phusion-based containers IMO. I was just perplexed as to why the startup scripts were executing when running one-off commands; but that explains it and all's good.
