### ISSUE TITLE
Move away from TravisCI?

### ISSUE THREAD

**Issue by PikachuEXE** [phusion/baseimage-docker#572]
https://news.ycombinator.com/item?id=25338983
Maybe TravisCI still runs for this project but not sure for how long
Might be good to start the preparation early

**Comment by Theaxiom** [comment]
GitHub has CI now, we should definitely leverage it. Thank you for opening this issue!

**Comment by samip5** [comment]
You can actually do multi-arch images quite easily with GitHub actions. Just an FYI.

P.S The Travis builds are currently [failing](https://travis-ci.org/github/phusion/baseimage-docker) one major task, maybe drop support for ppc64le and i386?

**Comment by Theaxiom** [comment]
@samip5 yeah we can do that, sorry I have been completely swamped. I will take a shot at fixing the builds.

**Comment by samip5** [comment]
@Theaxiom Seems that the builds for this repository on Travis CI has cheased so we are going to have to move to travis-ci.com OR Use Github Actions. Which one do you prefer?

**Comment by Theaxiom** [comment]
@samip5 GitHub actions, since it is native.

**Comment by samip5** [comment]
Alright, I'm going to be working on getting the Github Actions workflow done for this.

**Comment by Theaxiom** [comment]
@samip5 My email address is travis.rowland@d11y.co -- drop me an email so we can be connected outside of GitHub. 👍

**Comment by samip5** [comment]
> @samip5 My email address is [travis.rowland@d11y.co](mailto:travis.rowland@d11y.co) -- drop me an email so we can be connected outside of GitHub.

Dropped you an email.
