### ISSUE TITLE
When will focal be available?

### ISSUE THREAD

**Issue by rolintoucour** [phusion/baseimage-docker#573]
Hi.

https://hub.docker.com/r/phusion/baseimage/tags?page=1&ordering=last_updated indicates that the focal version is alpha for 3 months. When do you plan to release it?

The repo doesn t seem to be frequently maintenained. will there still be updates and fixes?

Thx.

**Comment by Theaxiom** [comment]
@rolintoucour we need to ensure stability, you can always download the focal alpha image from Docker Hub and provide feedback! We are always accepting contributions and feedback, this baseimage is extremely stable and has been around for quite some time, that is why there are not many changes happening. Most changes are really to keep everything up to date with patches, etc.

**Comment by yakutovicha** [comment]
Hello,

Numpy drops support of python 3.7 in December (see [this table](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table)). The same happens to our AiiDA project (see [here](https://github.com/aiidateam/AEP/tree/master/003_adopt_nep_29#detailed-explanation)) which distributed through Docker images that we base on the Phusion base image.

@Theaxiom when you say

> we need to ensure stability

What exactly do you mean by this? Are the stability criteria known/documented? I think having a clear understanding of what should be done would help us to help you :).

**Comment by Theaxiom** [comment]
@yakutovicha we haven't received any bug reports against focal, so we can bump it up to release.

**Comment by Theaxiom** [comment]
I just released focal-1.0.0 -- thank you!
