### ISSUE TITLE
Ubuntu does not use Upstart any more

### ISSUE THREAD

**Issue by guettli** [phusion/baseimage-docker#577]
README:

> Ubuntu is not designed to be run inside Docker. Its init system, Upstart, assumes  ....

Ubuntu does not use Upstart any more

**Comment by Theaxiom** [comment]
@guettli yes, baseimage-docker was created a very long time ago and has been maintained all this time. That was true when the statement was written and this comes from a blog post which was associated with the release of baseimage-docker.
