### ISSUE TITLE
Looking for core maintainers

### ISSUE THREAD

**Issue by Theaxiom** [phusion/baseimage-docker#579]
My schedule is extremely hectic at my day job and my start-up is gaining momentum. Full transparency, I could use some help here with getting new versions out, reviewing pull requests, etc. If anyone is interested, please post here so we can connect. This project is far from dead, but it does indeed need a bit of TLC in order to keep it up to date, which I am currently unable to provide. Thanks so much!

**Comment by anlek** [comment]
Hello,

Thank you for sharing and asking for help.

I was wondering how much of a commitment this is. What I mean is, is it 2 hours a week or 2 hours a day of reviews and whatnot. What would a good maintainer need to know to take this task on?

Thanks,
Andrew

**Comment by Theaxiom** [comment]
@anlek those are fantastic questions!

1. This is not a huge commitment, this product is extremely stable and doesn't receive many pull requests. I would say that even 2 hours per month to start is extremely helpful!
2. A good maintainer needs to be familiar with CI/CD, some bash scripting and a bit of python. They also must be detail oriented and stand for quality.

Please let me know if you have any further questions. <3

**Comment by ojotoxy** [comment]
@Theaxiom  I'm a big fan of this project and think I could help out as well if needed.

**Comment by sshishov** [comment]
Hello @Theaxiom , I also can try to help if needed? At least I can look over the issues and try to fix what I can understand :D

**Comment by Theaxiom** [comment]
@sshishov thanks for your interest, please feel free to submit any pull requests for submission. It is greatly appreciated! :)

**Comment by samip5** [comment]
I can also help if needed, I could work on getting the CI moved  to Github Actions? :)

**Comment by Theaxiom** [comment]
@samip5 thank you for offering, I have sent you an invite to become maintainer. Your support is greatly appreciated!

**Comment by Theaxiom** [comment]
@sshishov I have invited you as a maintainer, thank you! Your support is greatly appreciated!
