### ISSUE TITLE
Getting tons of debconf messages unless TERM is set to linux

### ISSUE THREAD

**Issue by nikolay** [phusion/baseimage-docker#58]
```
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 19.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```

**Comment by micheleorsi** [comment]
ENV DEBIAN_FRONTEND noninteractive
worked as well to me!

**Comment by christianbundy** [comment]
:+1: for `ENV DEBIAN_FRONTEND noninteractive`

**Comment by christianbundy** [comment]
Why isn't `ENV DEBIAN_FRONTEND noninteractive` part of the default Dockerfile?

**Comment by brunowego** [comment]
@christianbundy :+1:

**Comment by HadesArchitect** [comment]
The 'ENV DEBIAN_FRONTEND noninteractive' should be in the default Dockerfile or, at least, in the documentation, imho.

**Comment by christianbundy** [comment]
My PR (#252) was rejected, and I doubt that this will ever be resolved due to docker/docker#4032

**Comment by FooBarWidget** [comment]
As discussed in docker/docker#4032 and related discussions, setting `ENV DEBIAN_FRONTEND noninteractive` by default is a bad idea. What people *really* want is a way to set environment variables during 'docker build' without persisting them to the final container image. Unfortunately this is not something that we can fix, only the Docker guys can do this.

**Comment by christianbundy** [comment]
@FooBarWidget Instead, could we set `ENV DEBIAN_FRONTEND noninteractive` at the start of the build, and reset it back to the default before running the final command?

**Comment by FooBarWidget** [comment]
I haven't tried but I think that would work.

**Comment by aureliojargas** [comment]
Using `ARG` instead of `ENV` would set the variable just for the build phase.

**Comment by QianJin2013** [comment]
Although this is closed. I find when use `sudo` there need special attention.

NG: `RUN sudo apt-get install -y xxxxxxx`
OK: `RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install -y xxxxxxx`

Good luck.

**Comment by ebuildy** [comment]
Why this is not "embedded" in the base image already?

**Comment by hyperknot** [comment]
I think the right choice is to set

    ENV DEBIAN_FRONTEND noninteractive

At the beginning of each Dockerfile and set

    ENV DEBIAN_FRONTEND teletype

At the end of each. `noninteractive` is needed for all the build steps, while `teletype` is needed for interactive configuration, the user might want to do inside a running container.

**Comment by Chris-Hu** [comment]
Set your variable in one command with the apt-get to keep the context

RUN export DEBIAN_FRONTEND=noninteractive && apt-get .....

**Comment by OnkelTem** [comment]
@jjqq2013 It's sort of off-topic, but why one would need to use `sudo`s in... Dockerfile? 

As reading all the discussion and some linked ones, I think the best thing to do is to IGNORE the warning messages. It's just one less thing we need to think about.

**Comment by jjqq2013** [comment]
@OnkelTem this is a good question.  

1. The root user inside docker container could compromise the real host where docker is running, by some tricks. Theoretically, Docker, as a kernel-shared container technology, it is not and will never, be considered as the most secure isolation solution. 

2. There are some anti-root software which prevent itself from being run with root user. Such as yoman.

**Comment by hyperknot** [comment]
Sudo makes no sense for building containers.

What you want for security is to use setuser to drop the permissions when
running a service app.

**Comment by OnkelTem** [comment]
@jjqq2013 totally greed, but already answered by @hyperknot  above - building is not running.
I personally use `su` (not sudo which is to be installed first, then configured sudoers - pain) for running  processes inside container upon startup.

**Comment by jjqq2013** [comment]
hi guys, do not misunderstand me. I am not meaning to push an issue of this base image(i don't event know what it is),

i just wanted to appreciate you because your answer of "DEBIAN_FRONTEND =noninteractive" solved my problem, 

and just wanted to contribute more comment about it when used in sudo (Whatever you think of sudo in docker container,  there are some cases you sudo being used)

That's all. Good luck.

**Comment by Taisgeal** [comment]
I am brand new to Docker, but on an Ubuntu 16.04 LTS box, I did
apt install dialog

and this warning message went away.

**Comment by kamalverma04** [comment]
Just add the below line at the beginning of the Dockerfile to solve the issue.

ARG DEBIAN_FRONTEND=noninteractive

**Comment by KeithTt** [comment]
@famelis 👍

**Comment by johnxy84** [comment]
You could also add an ARG before running apt-get like so
`ARG DEBIAN_FRONTEND=noninteractive`

**Comment by ishandutta2007** [comment]
`ENV DEBIAN_FRONTEND noninteractive` didn't work for me
neither did `ARG DEBIAN_FRONTEND noninteractive` 
but `RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections` did

**Comment by PikachuEXE** [comment]
I just add `DEBIAN_FRONTEND=noninteractive` just after `RUN` with `apt-get install`
```docker
RUN \
  DEBIAN_FRONTEND=noninteractive; \
  apt-get update \
  && \
  apt-get install -y --no-install-recommends \
    build-essential \
    nodejs \
    git \
    curl \
    automake \
  && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by dineshrathee12** [comment]
EXAMPLE With Success:
================

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
sudo apt-get install -y -q <package name>


It works fine for me.

**Comment by dsanpedro** [comment]
> I use docker on Debian/Jessie.
> 
> In the Dockerfile of a container
> 
> ```dockerfile
> FROM debian:sid
> ```
> 
> I set, before the first `apt-get`,
> 
> ```dockerfile
> RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
> ```
> 
> and everything is ok.

Thanks. This helped in an unrelated problem.

**Comment by sanzenwin** [comment]
> I use docker on Debian/Jessie.
> 
> In the Dockerfile of a container
> 
> ```dockerfile
> FROM debian:sid
> ```
> 
> I set, before the first `apt-get`,
> 
> ```dockerfile
> RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
> ```
> 
> and everything is ok.

Helpful.
