### ISSUE TITLE
`my_init` one-shot command exits with OOMKill, but container still reports successful execution

### ISSUE THREAD

**Issue by indiebrain** [phusion/baseimage-docker#583]
Application Base Image: phusion/passenger-customizable:0.9.35
Image digest: d1d611f7ba99

The [baseimage-docker documentation for running "one-shot" commands](https://github.com/phusion/baseimage-docker#running-a-one-shot-command-in-a-new-container) indicates that one should probably use the `/sbin/my_init -- COMMAND ARGUMENTS` form to run one-shot commands to ensure that "important daemons such as cron and syslog" are running and to avoid orphaning child processes.

We use this form to execute "one-shot" commands during our deployment process. Specifically we have a Rails application on which we run database migrations and data transformations as a pre-deployment step. The application shipped a faulty migration which caused the container's `bin/rails db:migrate` process to be OOMKilled. The `bin/rails db:migrate` process exits with status 137 (OOMKilled), however the container exits with status 0 (Succeeded). This creates a confusing scenario where the container fails to run the application process it was asked to perform, but the container reports that it was successful. In our case, this causes deployments report as being "successful" even though they should have been "failed" and halted because the migration process was OOMKilled. This resulted in the deployment of application state for which the database schema was NOT present.

For context, I've found this potentially related - seemingly stale - issue which seem to fit what I see as the general pattern - some one-shot container runs a process managed by `my_init fails`, but `my_init` reports a "Succeeded" status code:

- https://github.com/phusion/baseimage-docker/issues/420

**Comment by Theaxiom** [comment]
You should be able to catch the failure in your script and then kill PID1 to cause a non-zero exit code.

**Comment by indiebrain** [comment]
@Theaxiom , thanks for the reply. 

The above example, I'm using the "one-shot" command form as documented in the README: `/sbin/my_init -- COMMAND ARGUMENTS`. I've been using this to run one-shot commands / scripts which I do not own, such as `bin/rails`, `yarn`, etc. I believe the suggestion "You should be able to catch the failure in your script" infers my_init assumes that `COMMAND` is always some script which I own if I want to make sure `my_init` will have an appropriate exit status?

Additionally, I'm a bit uncomfortable with "...then kill PID1 to cause a non-zero exit code." This assumes that I only ever run said COMMAND / script in an environment where `my_init` is PID 1 - essentially the COMMAND / script needs to KNOW that it's ok to kill the init sytem. At the very least, this limits the usefulness / reusability of such "scripts", and at worst could prove harmful if such a script is run in a context where `my_init` is NOT PID 1. Does that make sense?

The above concerns aside, it seems like the issues described in https://github.com/phusion/baseimage-docker/issues/420 would STILL present a problem, no?
