### ISSUE TITLE
Duplicate logrotate entries

### ISSUE THREAD

**Issue by Konnichy** [phusion/baseimage-docker#584]
Hello,

Using another project built on this one, I periodically received the following notification by email:
```
/etc/cron.daily/logrotate:
error: /etc/logrotate.conf:22 duplicate log entry for /var/log/wtmp
error: /etc/logrotate.conf:29 duplicate log entry for /var/log/btmp
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

After investigating, I notice that duplicates are introduced by your `logrotate.conf`, installed at the end of `syslog-ng.sh`, which contains `btmp` and `wtmp` sections. This doubles with files `/etc/logrotate.d/btmp` and `/etc/logrotate.d/wtmp`, which are already installed by the official package, just one line above in your script.

**Comment by Theaxiom** [comment]
@Konnichy could you please submit a PR to resolve this? It would be greatly appreciate, thank you!

**Comment by Theaxiom** [comment]
This was resolved per PR.
