### ISSUE TITLE
Can't pull image in CoreElec with kernel 4.9.113 aarch64 and Docker version 19.03.15

### ISSUE THREAD

**Issue by ramoncio** [phusion/baseimage-docker#593]
I run CoreELEC in different amlogic boxes, and it has docker support. 
This image would be great to be able to have a functional ubuntu on top of CoreELEC or LibreELEC, there are arm64 images, but none of them have baseimage-docker features.

Seeing this file, I guess you are adding support for different architectures?
https://github.com/phusion/baseimage-docker/pull/567/commits/1f44ae98c0f2ca79717b4fddb024409905a2feb2
but it doesnt work for me, or maybe I'm doing something wrong.

`CoreELEC:~ # docker run --rm -t -i phusion/baseimage:focal-1.0.0 /sbin/my_init -- bash -l
Unable to find image 'phusion/baseimage:focal-1.0.0' locally
focal-1.0.0: Pulling from phusion/baseimage
docker: no matching manifest for linux/arm/v8 in the manifest list entries.
See 'docker run --help'.
CoreELEC:~ # uname -a
Linux CoreELEC 4.9.113 #1 SMP PREEMPT Sun May 30 00:24:57 UTC 2021 aarch64 GNU/Linux
CoreELEC:~ # docker --version
Docker version 19.03.15, build 99e3ed89195c4e551e87aad1e7453b65456b03ad`

Thanks a lot for your great work with this project!!

**Comment by ramoncio** [comment]
I see it works in another Amlogic box with armbian, with a newer 5.9 kernel. 
Any idea why in CoreELEC I get this "docker: no matching manifest for linux/arm/v8 in the manifest list entries" error??

`root@h96max:~# docker pull phusion/baseimage:focal-1.0.0
focal-1.0.0: Pulling from phusion/baseimage
80bc30679ac1: Pull complete 
9bf18fab4cfb: Pull complete 
5979309c983a: Pull complete 
1357ffa77d61: Pull complete 
71f46679fd32: Pull complete 
85baf5ed4b49: Pull complete 
Digest: sha256:fe61f3b11bc0f434612e12aa2ecf5d692775faec714ceb689d1b796115deb11c
Status: Downloaded newer image for phusion/baseimage:focal-1.0.0
docker.io/phusion/baseimage:focal-1.0.0
root@h96max:~# uname -a
Linux h96max 5.9.0-arm-64 #20.10 SMP PREEMPT Wed Oct 14 12:04:42 MSK 2020 aarch64 aarch64 aarch64 GNU/Linux
root@h96max:~# docker --version
Docker version 19.03.13, build 4484c46
`

**Comment by ramoncio** [comment]
Copied that image to CoreELEC and it works just fine!

**Comment by samip5** [comment]
Because currently the build is failing some builds which in turn is making it not execute the manifest task which is vital for manifests.

**Comment by Theaxiom** [comment]
@samip5 how do we resolve this?

**Comment by samip5** [comment]
> @samip5 how do we resolve this?

This is due to missing manifest which is due to the CI pipeline not getting all the way to the task which pushes the manifest. That's the last step which is not being ran due to the build errors before it.

**Comment by Theaxiom** [comment]
@samip5 I've added you as maintainer, would you please create a PR to master to fix this and I will merge it? Thank you, I appreciate you! <3

**Comment by samip5** [comment]
> @samip5 I've added you as maintainer, would you please create a PR to master to fix this and I will merge it? Thank you, I appreciate you! <3

Yeah, will do that.

**Comment by samip5** [comment]
There is now a focal-1.1.0 image, which you may want to try.

**Comment by samip5** [comment]
A month has passed, without any input from Author, marking as stale, and closing automatically if no further action occurs.
