### ISSUE TITLE
Changelog for `focal-1.1.0`

### ISSUE THREAD

**Issue by mserranom** [phusion/baseimage-docker#602]
# Details

`focal-1.1.0` doesn't appear in [Github releases](https://github.com/phusion/baseimage-docker/releases), but it's been released to [Dockerhub](https://hub.docker.com/layers/phusion/baseimage/focal-1.1.0/images/sha256-12aeeecfff1a6af0b3b65291aba13f7641d1f3fd6d6c4098507702f33c03c096?context=explore).

Digging in [the Discord channel](https://discord.com/channels/883039811823357952/883040255962415105/895020889475784755) I understand `focal-1.1.0` is a stable release, just not published in Github.

The [Changelog](https://github.com/phusion/baseimage-docker/blob/d454ef62715d1dd8df637470517c17b2fb6f5c79/Changelog.md) still points to Github Releases. Would it be possible to have a changelog for this new release? Thanks!

**Comment by Theaxiom** [comment]
@mserranom I found out what happened, someone named a branch using our release naming scheme and it automatically built and pushed a corresponding image (we build and push all branches for testing purposes).

focal-1.1.0 was not released actually, so we are going to figure out how to prevent this from happening in the future. Thank you for bringing this to our awareness.

**Comment by mserranom** [comment]
Thanks @Theaxiom
