### ISSUE TITLE
hi. rocky8 or centos8 not support?

### ISSUE THREAD

**Issue by Neptunium1129** [phusion/baseimage-docker#605]
in cent8, rocky8

There is a problem with the zombie process.

**Comment by samip5** [comment]
Please explain in more detail. What's the actual issue? We also don't provide images for Rocky nor CentOS.

**Comment by Neptunium1129** [comment]
env : https://hub.docker.com/r/rockylinux/rockylinux

install images > Dockerfile for systemd base image

service stop -> zombie process was occured

**Comment by Neptunium1129** [comment]
![image](https://user-images.githubusercontent.com/32185134/147843785-3d7b5a82-ce22-4a4c-8d5f-3513b48f39df.png)

**Comment by Neptunium1129** [comment]
solved , use option-> --init
