### ISSUE TITLE
There is a missing tag for focal-1.1.0

### ISSUE THREAD

**Issue by josegonzalez** [phusion/baseimage-docker#607]
# Details

The tag exists on [docker hub](https://hub.docker.com/layers/phusion/baseimage/focal-1.1.0/images/sha256-b97106632d63119a59c071e32c119bd2d85f526cabb37552faf93fdff87f6ff2?context=explore) but not on github.

Seems it happened somewhere [here](https://github.com/phusion/baseimage-docker/compare/focal-1.0.0...master#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R24).

**Image version:**

focal-1.1.0

**What steps did you take and what happened:**

I tried to find the release notes for focal-1.1.0 and couldn't.

**What did you expect to happen:**

A github tag/release for the respective git commit..

**Anything else you would like to add:**

This is a great project.

**Additional Information:**

N/A

**Comment by samip5** [comment]
If I remember right, @Theaxiom was supposed to delete it from Docker Hub?

**Comment by josegonzalez** [comment]
Ah nooo please don't delete it, I'm using it in dokku now because the focal-1.0.0 one doesn't have an arm release.

**Comment by samip5** [comment]
Related: https://github.com/phusion/baseimage-docker/issues/602

**Comment by samip5** [comment]
@josegonzalez There's a new version available with a changelog, so I'm closing this even though 1.1 doesn't have one.

**Comment by josegonzalez** [comment]
Love it!
