### ISSUE TITLE
pull error

### ISSUE THREAD

**Issue by nbctcp** [phusion/baseimage-docker#609]
# Details
# docker pull phusion/baseimage
Using default tag: latest
Error response from daemon: manifest for phusion/baseimage:latest not found: manifest unknown: manifest unknown

**Image version:**
latest today

**What steps did you take and what happened:**

**What did you expect to happen:**

**Anything else you would like to add:**
no image if I pull from portainer

**Additional Information:**

**Comment by samip5** [comment]
What is the outpot of `uname -m` on that system you tried to pull from?

**Comment by cu** [comment]
As far as I can see, there's no `latest` tag on docker hub: https://hub.docker.com/r/phusion/baseimage/tags?page=1&name=latest

There are 3 `latest-<arch>` but those are 3 years old.

**Comment by samip5** [comment]
That's because we use tagged version releases rather than latest so not a bug.
