### ISSUE TITLE
Add anacron to the system services

### ISSUE THREAD

**Issue by olberger** [phusion/baseimage-docker#61]
As the docker containers aren't always up all time, particularly on the dev side, I find it convenient to have anacron making sure that cronjobs are executed once in a while, for example for log rotations, etc.

I've modified image/system_services.sh to add "$minimal_apt_get_install anacron" in my "Debian fork" (https://github.com/olberger/baseimage-docker/tree/debian).

Or maybe this is only useful in Debian environment, and not applying to the base Ubuntu system ?

Hope this helps.

**Comment by FooBarWidget** [comment]
I don't think anacron is useful enough to be included in the default baseimage. I think it should be opt in.
