### ISSUE TITLE
syslog-ng warning

### ISSUE THREAD

**Issue by cairoapcampos** [phusion/baseimage-docker#616]
# Details

**Image version:** phusion/baseimage:jammy-1.0.0

**What steps did you take and what happened:**  When I view the logs (docker-compose logs) I get the message.

**What did you expect to happen:** I believe this message should not appear in the log.

**Anything else you would like to add:**

**Additional Information:**

**Message**

WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.35 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.25'
[2022-06-30T15:08:01.312610] WARNING: The internal_queue_length stat counter has been renamed to internal_source.queued. The old name will be removed in future versions; config-version='3.25'

**Comment by burgerrg** [comment]
See pull request https://github.com/phusion/baseimage-docker/pull/615.
