### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by gr8bit** [phusion/baseimage-docker#622]
(Inspired by https://github.com/phusion/passenger-docker/issues/350)

There currently are a few security vulnerabilities in the image, one of which even is of severity HIGH:
![Bildschirm­foto 2023-01-07 um 21 55 04](https://user-images.githubusercontent.com/341793/211170061-d617c4e0-9d35-45d5-939c-ef7db40142d5.png)

Would it be possible to update the packages in the image to get rid of those vulnerabilities?

**Comment by samip5** [comment]
@gr8bit Which baseimage version was used? master is 11 months old and there are newer ones.

**Comment by oozone** [comment]
Where can we find the newer images, it's not clear, thanks.

**Comment by gr8bit** [comment]
phusion/passenger-docker uses phusion/baseimage-docker:master and the Passenger-image version I was commenting on here was built on Dec 20th. So it probably used that 11 month old one...

**Comment by samip5** [comment]
> Where can we find the newer images, it's not clear, thanks.

We have been making releases when a new image is available (it gets built on release): https://github.com/phusion/baseimage-docker/releases

Latest is currently jammy-1.0.1.

**Comment by samip5** [comment]
Closing as invalid.
