### ISSUE TITLE
Base on Ubuntu 22.04 LTS?

### ISSUE THREAD

**Issue by gr8bit** [phusion/baseimage-docker#624]
# Details

As I'm getting more and more security concerns in my automated reports (Trivy), I'd like to ask if you have plans to update the baseimage to Ubuntu 22.04 anytime soon?
I'd love to base my images upon that and it would also affect the Passenger™ images which I'm also happily using. :)

**Comment by samip5** [comment]
It already is, you're more than likely using a tag that's not being pushed to anymore.
Please see available tags eg here: https://github.com/phusion/baseimage-docker/pkgs/container/baseimage
