### ISSUE TITLE
/bin/sh: 1: Syntax error: "(" unexpected on startup

### ISSUE THREAD

**Issue by adamlwatson** [phusion/baseimage-docker#640]
# Details

**Image version:**
phusion/baseimage:18.04-1.0.0-amd64

**What steps did you take and what happened:**
I'm building the image using Packer for use with Kubernetes, and these are the Docker commands I've added to the build:

  "USER root",
  "CMD ['/sbin/my_init']",
  "EXPOSE 11211",

I'm also adding a single runit script to spin up a memcached daemon, as in the example provided. The script is saved to `/etc/service/memcached`, and the contents of the script are:
```
        #!/bin/sh
        memcached -v -I 2m -p 11211 -u memcache -P /var/run/memcached/memcached.pid >> /var/log/memcached.log 2>&1
```

**What did you expect to happen:**
When the image is spun up via K8S, I'd expect the memcached daemon to run.

Instead, the container goes into CrashLoopBackOff status, and the logs simply state:
`/bin/sh: 1: Syntax error: "(" unexpected`

**Anything else you would like to add:**

I can add the /sbit/my_init command as an ENTRYPOINT, and that works as expected, however since it's started under a shell PID1 will not properly accept SIGTERM signals, which are necessary for graceful shutdowns.

**Additional Information:**

**Comment by samip5** [comment]
You're using an obsolete tag, closing as won't fix.

**Comment by adamlwatson** [comment]
Actually, I made a mistake in my report. I'm actually using the `jammy-1.0.2` image. I've also found a way to circumvent this in terraform, if you're interested in a solution.
