### ISSUE TITLE
Is /sbin/my_init redundant?

### ISSUE THREAD

**Issue by edegaudenzi** [phusion/baseimage-docker#642]
# Details

**Describe the solution you'd like:**
I didn't quite get my head around it, but I'd like to have a collective brainstorming on the topic: **is /sbin/my_init redundant nowadays?** Unfortunately I could not answer to myself and at a very first sight it seems it could be removed from the image in favour of simplicity and an additional process saved from the execution.

**Anything else you would like to add:**
Starting with (Docker) Compose version 2.2 you can define the yaml property  `init:True` which, as reported in the [official documentation](https://docs.docker.com/reference/compose-file/services/#init):
> runs an init process (PID 1) inside the container that forwards signals and reaps processes. Set this option to true to enable this feature for the service.

**Additional Information:**
Now, this seems quite an explicit answer to the topic in subject, but I was wondering if there could be additional considerations that still make `/sbin/my_init` essential nowadays?

**Comment by tinco** [comment]
Yes, you are correct, it effectively replaces the need for a `my_init` for users. While it is a useful addition, it is not enabled by default, nor is it possible to activate it from a docker image configuration (i.e. through the `Dockerfile`). Without that we have no way of guaranteeing a user of the container is running it correctly, so we must still rely on `my_init` to ensure users can just run the image without extra configuration.

Frankly it seems to be more of a handy feature to fix broken images, than that it is a proper solution for images like ours.

Unless the docker team (or really the OCI) provides for a way to indicate that the container does not reap its own processes, we must include a system for reaping the processes spawned by Passenger.
