### ISSUE TITLE
README should mention how to use the current (or earlier) version

### ISSUE THREAD

**Issue by richb-hanover** [phusion/baseimage-docker#643]
# Details

I'm trying to revive an old project (that used 0.9.22 (!)). I see the README advises use of `FROM phusion/baseimage:<VERSION>` I couldn't figure out what version number to use (using `latest` didn't seem to work).

The README should have a **Current Status** section that lists the current version that displays the exact `FROM ...` to use and a pointer to the list of earlier "production" versions? 

Many thanks.

**Comment by samip5** [comment]
Sorry but I'm gonna mark this as won't fix. I don't believe we should be holding the users hand in figuring this one out.

**Comment by richb-hanover** [comment]
@samip5 Hmmm... I don't think of it as "handholding". It's more like saving each potential new person five minutes... But that's besides the point. I spent the five minutes, and would offer the following for the README:

---
### Current Status

The current version of the image is always available from the **Releases** on the [home page](https://github.com/phusion/baseimage-docker). To use that image, use `docker pull phusion/baseimage:release` where `release` is the name shown at the top of the page.

---

Advantages:
* It answers the most common question: how do I use this?
* It doesn't require maintenance - all the work goes into updating the Release page (which you do anyway)

**Comment by Theaxiom** [comment]
@richb-hanover Thank you for the feedback, please submit a PR to the README and we will review and possibly integrate your changes. This is a community project! :)

**Comment by laur89** [comment]
I'm with u/samip5 here - finding docker images from docker hub is not phusion-specific, so giving explicit instructions do seem too much of a hand-holding.

**Comment by richb-hanover** [comment]
OK. It's your project.

I will note that as a symptom of #646, the project seems broken to newcomers. (Hint: _":latest"_ doesn't work. And your decision not to include instructions for getting the right tag the first time doesn't seem sensible to me.)

**Comment by samip5** [comment]
> I will note that as a symptom of #646, the project seems broken to newcomers. (Hint: _":latest"_ doesn't work. And your decision not to include instructions for getting the right tag the first time doesn't seem sensible to me.)

It's sad that you feel like that, but using latest was a issue we had, as that wasn't being updated at all. People seem to expect it to work when they're newcomers to containers, but that doesn't mean that we should support it.

**Comment by tinco** [comment]
@laur89 @samip5 I completely agree with the decision to not support the `:latest` tag in the baseimage, and I don't agree with @richb-hanover 's position that we should support it to accommodate newcomers, as recommending bad practices to newcomers is obviously a bad idea.

However despite the disagreement, @richb-hanover did follow through and submitted a merge request with something that is a clear improvement over the documentation. It does not feel like excessive hand holding to me, especially since this project is a base image, it is actually a good thing if it is being used by newcomers.

If possible, I would suggest putting the disagreement over the `:latest` tag from your mind and reviewing the improvements from a neutral perspective.

Thanks!

**Comment by richb-hanover** [comment]
Here are my last thoughts: as project maintainers, you can decide how to proceed.

1. I'm not an expert in using Docker. As a relative newcomer, I have heard lots of voodoo surrounding the "right way to do things". One is that "Using _latest_ is a good idea." (Not that it's necessarily true, and it seems that you have good reasons not to support it.)

2. It is never a bad idea to tell people what TO do. I would encourage you to tweak the PR (#645) to state what's correct. You should definitely note that the container is available on both hub.docker.com as well as ghcr.io (to prevent newcomers from developing a mythology that one version is "better" than the other...)

Thanks for listening.
