### ISSUE TITLE
Trusted build

### ISSUE THREAD

**Issue by gissehel** [phusion/baseimage-docker#68]
Not really an issue here but as many people where yelling for a trusted build on the page https://index.docker.io/u/phusion/baseimage/ , I created one on https://index.docker.io/u/gissehel/phusion-baseimage/ .

I named it "phusion-baseimage" because "phusion's baseimage" is the most meaningfull title I found. On the other hand, it contains the term "phusion" in it, which you may not like.

If this is a problem, I can delete the docker index's repo and github repo (for that reason or any other reason like you provided trusted builds, or you just don't like the idea).

**Comment by Theaxiom** [comment]
Trusted builds have been replaced with automated builds: https://docs.docker.com/docker-hub/builds/#add-and-run-a-new-build
